cli/src/org/partiql/cli/main.kt
cli/test/org/partiql/cli/functions/WriteFileTest.kt
docs/user/CLI.md

I found occurrences to "sqlcli" in the documentation that make me think that it is an original name of "partiql" and that these occurrences were forgotten before the release.
For the sake of everyone's understanding, I would like to fix them.

Replaced "sqlcli" occurences to "partiql"

---

docs/tutorial/tutorial.md

Minor typing mistake in the tutorial that wouldn't be picked up by a spell checker.

Typing mistake in tutorial

---

build.gradle
lang/build.gradle
lang/gradle.properties

This is being done in preparation for publishing to maven central.
To ensure the ability to publish development versions of the library to the local maven repository for developers that do not have the GPG keys installed is not broken, we only attempt to sign the build artifacts when we are not building a "-SNAPSHOT" version.

Issue #118, generate pom.xml and sign build artifacts

---

testscript/pts/test-scripts/temp/temp.sqlts
testscript/src/org/partiql/testscript/junitRunner/PtsRunner.kt

While preparing to delete the old testframework I noticed that the new `:pts` project wasn't failing tests that should have been failing.
I traced the problem to the `PtsRunner` class, which was identifying test failures correctly but was incorrectly notifying the `RunNotifier` instance.  It was calling `fireTestStarted` for every test but only calling `fireTestFinished` for tests that passed and only calling `fireTestFailed` instead.  (The [RunNotifier javadoc](http://junit.sourceforge.net/javadoc/org/junit/runner/notification/RunNotifier.html#fireTestFinished(org.junit.runner.Description)) states that it should always be called because runners expect `fireTestStarted` and `fireTestFinished` calls to occur in pairs.
This problem manifested itself in the command-line Gradle build (and …

Test script runner fix

---

.travis.yml
build.gradle
cli/build.gradle
examples/build.gradle
lang/build.gradle
pts/build.gradle
testscript/build.gradle

Closes #45 
This PR adds `.travis.yml` and enables JaCoCo for all subprojects. 
Send request to the PartiQL Github Organization to allow Travis and Codecov.io access to this repo.
Once the request is accepted the token setup for Codecove needs to be passed to the Travis configuration.
I tried to remove duplication of Gradle code from sub projects as much as I could from my (limited) Gradle knowledge. There is still some replication (see reports configuration block in each sub-project). I tried some ideas from Google searches but they did not work for this project's setup.
I am open to any other ideas that could remove Gradle code duplication.  
Links to builds and code coverage reports:
* [Travis …

(Build) Enable travis and codecoverage 

---

.travis.yml

JDK8 builds tend to go over the 10 minute TTL from travis and get killed. `travis_wait` extends that TTL to 20 minutes. 

(Build) Extend Travis TTL to 20 minutes 

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/test/org/partiql/lang/eval/JoinWithOnConditionTest.kt
testscript/pts/test-scripts/join/join-with-condition.sqlts

Expression given as `ON` for `JOIN` treat Unknowns (`null`, `missing`) as `false` removing the row from JOIN's result set. 

(Eval)  Null as false for Join with On condition

---

cli/src/org/partiql/cli/main.kt
lang/src/org/partiql/lang/util/ExprValueFormatter.kt

This was happening any time the REPL attempted to pretty print a `FLOAT`, `TIMESTAMP`, `SYMBOL`, `CLOB`, `BLOB`, or  `SEXP`.
The problem was caused because the instance of `IonWriter` returned from `IonSystemBuilder.standard().build(outputStream)` closes the `OutputStream` when `IonWriter.close()` is called.  (We should also consider if this is a bug in `ion-java` or not and if its possible to fix this since this behavior is now expected in places where it is currently being used.
In any case, this PR implements a simple work-around.

Fix issue causing the REPL's output stream to be prematurely closed

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt

resolves #25
Uses a `TreeSet` with the default comparator when the right argument of an IN clause is a list of literals speeding up the predicate. Changes make IN clause for this use case between ~14% to ~30% faster. 
Benchark setup is the query `SELECT COUNT(*) FROM myTable t WHERE t IN <IN_LIST>` where IN list has 10, 100, 1,000 or 5,000 literals and `myTable` is always a list with 10,000 elements. To trigger the query we are forced to call `ionValue` on the resulting `ExprValue` so we use a `COUNT` to minimize the the time spent materializing Ion objects in that operation. 
Benchmark numbers bellow: 
```
InClauseWithLiterals.optimizedWith5000Literals  thrpt   10   0.110 ± 0.027  ops/s
InClauseWithLiterals.with5000Literals …
```

Uses a set to optimize IN clause when right side is all literals

---

README.md

Simply changes the Maven URL to point to:
https://search.maven.org/artifact/org.partiql/partiql-lang-kotlin
Instead of:
https://search.maven.org/artifact/org.partiql/partiql-lang-kotlin/0.1.0/jar
This way we don't have to update it with every version bump.

Change Maven URL so it doesn't include a version

---

README.md
build.gradle

Removes `-SNAPSHOT` and MV bumps the recommended version in `README.md`.

Prepare for v0.1.2 release

---

cli/src/org/partiql/cli/Cli.kt
cli/test/org/partiql/cli/CliTest.kt

resolves #206
Closes the output writer for the `PARTIQL` output format so the output is actually flushed 

Closes CLI stream for partiql format

---

lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

Fixes #228 
This sanity check threw an exception from SqlParser whenever a data type reference that included more than one argument was encountered.  The check appears to have been completely erroneous from the start and on removivng it, no other modifications were needed.
This commit also adds a few tests to SqlParserTests to cover this scenario and prevent regressions.

Fix #228 by removing invalid sanity check.

---

README.md
build.gradle

The `v0.1.3` branch was created so we can do a hotfix.  This PR accounts for the version bump that was required: 
- Change 0.1.3 to 0.1.4 in root `build.gradle`
- Change 0.1.2 to 0.1.3 in `README.md` so it displays the correct version on
the repository home page.

Bump minor versions after v0.1.3 hotfix was released separately

---

lang/src/org/partiql/lang/syntax/SqlLexer.kt
lang/test/org/partiql/lang/syntax/SqlLexerTest.kt

Previously, "//" to EOL was being treated as an Ion comment and removed,
when between "{{" and "}}".
Fixes #236.

Make SqlLexer aware of Ion BLOBs and CLOBs (#236)

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt

Fixes #246
We previously ignored this compile option.  The fix prevents the filtering of `MISSING` values from star projection when `ProjectionIterationBehavior.UNFILTERED` is set. 

Respect ProjectionIterationBehavior.UNFILTERED within star projection

---

cli/src/org/partiql/cli/Repl.kt
cli/test/org/partiql/cli/ReplTest.kt

#248 CLI: Execute PartiQL query when a line ending with a semi-colon is read
Add a new state to the REPL state machine, `LAST_PARTIQL_LINE`. Transition to this state from `READY` or `READ_PARTIQL` when the input line ends with a `;`. `LAST_PARTIQL_LINE` simply appends the current line to the buffer and transitions to the `EXECUTE_PARTIQL` state.

Execute PartiQL query when a line ending in a semi-colon is read.

---

.github/no-response.yml

Use the label `more-information-needed` when an issue requires more
information from the issue's author. If the issue's author does not
respond within 14 days, the bot will auto-resolve the issue.
see https://github.com/probot/no-response

Configures auto-respond bot.

---

buildSrc/build.gradle
lang/build.gradle
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

And a minor issue is discovered with the `ion-element` API as well, which I've created a issue for.

Migrate to PIG 0.2.0

---

lang/test/org/partiql/lang/ast/passes/StaticTypeRewriterTests.kt

I received a second question over Chime today about the purpose of these comments, indicating that their purpose wasn't immediately clear.  

Explain purpose of numeric comments in StaticTypeRewriterTests

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt

Review usage of Internal flag for EvaluationException. 

Set internal flag for incorrect parameter count

---

cli/test/org/partiql/cli/ReplTest.kt

This race condition is not caused by production code--just the tests.
This one is driving me bonkers--I don't have the time to fix this properly right now.  I've created #266 so we don't forget to un-`@Ingore` this later.

Temporarily disable REPL tests due to race condition.

---

lang/build.gradle

This is needed so clients do not need to take a separate dependency on the PIG runtime library.

Expose pig-runtime as API dependency

---

lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstSanityValidator.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/syntax/LexerConstants.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/ast/AstNodeTest.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

Part 1 of implementation for `LET` clause (#179) as defined in the high-level [spec](https://github.com/partiql/partiql-spec/issues/15).
Currently just implementing `LET` following `FROM` clauses as they are what's most clearly defined in the high-level spec and use cases.
Future supported clauses will be added later (especially because of #281, _Incorrect execution order for_ `LIMIT` _clause during query execution_)
Current status relating to `LET` following `FROM` clauses (from_let):
(Evaluation to be done in a separate PR before merging into `from-let-final` feature branch)
Possible additions:
- test conversion between `PartiqlAst` and `ExprNode`
- test V0 ast (de)serializer outputs intended error when parsing `LET` clauses …

LET (from `FROM` clauses) implementation - Parsing and ExprNode conversions

---

lang/src/org/partiql/lang/util/NumberExtensions.kt
lang/test/org/partiql/lang/util/NumbersTest.kt

Closes #293 
`bigDecimalOf` special cased `Decimal.NEGATIVE_ZERO` in a `when` clause and then cast to `Decimal`. This caused a class cast exception because `BigDecimal.ZERO == Decimal.NEGATIVE_ZERO` leading to a downcast that failed. 

fix: bigDecimalOf no-ops when given an Ion decimal 

---

lang/build.gradle
lang/test/org/partiql/lang/ast/PathComponentExprTest.kt
lang/test/org/partiql/lang/ast/SourceLocationMetaTest.kt
lang/test/org/partiql/lang/ast/VariableReferenceTest.kt
lang/test/org/partiql/lang/ast/passes/AstWalkerTests.kt
lang/test/org/partiql/lang/ast/passes/SubstitutionRewriterTest.kt
lang/test/org/partiql/lang/eval/EvaluationSessionTest.kt
lang/test/org/partiql/lang/eval/ExprValueFactoryTest.kt
lang/test/org/partiql/lang/eval/LikePredicateTest.kt
lang/test/org/partiql/lang/eval/NodeMetadataTest.kt
lang/test/org/partiql/lang/eval/builtins/TimestampParserTest.kt
lang/test/org/partiql/lang/eval/builtins/TimestampTemporalAccessorTests.kt
lang/test/org/partiql/lang/eval/builtins/timestamp/TimestampFormatPatternParserTest.kt
lang/test/org/partiql/lang/util/AstExtensions.kt
lang/test/org/partiql/lang/util/ConfigurableExprValueFormatterTest.kt

This allows us to start using JUnit5 APIs now without having to migrate the entire test suite to JUnit5.
JUnit5 has better assertions and test parameterization that is well integrated with the IDE which will improve developer productivity.

Add JUnit5 and vintage compatibility layer.

---

lang/src/org/partiql/lang/syntax/LexerConstants.kt
lang/src/org/partiql/lang/syntax/SqlLexer.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt
lang/test/org/partiql/lang/eval/builtins/DateAddEvaluationTest.kt
lang/test/org/partiql/lang/eval/builtins/DateDiffEvaluationTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
testscript/pts/test-scripts/builtin-functions/date_add.sqlts
testscript/pts/test-scripts/builtin-functions/date_diff.sqlts

This also required adding/enhancing parser support for the special
functions extract, date_add and date_diff functions all of which
have special syntax.
This is "technically" a breaking chance as evidenced by the
changes required to the tests related to these which previously
expected these keywords to be values instead of the grammatical
elements that they actually are.  For instance, this commit
removes several tests that attempt to pass NULL and MISSING
values instead of a date part to these functions.
Fixes #121 and #314.

Stop treating date parts as if they are string literals

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerLimitTests.kt

Fix `LIMIT` clause execution order

---

build.gradle

Fix to `build.gradle` that was causing build failures.
`rersion` -> `version`

Fix typo in build.gradle

---

lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

Adds parsing and PIG definition of stored procedure calls with the unnamed argument syntax defined in PartiQL spec issue #[17](https://github.com/partiql/partiql-spec/issues/17).
A valid call to a stored procedure as part of this PR is defined by `EXEC <symbol> [<expr>.*]` and is only a valid PartiQL statement when in the top level query.

Stored Procedures - call with unnamed args (parsing + PIG definition)

---

lang/src/org/partiql/lang/eval/visitors/SelectListItemAliasVisitorTransform.kt
lang/test/org/partiql/lang/eval/visitors/SelectListItemAliasVisitorTransformTests.kt

Fixes #321. Also adds a deeper nested `SELECT` test case.

Fix for SelectListItemAlias subqueries

---

build.gradle
cli/build.gradle
examples/build.gradle
pts/build.gradle
testscript/build.gradle

Gradle was previously not running any of the `ParameterizedTest`s and possibly other JUnit5 tests.
Tested by running `./gradlew build` with a failing `ParameterizedTest` to ensure the test fails appropriately.

Fix to gradle to run on `ParameterizedTest`s

---

build.gradle
cli/src/org/partiql/cli/Repl.kt
cli/test/org/partiql/cli/ReplTest.kt

Adds current PartiQL version number (from gradle) and the most recent commit hash to the CLI output.
Example output shown below:
```
Welcome to the PartiQL REPL!
Using version: 0.2.5-SNAPSHOT-6786c36
PartiQL> 1+1;
==='
2
---
OK!
```
This approach follows from this similar stackoverflow [answer](https://stackoverflow.com/a/50119235). Essentially, the root `build.gradle` file will output the `version` to a file in the Gradle build, which can be accessed as a resource by the CLI/REPL.
Retrieving the most recent commit hash follows this stackoverflow [answer](https://stackoverflow.com/a/35041457). We similarly store the commit hash to a Gradle build file.
Also, some existing REPL tests (previously ignored by #266) were updated to incorporate this change.
By submitting this pull request, I …

Add version number to CLI output

---

examples/src/kotlin/org/partiql/examples/CustomProceduresExample.kt
examples/src/kotlin/org/partiql/examples/util/Main.kt
examples/test/org/partiql/examples/CustomProceduresExampleTest.kt
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/errors/ErrorAndErrorContexts.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/builtins/storedprocedure/BuiltinProcedures.kt
lang/src/org/partiql/lang/eval/builtins/storedprocedure/StoredProcedure.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerExecTests.kt

Implements evaluation of stored procedure calls with unnamed argument syntax defined in PartiQL spec issue #[17](https://github.com/partiql/partiql-spec/issues/17).
This should be reviewed **after** the parsing of stored procedure calls (#333) is merged into the `stored-procedures` feature branch.

Stored Procedures - call with unnamed args (evaluation)

---

lang/test/org/partiql/lang/eval/builtins/TimestampExtensions.kt

Fixes #229.
This issue was kind of bugging me from a GH actions [build failure](https://github.com/partiql/partiql-lang-kotlin/runs/1560219706?check_suite_focus=true) from the other day.
The year needs to be an integer between 1 and 9999 inclusive. The [previous code](https://github.com/partiql/partiql-lang-kotlin/blob/de1fe32b1d535a9d56b3337b1de9c10780422745/lang/test/org/partiql/lang/eval/builtins/TimestampExtensions.kt#L44) would 
1. generate a random int
2. take the absolute value
3. modulo 9999
4. add 1
However, taking `abs(Int.MIN_VALUE) = Int.MIN_VALUE`, so the resulting year would be negative. The correct order of operations should be 
1. generate a random int
2. **modulo 9999**
3. **take the absolute value**
4. add 1
I also fixed this for the `seconds` argument.
By submitting …

Fixes `TimestampTemporalAccessorTests` negative year

---

examples/src/java/org/partiql/examples/CSVJavaExample.java

Add <ExprValue> to getBindings return type to fix the following
javac unchecked warning:
```
examples/src/java/org/partiql/examples/CSVJavaExample.java:72:
warning: [unchecked] getBindings() in CsvRowExprValue implements
getBindings() in ExprValue
```

CSVJavaExample.java: Fix unchecked warning

---

cli/src/org/partiql/cli/Cli.kt
cli/src/org/partiql/cli/main.kt
docs/user/CLI.md

The interactive REPL prints PartiQL results in a "pretty" format with
newlines and indentation. The non-interactive command line tool does
not. This adds --output-format=PARTIQL_PRETTY to print results in the
same format.
Example result without --output-format:
<<{'employeeName': 'Bob Smith', 'projectName': 'AWS Redshift Spectrum querying'}, {'employeeName': 'Jane Smith', 'projectName': 'AWS Redshift security'}>>
Example result with --output-format=PARTIQL_PRETTY
<<
{
'employeeName': 'Bob Smith',
'projectName': 'AWS Redshift Spectrum querying'
},
{
'employeeName': 'Jane Smith',
'projectName': 'AWS Redshift security'
}
>>

cli: Add --output-format=PARTIQL_PRETTY for non-interactive use

---

cli/build.gradle
cli/test/org/partiql/cli/CliTest.kt
examples/build.gradle
examples/src/kotlin/org/partiql/examples/CsvExprValueExample.kt
examples/src/kotlin/org/partiql/examples/CustomFunctionsExample.kt
examples/src/kotlin/org/partiql/examples/ParserErrorExample.kt
examples/src/kotlin/org/partiql/examples/ParserExample.kt
lang/build.gradle
pts/build.gradle
testscript/build.gradle

The following gradle targets were not running any of the unit tests
contained in their directories due to incorrect test dependencies. It
appears these projects all use JUnit 5 "vintage" tests, so need that
engine as a test dependency.
:cli:test
:examples:test
:pts:test
CliTest: Add test for the PARTIQL_PRETTY output format added in commit
91750026f1. This was how I discovered this issue.
examples: Remove tests from the implementation dependencies.

gradle: fix test target for cli, examples, pts

---

examples/Readme.md
examples/src/kotlin/org/partiql/examples/CustomProceduresExample.kt
examples/src/kotlin/org/partiql/examples/util/Main.kt
examples/test/org/partiql/examples/CustomProceduresExampleTest.kt
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/errors/ErrorAndErrorContexts.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/builtins/storedprocedure/StoredProcedure.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerExecTests.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

Adds the ability to create custom stored procedures and call them with the `EXEC` clause, following the description given in this [issue](https://github.com/partiql/partiql-spec/issues/17).
Also provides a simple custom stored procedure [example](https://github.com/partiql/partiql-lang-kotlin/blob/stored-procedure/examples/src/kotlin/org/partiql/examples/CustomProceduresExample.kt).
Previously approved PRs part of this PR:
- parsing + PIG definition https://github.com/partiql/partiql-lang-kotlin/pull/333
- evaluation + example https://github.com/partiql/partiql-lang-kotlin/pull/335

Add stored procedure calls with unnamed args

---

lang/src/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransform.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt
lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt

Fixes #212.
The cause appears to be from the `AggregateSupport(Rewriter/VisitorTransform)`, which at a high level, populates a meta containing information about the query's aggregation functions. 
It was not correctly excluding subqueries when creating a list of aggregates. So in a query with aggregates in a subquery such as `SELECT 1 FROM (SELECT COUNT(1) FROM foo)`, the outer `SELECT`'s metas would contain the subquery's aggregate metas. Because of this, the wrong evaluation path was taken in the `EvaluatingCompiler`:https://github.com/partiql/partiql-lang-kotlin/blob/de1fe32b1d535a9d56b3337b1de9c10780422745/lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt#L972

Fix to aggregate being used in subquery binding error

---

docs/user/BuiltInFunctions.md
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/org/partiql/lang/eval/builtins/BuiltinFunctions.kt
lang/src/org/partiql/lang/eval/builtins/FromUnixTimeFunction.kt
lang/src/org/partiql/lang/eval/builtins/UnixTimestampFunction.kt
lang/test/org/partiql/lang/eval/builtins/FromUnixTimeFunctionTest.kt
lang/test/org/partiql/lang/eval/builtins/UnixTimestampFunctionTest.kt

Adds functions to convert from UNIX epoch to TIMESTAMP and TIMESTAMP to UNIX epoch. Largely follows MySQL's variants: [FROM_UNIXTIME](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_from-unixtime) and [UNIX_TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_unix-timestamp).
Still might need discussion on:
- Better names for the functions. I just followed MySQL's convention given that I couldn't find similar functions in other DBMS and SQL-92 standard. Perhaps `UNIX_TO_TIMESTAMP` and `TIMSTAMP_TO_UNIX` would be better?
- Supporting a format argument when converting UNIX epoch -> TIMESTAMP. This is an additional argument in MySQL's version, but this may be better served as its own function.
- Datatype input for UNIX epoch …

Add UNIX epoch <-> TIMESTAMP conversion functions

---

docs/dev/RewriterToVisitorTransformGuide.md

Adds Rewriter to VisitorTransform guide.
Rendered markdown can be viewed [here](https://github.com/partiql/partiql-lang-kotlin/blob/add-rewriter-to-vt-doc/docs/dev/RewriterToVisitorTransformGuide.md).

Add Rewriter to VisitorTransform guide

---

lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

Issue #363 
Fixes parser by traversing and validating the parse tree to ensure that the top level tokens are not present at the level(s) below. 

Fixes parser for the top level tokens

---

lang/test/org/partiql/lang/eval/LikePredicateTest.kt

#32 appears to have been inadvertently fixed by #286.  Inadvertent yes, but still a good thing. :)
This PR simply adds a regression test for it.

Add regression test for multi-codepoint LIKE patterns

---

lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/ExprValueType.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt

Adds support for parsing parsing date literals. Syntax for the date literal is `DATE 'YYYY-MM-DD'`.

Adds support for parsing date literals

---

lang/src/org/partiql/lang/eval/builtins/SizeExprFunction.kt
lang/test/org/partiql/lang/eval/builtins/SizeEvaluationTest.kt

Make SIZE function work with s-expressions.

---

lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt

This PR adds more parser error tests to validate the behavior for the top level tokens which was introduced with the PR #369.  

Add more parser error tests to validate top level tokens

---

lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/ExprValueType.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

* Extends `SqlParser` to support `TIME` literals.
* Supports parsing optional `precision` and optional TIME ZONE specifier `WITH TIME ZONE` for `TIME` literals.
* Adds tests covering positive and negative cases for `TIME` literals.
*  Uses `LocalTime` and `OffsetTime` java classes for parsing and validating `TIME` strings.

Added Parser support for TIME literals

---

lang/src/org/partiql/lang/ast/SourceLocationMeta.kt
lang/src/org/partiql/lang/ast/passes/StatementRedactor.kt
lang/test/org/partiql/lang/ast/passes/StatementRedactorTest.kt

Closes #375.
Migrates `StatementRedactor` to PIG-generated visitor. Additionally does some initial cleanup and adds tests for `Concat` and `Parameter`.

Migrates StatementRedactor to PIG-generated visitor (#375)

---

cli/src/org/partiql/cli/Cli.kt
cli/test/org/partiql/cli/CliTest.kt

**Issue #, if available:**
Fixes #207 
**Description of changes:**
Causes all top-level ion values to be delimited by a newline when using the ION_TEXT output format, and the full output is terminated by a newline.
----

Change ION_TEXT output format to put each top-level ion value on a newline

---

lang/src/org/partiql/lang/ast/ast.kt

Changed AST `iterator()` to use mutable list for optimizing performance. 

Optimizes AST iterator

---

README.md
build.gradle
lang/src/org/partiql/lang/ast/ast.kt

* Prepare "hotfix" release `v0.1.5`
* Hotfix for optimizing the performance of AST `iterator()` for queries with large number of nodes.   

v0.1.5 Hotfix Release

---

lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/ast/AstDeserialization.kt
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstVisitor.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/visitors/FromSourceAliasVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/GroupByItemAliasVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/PipelinedVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/SelectListItemAliasVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/SelectStarVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/StaticTypeVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/SubstitutionVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/VisitorTransformBase.kt
lang/src/org/partiql/lang/eval/visitors/VisitorTransforms.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/src/org/partiql/lang/util/ThreadInterruptUtils.kt
lang/test/org/partiql/lang/thread/EndlessTokenList.kt
lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt

A few times over the past few years we've received reports from a PartiQL service where with a customer sending a very large  query (in terms of size of the SQL), where PartiQL would take a long time (>30s) to parse, rewrite, validate, and compile.  
Although we have optimized every case where this has happened, this PR applies a mitigation measure which can be used in case it happens again.  I have identified several "hot" loops where the state of `Thread.interrupted()` can be polled and if set an `InterruptedException` is thrown.  This is the hope that if such a query is encountered again, it can be aborted by the calling code rather than risk causing service outages.  This approach still might miss loops that we did not anticipate would become hot in the case of unexpected user input, …

Adds Compile-Time `Thread.interrupted()` checks

---

build.gradle
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/ast/AstDeserialization.kt
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstVisitor.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/src/org/partiql/lang/util/ThreadInterruptUtils.kt
lang/test/org/partiql/lang/ast/AstNodeTest.kt
lang/test/org/partiql/lang/thread/EndlessExprNodeList.kt
lang/test/org/partiql/lang/thread/EndlessTokenList.kt
lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt

Just like the title says, no new implementation, but there was changes to the unit tests:
For some reason I still don't fully understand, the tests added in PR #398 to the started consuming more than 4gb of RAM after being cherry-picked to the `v0.1.6` branch, which would cause the build fail since the JVM was limited to 4gb.  I tried increasing the RAM allocated to the JVM but wasn't able to get it to run correctly until 6gb and 7gb is the maximum amount of memory allowed by GitHub actions, which I know we will likely migrate to some day soon.  That was cutting it pretty close, so I was felt it was better to reduce memory consumption of the tests, so this PR includes changes that reduce the memory consumption of the tests.
By submitting this pull request, I confirm that my contribution …

Cherry-pick PR #398 to v0.1.6 branch and optimize test memory usage

---

lang/test/org/partiql/lang/thread/EndlessList.kt
lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt

For some reason I still don't fully understand, the tests added in PR #398 to the started consuming more than 4gb of RAM after being cherry-picked to the `v0.1.6` branch, which would cause the build fail since the JVM was limited to 4gb.  I tried increasing the RAM allocated to the JVM but wasn't able to get it to run correctly until 6gb and 7gb is the maximum amount of memory allowed by GitHub actions, which I know we will likely migrate to some day soon.  That was cutting it pretty close, so I was felt it was better to reduce memory consumption of the tests in that branch and decided to apply a similar fix to `master` in this PR. 

Reduce memory usage of Thread.interrupted() tests

---

lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/org/partiql/lang/eval/NaturalExprValueComparators.kt
lang/src/org/partiql/lang/eval/time/Time.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerDateTimeTests.kt
lang/test/org/partiql/lang/eval/NaturalExprValueComparatorsTest.kt

Resolves #394 
Adds comparison operations for `DATE` and `TIME` `ExprValues`.

Adds comparison operators for DATE and TIME

---

lang/test/org/partiql/lang/eval/EvaluatingCompilerDateTimeTests.kt

The name of this class was breaking some internal tooling.

Renames TimeForTest -> TimeForValidation

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/visitors/GroupByPathExpressionVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/SelectStarVisitorTransform.kt
lang/src/org/partiql/lang/eval/visitors/VisitorTransformBase.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt

Fixes #417
Dropping the `ORDER BY` clause prevents the `EvaluationException` from being thrown by `EvaluatingCompiler` due to not having evaluation support for `ORDER BY`, effectively ignoring the `ORDER BY` clause.

Prevent the ORDER BY clause from being dropped in visitor transforms

---

lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt

Fixes leap year logic in SqlParserDateTimeTests's random date generator.

---

buildSrc/build.gradle
lang/build.gradle

It seems there are no breaking API changes in PIG `v0.3.2` so this is all that's needed.

Update PartiQL IR Generator Dependency to v0.3.2

---

lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

Refactors `SqlParser.parseUnaryTerm` so it does not attempt to
needlessly re-parse every sub-expression of the `not` unary operator.
This effect was cumulative, so that multiple nestings of `not` would
become pathologically slow.

Fix bug causing multiple nested `not`s to parse very slowly

---

lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

Refactors `SqlParser.parseUnaryTerm` so it does not attempt to
needlessly re-parse every sub-expression of the `not` unary operator.
This effect was cumulative, so that multiple nestings of `not` would
become pathologically slow.
(cherry picked from commit 6de9ca0d42b18d72c3f81bf62c6a9faa0cc1d033)
This will be for the v0.2.7 release.

Cherry picks "Fix bug causing multiple nested `not`s to parse very slowly (#436)" for v0.2.7 release

---

lang/src/org/partiql/lang/eval/Bindings.kt
lang/src/org/partiql/lang/eval/ExprValueFactory.kt
testscript/src/org/partiql/testscript/compiler/Compiler.kt

LazyThreadSafetyMode.NONE literally means that accessing
the lazy value from multiple threads can cause an NPE.
Unfortunately, we assumed NONE would be implemented such
that a lazy value could be initialized by multiple
threads without throwing an NPE, with race conditions
only possibly occurring inside the initializer block.
However, that is actually the behavior is for
LazyThreadSafeteyMode.PUBLICATION.
(cherry picked from commit eef183c7853f8f8561f7ee487ab13f179ec0dbf9)
This will be for the v0.2.7 release.

Cherry picks "Use LazyThreadSafteyMode.PUBLICATION instead of NONE (#433)" for v0.2.7 release

---

lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

Refactors `SqlParser.parseUnaryTerm` so it does not attempt to
needlessly re-parse every sub-expression of the `not` unary operator.
This effect was cumulative, so that multiple nestings of `not` would
become pathologically slow.
(cherry picked from commit 6de9ca0d42b18d72c3f81bf62c6a9faa0cc1d033)
This will be for the v0.1.7 release.

Cherry picks "Fix bug causing multiple nested `not`s to parse very slowly (#436)" for v0.1.7 release

---

lang/src/org/partiql/lang/eval/Bindings.kt
lang/src/org/partiql/lang/eval/ExprValueFactory.kt
testscript/src/org/partiql/testscript/compiler/Compiler.kt

LazyThreadSafetyMode.NONE literally means that accessing
the lazy value from multiple threads can cause an NPE.
Unfortunately, we assumed NONE would be implemented such
that a lazy value could be initialized by multiple
threads without throwing an NPE, with race conditions
only possibly occurring inside the initializer block.
However, that is actually the behavior is for
LazyThreadSafeteyMode.PUBLICATION.
(cherry picked from commit eef183c7853f8f8561f7ee487ab13f179ec0dbf9)
This will be for the v0.1.7 release.

Cherry picks "Use LazyThreadSafteyMode.PUBLICATION instead of NONE (#433)" for v0.1.7 release

---

lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/syntax/LexerConstants.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/ast/AstNodeTest.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

*Issue #422, task 2: Implement `OFFSET` in lexer, parser, and `ExprNode` conversions*
1. `ExprNode` representation of `OFFSET` 
2. Conversion between `PartiqlAst` and `ExprNode` for `OFFSET` 
3. V0 Ast Serliazation for `OFFSET` 
4. Parsing of `OFFSET` in Parser
4. Other minor changes to make code able to be compiled 
5. Test cases for `OFFSET` in Parser

Add offset parser

---

lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

This PR aims to better the code in file 'SqlParserTestBase'. 
1. Changed variables name. e.g. originally, for actual values, some variables use `actual` or `parsed` as prefix, while some do not have prefix. Now change them into a uniform prefix `actual`. 
2. Removed unuseful code. 
3. Refactored the code in `assertExpression`.

Better SqlParserTestBase 

---

examples/src/kotlin/org/partiql/examples/ParserErrorExample.kt
examples/src/kotlin/org/partiql/examples/ParserExample.kt
examples/src/kotlin/org/partiql/examples/PreventJoinVistor.kt
lang/jmh/org/partiql/jmh/PartiQLBenchmark.kt
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/ast/passes/StatementRedactor.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/test/org/partiql/lang/ast/passes/StatementRedactorTest.kt
lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt
lang/test/org/partiql/lang/eval/visitors/VisitorTransformTestBase.kt
lang/test/org/partiql/lang/syntax/SqlParserPrecedenceTest.kt

*This PR aims to remove dependencies on `parseExprNode` method from Parser as much as possible*
Changed `parseExprNode` into `parseAstStatement` in multiple files. 
1. Some test files which are just for testing `ExprNode`. 
2. 'RewriterTestBase' and related files which currently do not support PIG AST. 
3. The files which are involved with Evaluator. Will change them once we are doing the work on deprecating `ExprNode` in Evaluator . 
The file 'PreventJoinVisitor.kt' uses `ExprNode` to iterate the AST. However, since currently the PIG AST is not iterable, will need to see if there is another way to iterate the AST in format of PIG.

Removed dependencies on `parseExprNode` from parser

---

lang/src/org/partiql/lang/ast/AstDeserialization.kt
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

*This PR is aimed to fix the bug causing 3 test cases failed in FB-deprecate-ExprNode branch*
1. The `CreateIndex` in `ExprNode` AST has a field `tableName`, which is a `String` type, as shown [here](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/org/partiql/lang/ast/ast.kt#L480). However, in PIG AST, it is an `identifier`, as shown [here](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/resources/org/partiql/type-domains/partiql.ion#L275).
2. Similarly for `DropIndex`, refer to [here](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/org/partiql/lang/ast/ast.kt#L507) (`ExprNode`) and [here](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/resources/org/partiql/type-domains/partiql.ion#L280) (PIG AST).
3. Similarly for …

Fixed bug for 3 failed test cases

---

lang/test/org/partiql/lang/eval/visitors/StaticTypeVisitorTransformTests.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

1. Changed `parse` method so it uses `parseAstStatement` to produce PIG AST node instead of `ExprNode`. Also, changed a few function's signature so they receive PIG AST node now, instead of `ExprNode`. 
2. Removed `assertRoundTripIonElementToPartiQlAst` and `assertRoundTripPartiQlAstToExprNode` and merged the checks into `pigDomainAssert`. 
3. Removed the check for actual value after round trip transformation: `ExprNode` -> PIG AST -> `SexpElement` -> PIG AST -> `ExprNode`. 
4. Changed round trip order in `assertRoundTripPigAstToExprNode` from (`ExprNode` -> PIG AST -> `ExprNode`) into (PIG AST -> `ExprNode` -> PIG AST). 
5. See other changes in comments.

Removed `ExprNode` in SqlParserTestBase as much as possible

---

docs/dev/RELATIONAL-ALGEBRA.md
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/domains/PartiqlAlgebraUtils.kt
lang/src/org/partiql/lang/domains/util.kt
lang/src/org/partiql/lang/planner/AstToAlgebra.kt
lang/test/org/partiql/lang/planner/AstToAlgebraTests.kt

This is the absolute beginning of PartiQL's experimental relational algebra which will be used to optimize PartiQL queries.  It's very early in its design so far.  For instance, many more operators other than the 4 defined so far are needed.  These will be defined later, incrementally.
This PR will merge to the `query-planner` branch where we will be also be building an experimental planner. 
- `docs/dev/RELATIONAL-ALGEBRA.md`  is intended to be the long term home for the documentation of the relational algebra.  Start there for details.
- `partiql.ion` includes a permuted PIG domain for the algebra. 
- Also included is a `astToAlgebra` function which performs conversion from the AST to the relational algebra.
By submitting this pull request, I confirm that my contribution is made under …

Inital definition of PartiQL's relational algebra and converstion from the AST

---

cli/src/org/partiql/cli/functions/ReadFile.kt
cli/src/org/partiql/cli/functions/WriteFile.kt
cli/test/org/partiql/cli/functions/ReadFileTest.kt
lang/build.gradle
lang/src/org/partiql/lang/eval/io/DelimitedValues.kt
lang/test/org/partiql/lang/eval/io/DelimitedValuesTest.kt

*This PR aims to resolve the issue on CLI reading CSV files reported in Issue #366*
Originally, we were implementing the CSV file reader for CLI by ourselves. Our implementation does not follow the standard CSV format as defined in [rfc4180](https://datatracker.ietf.org/doc/html/rfc4180), and it casues the following problems: 
1. Cannot recognize the double quotes escape. As a result, the comma in between double quotes escape are considered as a delimiter in a line. 
2. Cannot ignore the the empty lines. 
3. Each row can have different numbers of fields. 
This PR migrates from the self-implemented CSV reader to a standard [Apache CSVParser library](https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVParser.html). Thus, all the above problems except the last one …

Replaced self-implemented CSV file reader with Apache CSVParser for CLI

---

cli/src/org/partiql/cli/Cli.kt
cli/src/org/partiql/cli/main.kt
cli/src/org/partiql/cli/streams.kt
cli/test/org/partiql/cli/CliTest.kt
docs/user/CLI.md

*Issue #475*
1. Fixed the issue by assuming the input data is empty, if users do not explicit specify the input data argument while using CLI. 
2. Creates one test case to cover the case.

Fixed the bug on CLI command with input argument

---

cli/src/org/partiql/cli/Cli.kt
cli/test/org/partiql/cli/CliTest.kt

*Issue #473*
As show in https://github.com/partiql/partiql-lang-kotlin/blob/main/cli/src/org/partiql/cli/Cli.kt#L52-53, the `use` block in L52 invokes `close()` function on `output`. In case of `FileOutputStream`, it indeed closes the output stream. Thus, the `write()` function in L53 throws an exception. 
1. Move L53 into the `use` block. 
2. Create a test case to cover file output.

Fixed bug on CLI output IONTEXT to file

---

examples/src/kotlin/org/partiql/examples/ParserErrorExample.kt
examples/src/kotlin/org/partiql/examples/ParserExample.kt
examples/src/kotlin/org/partiql/examples/PreventJoinVistor.kt
lang/jmh/org/partiql/jmh/PartiQLBenchmark.kt
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/ast/AstDeserialization.kt
lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/StatementRedactor.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/syntax/Parser.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/ast/passes/StatementRedactorTest.kt
lang/test/org/partiql/lang/eval/visitors/AggregateSupportVisitorTransformTests.kt
lang/test/org/partiql/lang/eval/visitors/StaticTypeVisitorTransformTests.kt
lang/test/org/partiql/lang/eval/visitors/VisitorTransformTestBase.kt
lang/test/org/partiql/lang/syntax/SqlParserPrecedenceTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

*This PR aims to deprecate `ExprNode` in `Parser`.*
*Subtasks:*
&nbsp; PR: https://github.com/partiql/partiql-lang-kotlin/pull/460 
&nbsp; PR: https://github.com/partiql/partiql-lang-kotlin/pull/469 
&nbsp; PR: https://github.com/partiql/partiql-lang-kotlin/pull/462
&nbsp; PR: https://github.com/partiql/partiql-lang-kotlin/pull/471
&nbsp; PR: https://github.com/partiql/partiql-lang-kotlin/pull/470

Deprecate `ExprNode` in `Parser`

---

.gitignore
cli/build.gradle
cli/src/org/partiql/cli/Cli.kt
cli/src/org/partiql/cli/Repl.kt
cli/src/org/partiql/cli/Runnable.kt
cli/src/org/partiql/cli/functions/BaseFunction.kt
cli/src/org/partiql/cli/functions/ReadFile.kt
cli/src/org/partiql/cli/functions/WriteFile.kt
cli/src/org/partiql/cli/main.kt
cli/src/org/partiql/cli/stopwatch.kt
cli/src/org/partiql/cli/streams.kt
cli/test/org/partiql/cli/CliTest.kt
cli/test/org/partiql/cli/ReplTest.kt
cli/test/org/partiql/cli/functions/ReadFileTest.kt
cli/test/org/partiql/cli/functions/WriteFileTest.kt

*Issue #, if available:* 481
*Description of changes:* Included the following changes:
1. Adds macOs coverage in cli's .gitignore.
2. Removes the redundant lines in build.gradle.
3. To increase the code readability, replaces the wildcard imports with explicit imports in cli package.

[cli] remove wildcard imports

---

lang/src/org/partiql/lang/ast/AstSerialization.kt
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/ast/passes/AstRewriterBase.kt
lang/src/org/partiql/lang/ast/passes/AstWalker.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt

Removes sealed class DateTimeType as it was not needed.

---

docs/user/BuiltInFunctions.md
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/org/partiql/lang/eval/builtins/DateAddExprFunction.kt
lang/src/org/partiql/lang/eval/builtins/DateDiffExprFunction.kt
lang/src/org/partiql/lang/eval/builtins/ExtractExprFunction.kt
lang/src/org/partiql/lang/syntax/LexerConstants.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/src/org/partiql/lang/syntax/TokenType.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt
lang/test/org/partiql/lang/eval/builtins/DateAddExprFunctionTest.kt
lang/test/org/partiql/lang/eval/builtins/DateDiffExprFunctionTest.kt
lang/test/org/partiql/lang/eval/builtins/ExtractEvaluationTest.kt

As `DatePart` type includes Time components too, rename the type to
reflect the current value range.  In addition rename the related
functions.
GitHub Issue: https://github.com/partiql/partiql-lang-kotlin/issues/409
*Issue #, if available:* 409

Rename DatePart to DateTimePart

---

lang/test/org/partiql/lang/eval/EvaluatorTestBase.kt

Improve the CAST assertion assertEval with removing a redundant
assertion for permissive mode since we already run tests for this
mode as part of the overall process.
Issue #, if available: 519
Addressed the comment from the original PR which was closed because it was having changes from `remove-unused-imports` change:
https://github.com/partiql/partiql-lang-kotlin/pull/520

CAST: Improve the CAST assertion assertEval

---

lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerNAryIntOverflowTests.kt

The major change is to replace function `compileExprNode` with `compileAstStatement` and `compileAstExpr`. Each `ExprNode` type is replaced with the corresponding PIG AST node type. 
For NAry operators and typed operators, now each of them have one compiling function in `compileAstExpr`. (Removed `compileNAry` and `compileTyped` function)
One thing to note is that for now we still use `toPartiQlMetaContainer` function to convert IonElement metas (PIG AST) to ExprNode metas, and evaluate ExprNode metas. Will change it in the next commit. 
And I formatted the whole file. Sorry if it causes inconvenience to review.

Deprecate ExprNode in Evaluator

---

lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/passes/StatementRedactor.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserPrecedenceTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

*Motivation:*
As we are replacing `ExprNode` with PIG-generated AST, we need to resolve the inconsistency between them. 
With 2 or more arguments provided, `ExprNode` uses `NAry.add`(`NAry.Sub`) to model the addition operator, while PIG-generated AST uses `Plus`(`Minus`) to model it. However, with only one argument provided, the addition operator is modeled as `Pos`(`Neg`) in PIG AST, while in `ExprNode` it is still `NAry.add`(`NAry.Sub`). 
This PR aims to resolve this inconsistency. 
*Suggested reviewing order:*
1. SqlParser.kt and EvaluatingCompiler.kt 
2. ExprNodeToStatement.kt and StatementToExprNode.kt. 
3. Other files.

Added Pos and Neg operators.

---

lang/src/org/partiql/lang/syntax/SqlParser.kt

*Motivation:*
Currently, part of parser's code still uses `NAry`, which are `ExprNode` operators. We need to remove them as well.

Removed NAry operator in SqlParser.kt

---

lang/src/org/partiql/lang/ast/StaticTypeMeta.kt
lang/src/org/partiql/lang/ast/meta.kt
lang/src/org/partiql/lang/domains/util.kt
lang/src/org/partiql/lang/eval/AnyOfCastTable.kt
lang/src/org/partiql/lang/eval/ErrorSignaler.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/Exceptions.kt
lang/src/org/partiql/lang/eval/Thunk.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/eval/ErrorSignalerTests.kt
lang/test/org/partiql/lang/eval/ThunkFactoryTests.kt
lang/test/org/partiql/lang/eval/visitors/StaticTypeVisitorTransformTests.kt
lang/test/org/partiql/lang/eval/visitors/SubstitutionVisitorTransformTest.kt

*Motivation:*
The meta container PIG AST uses is `com.amazon.ionelement.api.MetaContainer`, while `ExprNode` uses `org.partiql.lang.ast.MetaContainer`. As we are deprecating `ExprNode`, we need to replace meta container as well. 
Note that the meta inside meta container is still the same. 
1. Added `metaContainerOf(vararg Meta)` in util.kt file. 
2. Replaced `org.partiql.lang.ast.MetaContainer` with `com.amazon.ionelement.api.MetaContainer` in EvaluatingCompiler.kt, Thunk.kt and related files.

Deprecate ExprNode metas

---

lang/build.gradle
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/src/org/partiql/lang/types/Plugin.kt
lang/src/org/partiql/lang/types/RSPlugin.kt
lang/src/org/partiql/lang/types/Type.kt
lang/src/org/partiql/lang/types/TypeAndFunctionManager.kt
lang/src/org/partiql/lang/types/TypeSignature.kt

* Introduces the following key interfaces as part of the design:
1. `Plugin`: Plugin to register types and functions supported on it.
2. `Type`: PartiQL's type which would potentially replace the current `StaticType`. 
3. `SymbolTableEntry`: A function signature and its implementation.
* `TypeAndFunctionManager`: A singleton instance that manages and resolves all the types and functions globally. 
* Note that this isn't a working piece of code but a design proposal for an open type system architecture. The design is expected to evolve and get better as we see fit.

Design for an open type system architecture inspired by PrestoDB.

---

cli/src/org/partiql/cli/Repl.kt
cli/src/org/partiql/cli/main.kt
cli/test/org/partiql/cli/CliTest.kt
docs/user/CLI.md

Implements #543.
Adds [PERMISSIVE](https://github.com/partiql/partiql-lang-kotlin/blob/3febaeec46a0b703781494699c445f2034e9c6c4/lang/src/org/partiql/lang/eval/CompileOptions.kt#L48-L76) typing mode evaluation option to CLI/REPL. Also prints the typing mode when running the REPL:
```
Welcome to the PartiQL REPL!
Typing mode: PERMISSIVE
Using version: 0.5.1-SNAPSHOT-a27123d
PartiQL>
```

[cli] Add permissive mode evaluation option to CLI/REPL

---

build.gradle

Bump Kotlin version to 1.4.32 from 1.4.0

---

lang/build.gradle

Previous Maven publishing would include the Ion team's name and email as the developers (e.g. [v0.4.0 release on Maven](https://search.maven.org/artifact/org.partiql/partiql-lang-kotlin/0.4.0/jar)). Updates to use the PartiQL team's info.

Update maven publishing name and email

---

gradle.properties
lang/build.gradle

I wasn't able to publish to maven due to some incompatibilities between the gradle version and the older version of `dokka` we were using. Sample errors when trying to gradle publish:
```
> Task :lang:dokka FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Some problems were found with the configuration of task ':lang:dokka' (type 'DokkaTask').
- In plugin 'org.jetbrains.dokka' type 'org.jetbrains.dokka.gradle.DokkaTask' property 'dokkaRuntime' is missing an input or output annotation.
Reason: A property without annotation isn't considered during up-to-date checking.
Possible solutions:
1. Add an input or output annotation.
2. Mark it as @Internal.
Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#missing_annotation for more details about this …
```

Upgrade dokka to 1.6.10, set org.gradle.jvmargs

---

lang/test/org/partiql/lang/eval/evaluatortestframework/AstEvaluatorTestAdapter.kt

Glad I caught this right away, could have been very confusing.  This makes me realize that my next PR should be some additional for the new evaluator test framework.

Parse expectedResult instead of query fixing a bug in the evaluator test framework

---

build.gradle

Implements #580.  This surfaces formatting problems identified by `ktlintCheck` earlier in the build, so long parts of the build like the unit tests don't need to be re-executed after applying formatting fixes.  
I also considered doing this before compilation, but `ktlinCheck`'s error messages are not at all helpful when it fails to parse some file... so it is better to compile, run ktlint, then run the tests...

Run ktlintCheck before tests

---

lang/test/org/partiql/lang/eval/EvaluatingCompilerNAryIntOverflowTests.kt
lang/test/org/partiql/lang/eval/EvaluatorStaticTypeTests.kt
lang/test/org/partiql/lang/eval/EvaluatorTestBase.kt
lang/test/org/partiql/lang/eval/EvaluatorTests.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/AbstractPipeline.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/Assertions.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/CompilerPipelineFactory.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/EvaluatorErrorTestCase.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/EvaluatorTestCase.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/EvaluatorTestDefinition.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/EvaluatorTestTarget.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/PipelineEvaluatorTestAdapter.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/PipelineEvaluatorTestAdapterTests.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/PipelineFactory.kt
lang/test/org/partiql/lang/util/testdsl/IonResultTestCase.kt

Since #582 is too big to review, it's being split up into a few smaller PRs.  This is the first.  Note that this PR will be merged to the `physical-plan-staging` branch, which will later be merged to `main`.
The test framework introduced in #573 and #579 includes `AstEvaluatorTestAdapter` which is tightly coupled to `CompilerPipeline` and therefore `EvaluatingCompiler` (the AST evaluator).  `AstEvaluatorTestAdapter` also contains all of the logic needed for running an individual test.  This PR moves all of that logic to `PipelineEvaluatorTestAdapter` and introduces an abstraction around pipelines to allow the logic to be used with other pipelines such as `PlannerPipeline` (which is being introduced in #592).
Additionally, the test framework currently lacks a mechanism to exclude one of …

Additional pipeline abstraction for test framework

---

lang/src/org/partiql/lang/planner/MetadataResolver.kt
lang/src/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/test/org/partiql/lang/planner/Util.kt
lang/test/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransformTests.kt

#588 introduces `UniqueIdResolver`.  While that name does accurately reflect what it currently does, in the future it will be expanded to cover much more than unique Ids.  Therefore, I have decided that `MetadataResolver` is a much better name.
I would like to merge this to `physical-plan-staging` before #590 and #592 are merged so as to reduce PR churn.  Thanks.

Rename `UniqueIdResolver` to `MetadataResolver`

---

README.md
cli/src/org/partiql/cli/functions/WriteFile.kt
cli/test/org/partiql/cli/CliTestUtility.kt
cli/test/org/partiql/cli/functions/WriteFileTest.kt

Related to Issue #606
- Fixes the `write_file()` function
- The old function required the input to be a string, but it must be a generic type.
- For example:
- a SELECT statement returns a bag
- a SELECT .. ORDER BY statement returns a list
- Updates the README as well

Fix write file

---

cli/src/org/partiql/cli/Cli.kt
cli/src/org/partiql/cli/functions/ReadFile.kt
cli/src/org/partiql/cli/functions/WriteFile.kt
cli/src/org/partiql/cli/main.kt
cli/test/org/partiql/cli/CliTest.kt
cli/test/org/partiql/cli/CliTestUtility.kt
cli/test/org/partiql/cli/functions/ReadFileTest.kt
cli/test/org/partiql/cli/functions/WriteFileTest.kt
docs/README.md
docs/user/CLI.md
docs/user/GettingStarted.md

- Adds the `--input-format` flag to the CLI
- Adds the ability to handle PartiQL data format for input (before was only Ion)
- Modifies the `--input` flag for CLI to not loop through the sequence of Ion values. Expect a single Ion value. (For the Ion input format)
- Modifies the `--output-format` option ION_TEXT to output the real value of the results (not loop through the bag)
- Updates the `read_file` function to read in a single Ion value
- Before, the `read_file` function used to loop through the values of an Ion file and place all values within a bag. This limits our ability to differentiate between different Ion values. See the next bullet-point for more information.
- Updates the `write_file` function to write the actual result.
- Before, the `write_file` function used to loop …

Cli add partiql input

---

lang/src/org/partiql/lang/ast/SourceLocationMeta.kt
lang/src/org/partiql/lang/errors/ProblemHandler.kt
lang/src/org/partiql/lang/eval/physical/PhysicalExprToThunkConverterImpl.kt
lang/src/org/partiql/lang/planner/PlannerPipeline.kt
lang/test/org/partiql/lang/planner/PlannerPipelineSmokeTests.kt

This PR will be merged to `main`.
This adds a new method to the `PlannerPipeline.Builder` class which allows customers to select optimal operator implementations and perform other custom rewrites on the physical algebra and also invokes these passes during plan-time.

Add API to PlannerPipeline to allow custom passes over physical plans.

---

examples/src/java/org/partiql/examples/CSVJavaExample.java
examples/src/java/org/partiql/examples/EvaluationJavaExample.java
examples/src/java/org/partiql/examples/ParserJavaExample.java
examples/src/java/org/partiql/examples/S3JavaExample.java
examples/src/kotlin/org/partiql/examples/EvaluationWithBindings.kt
examples/src/kotlin/org/partiql/examples/util/Example.kt
examples/src/kotlin/org/partiql/examples/util/Main.kt
examples/test/org/partiql/examples/EvaluationJavaExampleTest.kt
examples/test/org/partiql/examples/EvaluationWithBindingsTest.kt
examples/test/org/partiql/examples/ParserJavaExampleTest.kt

https://github.com/partiql/partiql-lang-kotlin/issues/19
Adds an equivalent java example for ParserExample and EvaluationWithBindings

Add Equivalent Java Examples (#19)

---

lang/src/org/partiql/lang/eval/ExprValueFactory.kt
lang/src/org/partiql/lang/util/IonValueExtensions.kt
lang/test/org/partiql/lang/eval/ExprValueFactoryTest.kt

Closes #628
- Add support for DATE/TIME in Ion input format
- Essentially, we don't have the ability to interpet $partiql_date and $partiql_time, but this PR fixes that.

Add support for DATE/TIME in Ion input format

---

cli/build.gradle
cli/src/org/partiql/cli/functions/QueryDDB.kt
cli/src/org/partiql/cli/functions/ReadFile.kt
cli/src/org/partiql/cli/functions/WriteFile.kt
cli/src/org/partiql/cli/main.kt
docs/user/CLI.md
extensions/build.gradle
extensions/src/org/partiql/extensions/cli/functions/BaseFunction.kt
extensions/src/org/partiql/extensions/cli/functions/QueryDDB.kt
extensions/test/org/partiql/extensions/cli/functions/QueryDDBTest.kt
settings.gradle

Related to #631
- Initializes the `extensions` module
- Sets the `extensions` as a dependency to `cli`
- Moves the `BaseFunction` class to the `extensions` module
- Creates a new `query_ddb` function, along with test cases
- Links the function to the CLI
- Updates documentation

Initializes extensions module and adds the query_ddb function to the CLI

---

build.gradle

Closes #457
- Since we do not have locale-specific tests, this PR adds a flag to test with en_US
- This allows developers of other locales to build/test without a need to change their laptop's settings
- See the issue above for manual testing.

Specifies tests to be of locale en_US

---

lang/build.gradle

Closes #618
- Sets an explicit dependency on generate PIG domains
- This enables execution optimizations and decreases the Total Build Time (excluding tests) by approx ~30% (~4s) after looking at preliminary results (6 runs) of `./gradlew --profile build` and cleaning prior to each run.
- Also removes the warning on each build

Adds ktlint task dependency to enable execution optimizations

---

README.md
build.gradle

*Issue #, if available:* #647 
Releases the new version `0.7.0`. Going from `0.6.0` to `0.7.0` because we have the following backward incompatible changes: https://paste.debian.net/1244888/

Release 0.7.0

---

lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/visitors/GroupByPathExpressionVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/syntax/LexerConstants.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserMatchTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

This adds draft parser/AST support for a subset of GPML as outlined by [Graph Pattern Matching in GQL and SQL/PGQ](https://arxiv.org/abs/2112.06217). The use within the grammar is based on the assumption of a new graph data type being added to the specification of data types within PartiQL, and should be considered experimental until the semantics of the graph data type are specified.
This adds support for parsing:
- basic and abbreviated node and edge patterns (section 4.1 of the GPML paper)
- concatenated path patterns  (section 4.2 of the GPML paper)
- graph patterns (i.e., comma separated path patterns)  (section 4.3 of the GPML paper)
- AST support for path quantifiers  (section 4.4 of the GPML paper)
- AST support for pre-filters (section 5.2 of the GPML paper)
TODO:
- path …

Add experimental draft support for GPML-style graph query

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Adds the new questions to the PR process for backward-incompatibility and introduction of new dependencies.
*Have you updated the `Unreleased` section of `CHANGELOG.md` with your changes? (y/n) If not, please explain why:* 
yes. 

Pr template update

---

lang/src/org/partiql/lang/prettyprint/ASTPrettyPrinter.kt

A new AST node was introduced before PR 650 got merged, so the compile after PR 650 got merged failed. This PR fixes the compile problem.

Fixed compile error introduced by PR 650

---

cli/src/org/partiql/shell/ShellHighlighter.kt

[*Issue #, if available:*](https://github.com/partiql/partiql-lang-kotlin/issues/651)
Fixed the `!add_to_global_env` highlighting. This will highlight the PartiQL value in the `!add_to_global_env` command using the lexer/parser. 
No, small bug fix
No
```
For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in 
errors for users that are using our public APIs or the entities that have …
```

Fixes add_to_global_env highlighting

---

lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlParserMatchTest.kt

Minor clean-up after #652 and #658 :
- Clean up some linter warnings
- Require parentheses around implicitly joined (via comma) graph patterns in the MATCH clause.
---

Minor GPML Match clause clean-up

---

CHANGELOG.md
lang/src/org/partiql/lang/eval/EvaluationSession.kt
lang/test/org/partiql/lang/eval/EvaluationSessionTest.kt

This provides a way for embedding PartiQL applications to pass session context such as current user information and transaction state to their custom `ExprFunction` and physical operator implementations.
yes, see the diff.
Changes are backward compatible.
*Does your PR introduce a new external dependency? (y/n), if yes, please explain the reason. In addition, please
also mention any other alternatives you've considered and the reason …

Add EvaluationSession.contextVariables

---

lang/src/org/partiql/lang/eval/builtins/MathFunctions.kt
lang/test/org/partiql/lang/eval/builtins/functions/MathFunctionsTest.kt

#661 CEIL And FLOOR Function behavior wrong when supplied with literal larger than 64 bits
Adding support for larger literal for ``CEIL`` and ``FLOOR`` functions using ``BigDecimal``. Adding the corresponding test cases. 
No.
```
For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in 
errors for users that are using our public APIs or the entities that have …
```

Fix ceil floor

---

CHANGELOG.md
lang/src/org/partiql/lang/planner/PlannerEventCallback.kt
lang/src/org/partiql/lang/planner/PlannerEventNames.kt
lang/src/org/partiql/lang/planner/PlannerPipeline.kt
lang/test/org/partiql/lang/planner/PlannerPipelineSmokeTests.kt

Planner event callbacks provide a facility that allows the query to be visualized at every stage in the PlannerPipeline and to generate performance metrics for the individual parts of the planner.
Yes
No.
*Does your PR introduce a new external dependency? (y/n), if yes, please explain the reason. In addition, please
No.
By submitting this pull …

Add planner event callbacks

---

lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/ast/ExprNodeToStatement.kt
lang/src/org/partiql/lang/ast/StatementToExprNode.kt
lang/src/org/partiql/lang/ast/ast.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/physical/PhysicalExprToThunkConverterImpl.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/prettyprint/ASTPrettyPrinter.kt
lang/src/org/partiql/lang/syntax/LexerConstants.kt
lang/src/org/partiql/lang/syntax/SqlLexer.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/test/org/partiql/lang/syntax/SqlLexerTest.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

Part 2 of — https://github.com/partiql/partiql-lang-kotlin/issues/184
These changes add the OUTER set operators defined in [RFC-0007 ](https://github.com/partiql/partiql-docs/blob/main/RFCs/0007-rfc-bag-operators.md) to the type universe, lexer, and parser.
*Have you updated the `Unreleased` section of `CHANGELOG.md` with your changes? (y/n), If not, please explain why:* No, N/A
also mention any other alternatives you've considered and the reason they've been discarded?:* N
```
For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in 
errors for users that are using …
```

Adds OUTER set operators to parser and type domain

---

lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/planner/PlanningProblemDetails.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/test/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransformTests.kt

#677 
The domain of values allowed in the `partiql_logical.dml.target` element was too broad because it allowed for any expression.
This commit changes this to `partiql_logical.dml.target` to be simply `identifier`, which is the only currently supported form of DML targets in the planner.
No, this PR only slightly changes stuff already in the change log.
"Technically", the only change is to …

Narrow domain of DML targets (#677)

---

lang/src/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt

When we build the the project, it gives us such warnings: 
```
./gradlew build                                                                                                                                                                                            SIGINT(2) ↵  3781  12:40:25  
> Task :lang:compileKotlin
w: /home/ANT.AMAZON.COM/dlurton/projects/dlurton/partiql-lang-kotlin/lang/src/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt: (324, 30): Parameter 'node' is never used
w: /home/ANT.AMAZON.COM/dlurton/projects/dlurton/partiql-lang-kotlin/lang/src/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt: (373, 76): Parameter 'level' is never used
w: /home/ANT.AMAZON.COM/dlurton/projects/dlurton/partiql-lang-kotlin/lang/src/org/partiql/lang/prettyp …
```

Suppress Build warning

---

CHANGELOG.md
lang/src/org/partiql/lang/util/NumberExtensions.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerNAryIntOverflowTests.kt

*Issue #, if available:* [#513](https://github.com/partiql/partiql-lang-kotlin/issues/513)
1. fix the bug `neg(LONG.min_value) = LONG.min_value`
2. uncomment the test case
https://github.com/partiql/partiql-lang-kotlin/blob/cba305370b8cf78772c77808056cecec7a898620/lang/test/org/partiql/lang/eval/EvaluatingCompilerNAryIntOverflowTests.kt#L222
3. fix some typos
Yes. 
```
For this purpose, we define backward-incompatible changes as changes …
```

Fix neg overflow

---

docs/dev/version-migration/cli-versions.md
docs/dev/version-migration/migration-guide.md
docs/dev/version-migration/v0.1-to-v0.2-migration.md
docs/dev/version-migration/v0.2-to-v0.3-migration.md
docs/dev/version-migration/v0.3-to-v0.4-migration.md
docs/dev/version-migration/v0.4-to-v0.5-migration.md
docs/dev/version-migration/v0.5-to-v0.6-migration.md
docs/dev/version-migration/v0.6-to-v0.7-migration.md

#668.
*Description of changes:* Adds migration guides relevant for PartiQL library users who would like to migrate to a newer major version. This PR adds a folder to `docs/dev` with the guides. TBD if this folder will remain or if the contents are more appropriate as a set of wiki pages: https://github.com/partiql/partiql-lang-kotlin/wiki.
Rendered markdown files can be viewed by going to "Files changed" -> clicking the three horizontal dots on the given file -> click "View file". Also viewable here:
- [cli-versions.md](https://github.com/partiql/partiql-lang-kotlin/blob/aabbc98dc3097d601b2e4d9bcb083d66cf9a576a/docs/dev/version-migration/cli-versions.md)
- [migration-guide.md](https://github.com/partiql/partiql-lang-kotlin/blob/aabbc98dc3097d601b2e4d9bcb083d66cf9a576a/docs/dev/version-migr …

Add `partiql-lang-kotlin` major version migration guides

---

lang/src/org/partiql/lang/planner/PlannerPipeline.kt

This is a miss in previous commits.
Just like the title says.  I just missed this from #681.
No, because what's already discussed for planner event callbacks is adequate.
No.
*Does your PR introduce a new external dependency? (y/n), if yes, please explain the reason. In addition, please
No. …

Make PlannerPipeline.Builder.plannerEventCallback public

---

lang/src/org/partiql/lang/eval/BagOp.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/org/partiql/lang/eval/physical/PhysicalExprToThunkConverterImpl.kt
lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
lang/test/org/partiql/lang/ast/SerializationRoundTripTests.kt
lang/test/org/partiql/lang/eval/EvaluatorTestSuite.kt
lang/test/org/partiql/lang/eval/EvaluatorTests.kt
lang/test/org/partiql/lang/util/testdsl/IonResultTestSuite.kt

https://github.com/partiql/partiql-lang-kotlin/issues/184
This PR implements OUTER bag operators. These operators are the multi-set operators we know and love from math. The full specification is defined in [RFC-0007 ](https://github.com/partiql/partiql-docs/blob/main/RFCs/0007-rfc-bag-operators.md)
*Have you updated the `Unreleased` section of `CHANGELOG.md` with your changes? (y/n), If not, please explain why:* N
I will update CHANGELOG once set operators are added. This is just the OUTER operators.
also mention any other alternatives you've considered and the reason they've been discarded?:* N
```
For this purpose, we …
```

Adds OUTER bag operators [RFC-0007]

---

lang/test/org/partiql/lang/syntax/SqlParserMatchTest.kt

Added a few tests to make sure that SELECT * parses with graph queries. 
*Have you updated the `Unreleased` section of `CHANGELOG.md` with your changes?*
No - this is a minor catch-up for the graph query work already described for the next release.
*Does your PR include any backward-incompatible changes?*
No
*Does your PR introduce a new external dependency?*
No

Tests for SELECT * with graph query.

---

lang/src/org/partiql/lang/ast/passes/inference/StaticTypeExtensions.kt
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
lang/src/org/partiql/lang/mappers/IonSchemaMapper.kt
lang/src/org/partiql/lang/mappers/StaticTypeMapper.kt
lang/src/org/partiql/lang/types/PartiqlPhysicalTypeExtensions.kt
lang/src/org/partiql/lang/types/StaticType.kt
lang/test/org/partiql/lang/CustomTypeTestFixtures.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerCustomAnyOfTypeOperationTests.kt
lang/test/org/partiql/lang/eval/ThunkFactoryTests.kt
lang/test/org/partiql/lang/eval/builtins/InvalidArgTypeChecker.kt
lang/test/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransformTest.kt
lang/test/org/partiql/lang/mappers/E2EMapperTests.kt

Similar to https://github.com/partiql/partiql-lang-kotlin/pull/693, `Varchar`, `Char` & `String` types currently in partiql are modeled using the same kotlin data class with with different constraints of `StringLengthConstraint`. We need to refactor them so they are modeled using different kotlin data classes with similar properties, just as how other common types are modeled, before we start the work of rewriting all the static scalar types by exposed interfaces.

Refactored StaticType.STRING

---

lang/src/org/partiql/lang/ast/passes/inference/StaticTypeExtensions.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/org/partiql/lang/eval/physical/PhysicalExprToThunkConverterImpl.kt
lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
lang/src/org/partiql/lang/mappers/IonSchemaMapper.kt
lang/src/org/partiql/lang/mappers/StaticTypeMapper.kt
lang/src/org/partiql/lang/types/PartiqlPhysicalTypeExtensions.kt
lang/src/org/partiql/lang/types/StaticType.kt
lang/test/org/partiql/lang/CustomTypeTestFixtures.kt
lang/test/org/partiql/lang/ast/passes/inference/StaticTypeCastTests.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerNAryIntOverflowTests.kt
lang/test/org/partiql/lang/eval/builtins/InvalidArgTypeChecker.kt
lang/test/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransformTest.kt
lang/test/org/partiql/lang/mappers/E2EMapperTests.kt

*Motivation:*
Currently, `IntType` in `StaticType.kt` has a specific property `rangeConstraint: IntRangeConstraint`. This will cause unnecessary extra work when we try to refactor existing PartiQL scalar types using exposed interface. Because exposed interfaces should be used for defining generic properties or behaviors of a type, and no type should have a specific property when we are pulling all the scalar types out of `org.pariql.lang` package. Thus, in this PR, we removed `rangeConstraint` in `IntType` and refactored the way to model integer types. 
1. Now `INT2`, `INT4`, `INT8` & `INT` are modeled as unique kotlin data classes, instead of one data class with different constraints. 
2. Other changes are just to make compiling & test pass. 
*Note that this PR …

Re-modeling Integer Types in `StaticType`

---

.github/workflows/build.yml
build.gradle
lang/build.gradle
pts/build.gradle
testscript/build.gradle

Fixes #375
* Upgrades Kotlin Gradle plugin to 1.5.31.
* Upgrades JaCoCo to 0.8.8.
* Adds language/lib target to Kotlin 1.4 to ensure compatibility.
* Adds Java 8 compatibility globally to align with Kotlin.
* Adds CI support for JDK 17 and removes non-LTS releases that are past EOL.
The CI change showing build failure with JDK 17 before this change can be seen here[^1].
*Have you updated the `Unreleased` section of `CHANGELOG.md` with your changes? (y/n), If not, please explain why:* No, this change is purely build/CI.
also mention any other alternatives you've considered and the reason they've been discarded?:* No.
*Does your PR introduce a new …

Fixes Build on JDK17

---

CHANGELOG.md
lang/src/org/partiql/lang/syntax/SqlLexer.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt

- Closes #742
- Marks SqlLexer and SqlParser as DEPRECATED
- Updated CHANGELOG
- No backward incompatible changes. Marking as deprecated -- not removing.
- No new external dependencies

Deprecates SqlLexer and SqlParser

---

CHANGELOG.md
lang/src/org/partiql/lang/eval/BindingsExtensions.kt

Found a word that is being phased out by PartiQL. Deprecated the function and added a new function to take its place. We actually do not use the code, but as it is a public API, I opted to add the deprecation and a functional equivalent.
- No incompatible changes -- marking as deprecated
- Updated the unreleased section
- No external dependencies added

Renames method to conform to PartiQL's standards

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

- Adds issue templates
- No external dependencies, no CHANGELOG modification.
- See the [official GH documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) on issue templates.

Adds issue templates

---

cli/src/org/partiql/cli/main.kt
lang/src/org/partiql/lang/compiler/PartiQLCompiler.kt
lang/src/org/partiql/lang/compiler/PartiQLCompilerBuilder.kt
lang/src/org/partiql/lang/compiler/PartiQLCompilerDefault.kt
lang/src/org/partiql/lang/compiler/PartiQLCompilerImpl.kt
lang/src/org/partiql/lang/compiler/PartiQLCompilerPipeline.kt
lang/src/org/partiql/lang/errors/PartiQLException.kt
lang/src/org/partiql/lang/eval/PartiQLResult.kt
lang/src/org/partiql/lang/eval/PartiQLStatement.kt
lang/src/org/partiql/lang/planner/GlobalVariableResolver.kt
lang/src/org/partiql/lang/planner/PartiQLPlanner.kt
lang/src/org/partiql/lang/planner/PartiQLPlannerBuilder.kt
lang/src/org/partiql/lang/planner/PartiQLPlannerDefault.kt
lang/src/org/partiql/lang/planner/PartiQLPlannerImpl.kt
lang/src/org/partiql/lang/planner/PartiQLPlannerPass.kt
lang/src/org/partiql/lang/planner/PlannerPipeline.kt
lang/src/org/partiql/lang/planner/QueryPlan.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/src/org/partiql/lang/syntax/PartiQLParserBuilder.kt
lang/test/org/partiql/lang/eval/EvaluatorTestBase.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt
lang/test/org/partiql/lang/syntax/SqlParserTestBase.kt

This introduces **PartiQLCompilerPipeline** to replace the legacy **CompilerPipeline**. There are two major differences which are important to our team's goals.
1. Parsing, planning, and compiling responsibilities are split to enable plug-ability for library consumers. This is also a prerequisite for future refactor goals.
2. The legacy compiler methods return **ExprValue** which is representative of an Ion value. The **PartiQLCompilerPipeline** returns a new class called **Statement** which represents either a Query, DML command, or stored procedure. This verbiage is consistent with the PartiQL type domains.
As it stands, this is a replacement for the experimental PlannerPipeline, but this commit does not modify or remove PlannerPipeline. This commit shares most of the same code as …

Split compilation pipeline reponsibilities

---

CHANGELOG.md
lang/src/org/partiql/lang/errors/ErrorCode.kt
lang/src/org/partiql/lang/eval/builtins/TrimExprFunction.kt
lang/src/org/partiql/lang/visitors/PartiQLVisitor.kt
lang/test/org/partiql/lang/errors/ParserErrorsTest.kt
lang/test/org/partiql/lang/eval/builtins/functions/TrimEvaluationTest.kt

Closes Issue #744 
1. Added support for trim to accept case insensitive [ BOTH | LEADING | TRAILING]
2. Fixed error message in case of Trim Spec mismatch
3. Added an Parser Error to specifically for trim spec mismatch
4. Added test case for upper case trim spec
5. Added test cases for Trim Spec Mismatch
Future to do: 
Decide whether or not Trim Spec mismatch shall be a parser error or an evaluator error, and clean up the code accordingly. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

change trim spec to be case insensitive 

---

CHANGELOG.md
docs/documentation/Functions.md
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/test/org/partiql/lang/eval/CastTestBase.kt

#749 
cast(`+inf` AS INT) now produces error ` Can't convert Infinity or NaN to INT.` Before it produces `Internal error, Infinite or NaN`
Also added test cases to demonstrate how `cast([`+inf` | `-inf` | `nan`] as <type>)` behaves under different types. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

cast function inf/nan behavior change

---

CHANGELOG.md
examples/src/java/org/partiql/examples/ParserJavaExample.java
examples/src/kotlin/org/partiql/examples/ParserErrorExample.kt
examples/src/kotlin/org/partiql/examples/ParserExample.kt
examples/src/kotlin/org/partiql/examples/PreventJoinVistor.kt
examples/test/org/partiql/examples/ParserErrorExampleTest.kt
lang/jmh/org/partiql/jmh/MultipleLikeBenchmark.kt
lang/jmh/org/partiql/jmh/PartiQLBenchmark.kt
lang/src/org/partiql/lang/CompilerPipeline.kt
lang/src/org/partiql/lang/ast/passes/StatementRedactor.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/planner/PlannerPipeline.kt
lang/src/org/partiql/lang/prettyprint/ASTPrettyPrinter.kt
lang/src/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
lang/src/org/partiql/lang/visitors/PartiQLVisitor.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerExceptionsTest.kt
lang/test/org/partiql/lang/eval/JoinWithOnConditionTest.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
partiql-grammar/src/main/antlr/org/partiql/grammar/PartiQL.g4

- Closes #760 
- Makes the PartiQLParser the default Parser for the Compiler Pipeline, etc
- Makes changes to pass all tests, including:
- Making unary minus/plus act directly on numeric literals
- Adds metas to several AST nodes
- Updates examples directory
- No backwards incompatible changes
- Has not yet updated CHANGELOG
- No external dependencies added
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Makes the PartiQLParser the default Parser

---

docs/documentation/Functions.md

N/A 
Github wiki does not support anchor tags parsing. This is simply for a format change. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

wiki format change

---

.github/workflows/build.yml
README.md
cli/README.md
docs/general/Home.md
partiql-grammar/README.md
settings.gradle

- None
- Modifies build GH actions to not build when updating documentation.
- See the commit history to see the types of changes and the build types.
- Updated Unreleased Section in CHANGELOG: NO
- Small change.

Optimize GH Actions Build by removing documentation builds

---

lang/test/org/partiql/lang/eval/EvaluatingCompilerDateTimeTests.kt

- Closes #778 
- There was 4-5 tests performing 100,000 iterations each of an operation
- This caused an annoying test experience -- as the build would stop at around 77,000 tests, and it wouldn't give you an update for several minutes
- I took the input data and wrapped it to pass it to a ParameterizedTest so that JUnit could parallelize the test runs
- This way, the tests never freeze (YAY !), we can always see our progress, and I saw preliminary results of significantly faster tests.
Ran tests over two days (seems like Day 1 my computer was more friendly). Removed the build cache before each run and ran `./gradlew clean build` -- below are the test times.
- Branch `main`
- 8m 46s (Day 1)
- 8m 59s (Day 1)
- 10m 6s (Day 2)
- 9m 19s (Day 2)
- **AVERAGE: 9m 17.5s**
- Branch …

Parallelizes subset of tests by splitting test into many

---

lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt

*This PR aims to refactor code style of operators handling in `StaticTypeInferenceVisitorTransform.kt` for better readability. There is no behavior change in this PR*
##Changes:
1. Now the code of operators handling are structurally classified into the following 4 categories:
- Unary operators: `NOT`, `POS` & `NEG`
- Logical NAry operators: `AND` & `OR`
- Common NAry operators: `PLUS`, `MINUS`, `TIMES`, `DIVIDE`, `MODULO`, `CONCAT`, `EQ`, `NE`, LT`, `LTE`, `GT` & `GTE`
- Other special NAry operators: `LIKE`, `BETWEEN` &` IN`
Each category has similar coding structure and calls similar helper methods. e.g. NAry Arithmetic operators & comparator operators now both call `computeReturnTypeForNAry`

Refactor stivt code

---

examples/src/kotlin/org/partiql/examples/MergeKeyValues.kt
examples/test/org/partiql/examples/MergeKeyValuesTests.kt

Adds an example for using a custom function for working with elements of lists and struct members.
- [Closes] Issue #785 
- Adds an example for using a custom function for working with elements
of lists and struct members. In this case it's a function for merging the values of common given keys in the input.
- No, adding just an example, not a feature.
- No
- No

Add an additional example for ExprFunction

---

CHANGELOG.md
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt

- [Closes] Issue #743, #739 
- Adds the logical plan support for `ON CONFLICT DO REPLACE EXCLUDED`; as part of defines a new `dml_operation` called `dml_replace` for replace operations; with `DO REPLACE EXCLUDED` the value associated with the `dml_replace` is the value that is already specified in the replace.
- Yes.
- No.
- No.

Add logical plan support for DO REPLACE EXCLUDED

---

CHANGELOG.md
lang/src/org/partiql/lang/eval/CompileOptions.kt

Deprecates `TypedOpParameter.LEGACY` to be replaced with `TypedOpParameter.HONOR_PARAMETERS`

Marked TypedOpBehavior.LEGACY as deprecated

---

CHANGELOG.md
lang/src/org/partiql/lang/eval/ExprValueType.kt
lang/test/org/partiql/lang/eval/CastTestBase.kt

In legacy parser, type names are considered as keywords and stored [here](https://github.com/partiql/partiql-lang-kotlin/blob/2e19331afc8e6b4bdfced0ec78dcdc81553e2e9d/lang/src/org/partiql/lang/syntax/LexerConstants.kt). The property [`ExprValueType.typeNames`](https://github.com/partiql/partiql-lang-kotlin/blob/2e19331afc8e6b4bdfced0ec78dcdc81553e2e9d/lang/src/org/partiql/lang/eval/ExprValueType.kt#L31) duplicates those type names and [this part of code](https://github.com/partiql/partiql-lang-kotlin/blob/2e19331afc8e6b4bdfced0ec78dcdc81553e2e9d/lang/src/org/partiql/lang/eval/ExprValueType.kt#L122-L139) ensures type names defined in lexer and `ExprValueType` are the same. 
As we are going to remove legacy parser, also, since we want to make type names (type aliases) user-defined in OTS, …

Removed type names from ExprValueType

---

lang/src/org/partiql/lang/planner/PartiQLPlannerDefault.kt

N/A
The problem collector was mistakenly re-used between multiple plan calls. This was not caught in the unit tests, but I noticed in the shell.
No
No
No

Remove state from planner

---

CHANGELOG.md
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/eval/physical/EvaluatorState.kt
lang/src/org/partiql/lang/eval/physical/PhysicalBexprToThunkConverter.kt
lang/src/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
lang/src/org/partiql/lang/eval/physical/SetVariableFunc.kt
lang/src/org/partiql/lang/eval/physical/operators/DefaultOperatorFactories.kt
lang/src/org/partiql/lang/eval/physical/operators/RelationalOperatorKind.kt
lang/src/org/partiql/lang/eval/physical/operators/SortOperatorFactory.kt
lang/src/org/partiql/lang/planner/PartiQLPlannerDefault.kt
lang/src/org/partiql/lang/planner/transforms/AstNormalize.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerOrderByTests.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/EvaluatorTestCase.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/test/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransformTests.kt
lang/test/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransformTests.kt

- Closes #781 
- Adds a `SORT` node to `logical`, `resolved`, and `physical` plans (domains)
- Adds appropriate transforms
- Adds an abstract class `SortOperatorFactory` implementing a `RelationalOperatorFactory`
- Adds a simple `InMemorySortFactory` that takes in a `RelationExpression` and outputs a sorted `RelationExpression`. It is the default `SORT` implementation.
- It works by evaluating the source relation expression, copying the state's registers (for the purpose of sorting), evaluating the ORDER BY sort specs using the passed state's registers, and then modifying the state's registers to output the correct state order.
- Removes the check for the existence of `ORDER BY` -- it used to throw intentional "unimplemented" exceptions
- Adds tests to the three types of transforms, and …

Adds sort operator to planner

---

CHANGELOG.md
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/test/org/partiql/lang/eval/EvaluatorStaticTypeTests.kt
lang/test/org/partiql/lang/eval/EvaluatorTestSuite.kt
lang/test/org/partiql/lang/eval/EvaluatorTests.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/test/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransformTests.kt

#800 
Adds PIVOT projection expression to the logical domain
Yes. PIVOT support in the planner is a new, unreleased change so it has been included in the CHANGELOG.md
No
No

Adds PIVOT projection to PartiQLPlanner

---

CHANGELOG.md
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/physical/PhysicalBexprToThunkConverter.kt
lang/src/org/partiql/lang/syntax/SqlParser.kt
lang/src/org/partiql/lang/visitors/PartiQLVisitor.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt

- Closes #832 
- Moves defaulting of `ordering_spec` and `nulls_spec` within the `sort_spec` to evaluation time, rather than parse time.

Default sort & null spec in evaluator, not parser

---

README.md

Updates the root README's build instructions following the addition of the git submodule, `partiql-tests`. Without pulling in the `partiql-tests` git submodule, developers may have ran into this build failure from the `test/partiql-tests-runner` gradle module:
```
TestRunner > validatePartiQLEvalEquivTestData(TestCase) > org.partiql.runner.TestRunner.initializationError FAILED
org.junit.platform.commons.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
```
- Updated Unreleased Section in CHANGELOG: No, PR just updates README with additional instructions.
By submitting this pull request, I confirm that my contribution is made under the …

Update README following addition of partiql-tests git submodule

---

CHANGELOG.md
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/compiler/PartiQLCompilerDefault.kt
lang/src/org/partiql/lang/eval/PartiQLResult.kt
lang/src/org/partiql/lang/planner/QueryPlan.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
lang/src/org/partiql/lang/visitors/PartiQLVisitor.kt
lang/test/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/test/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransformTests.kt
lang/test/org/partiql/lang/syntax/SqlParserTest.kt
partiql-grammar/src/main/antlr/org/partiql/grammar/PartiQL.g4

- Closes #704 
- This PR includes the following:
- Support for `INSERT INTO tbl ... ON CONFLICT DO REPLACE EXCLUDED` and `REPLACE INTO tbl ...` evaluation.
- Support for `INSERT INTO tbl ... ON CONFLICT DO UPDATE EXCLUDED` logical planning.
- The reason that evaluation is excluded is b/c the logic is for update evaluation requires implementing merge with existing values which makes it more completed; since it's not part of the related ask (attached issue) we defer the implementation for now.
- Adds parsing support for `AS alias` for `UPSERT INTO` and `REPLACE INTO` statements.
Yes.
No.
No. …

Final changes for REPLACE/UPSERT/INSERT EXCLUDED

---

lang/src/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerGroupByTest.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerOrderByTests.kt

- [Closes/Related To] Issue https://github.com/partiql/partiql-lang-kotlin/issues/833
In this PR, a temporary resolution to fix iterating on the planner result was added. 
The way we achieve this is by "hard" reset the state before yielding `exprValue` in the bindingsToValues function. 
This patch fixes incorrect result when using subqueries (in testing and in pipeline breaking operators). 
As an evident, the failing tests for `GROUP BY` and `ORDER BY` are now passing. 
A long term solution can be having the operator to yield bindings instead of modifying a global mutable array list(register). 
- No, Bug fix in the experimental Planner. 
- No. 
- < For this purpose, we define …

fix subquery execution

---

lib/partiql-isl/build.gradle

Version bump with no changes simplifies 0.8.0 release. Starting at 1.0.0 we should consider having vended libs share the library version as this is avoid these bumps and is common elsewhere

Bumps partiql-isl-kotlin to 0.2.2

---

lang/src/org/partiql/lang/SqlException.kt
lang/src/org/partiql/lang/ast/passes/SemanticException.kt
lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/Exceptions.kt
lang/src/org/partiql/lang/eval/builtins/MakeDateExprFunction.kt
lang/src/org/partiql/lang/eval/builtins/MakeTimeExprFunction.kt
lang/src/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
lang/src/org/partiql/lang/eval/physical/operators/SortOperatorFactoryDefault.kt
lang/test/org/partiql/lang/eval/ExceptionWrappingTest.kt

- Closes Issue #616
This is a simple PR: There was an in-code TODO at SqlException, pointing at Issue #616.
The suggestion was to change the field to non-nullable, switching from null to an empty PropertyValueMap as the declared default.  It turned out that many use sites have already provided non-null actuals, so even a default is not necessary in a few places.  The only subclass that had use sites with null actuals (coming through the default) was EvaluationException, so its default did get changed rather than removed. 
- This is an internal change.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Makes SqlException.errorContext non-nullable, resolving Issue #616.

---

CHANGELOG.md
lang/src/org/partiql/lang/ast/passes/StatementRedactor.kt
lang/test/org/partiql/lang/ast/passes/StatementRedactorTest.kt

- Closes Issue #849 
This commit enables statement redaction for `INSERT`, `REPLACE`, and `UPSERT`.
Yes.
No.
No.

Add redaction for INSERT/UPSERT/REPLACE INTO << >>

---

lib/partiql-isl/build.gradle

- NA
- Updates to 2.2.3-SNAPSHOT

Update ISL to SNAPSHOT

---

CHANGELOG.md
cli/src/org/partiql/shell/Shell.kt
cli/src/org/partiql/shell/ShellHighlighter.kt
lang/antlr/PartiQLTokens.g4
lang/src/org/partiql/lang/syntax/PartiQLParser.kt
lang/src/org/partiql/lang/syntax/PartiQLVisitor.kt

- Closes #748
- Updates the Shell Highlighter to use ANTLR generated lexer/parser instead of SqlParser
- There are several new additions to the PartiQLParser (DML and more) that are not able to be highlighted by the existing Shell Highlighter
- Changes made:
- Created an UNRECOGNIZED token (which grabs anything not matching)
- Pushed comments and whitespace to hidden channel (so we can reproduce in CLI)
- Since we add to hidden channel, I needed to update the way we get parameter indexes because it uses a method that only tacks ON channel tokens.
- Also found a bug with `visitLiteralIon` in `PartiQLVisitor` -- if Ion can't parse the value, it throws an unhandled exception, and we need to catch it (addressed in this PR as well)
- Any …

Updates the CLI Shell Highlighter to use ANTLR-generated lexer/parser

---

CHANGELOG.md
lang/resources/org/partiql/type-domains/partiql.ion
lang/src/org/partiql/lang/eval/builtins/BuiltinFunctions.kt
lang/src/org/partiql/lang/eval/builtins/CollectionAggregationFunction.kt
lang/src/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
lang/src/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/org/partiql/lang/planner/validators/PartiqlLogicalValidator.kt
lang/test/org/partiql/lang/eval/EvaluatingCompilerCollectionAggregationsTest.kt
lang/test/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt

- Closes #837 
- Adds collection aggregation functions (COLL_SUM, COLL_AVG, COLL_MIN, etc)
- Creates a sealed class `CollectionAggregationFunction`, where each implementation just leverages the aggregation logic used by the aggregate operator. See Accumulator. We also add these to the built-in functions.
- Modifies the AstToLogical:
- In the normal flow, all CallAggs in a SFW query will be sent to the aggregate operator and replaced with identifiers
- After this happens, we just need to replace any remaining aggregation functions with the equivalent collection aggregation function.
- Similarly, we also need to replace any CallAggs that are outside of the SFW query. So, this PR also does that.
- Any backward-incompatible changes? **YES** …

Adds collection aggregation functions

---

examples/src/kotlin/org/partiql/examples/CustomProceduresExample.kt
examples/test/org/partiql/examples/CustomProceduresExampleTest.kt

- Remove the dependency on `ionValue` property in the custom procedure example

Modified custom procedure example to remove the use of `ionValue`

---

lang/build.gradle
lang/src/org/partiql/lang/syntax/PartiQLParser.kt
lang/test/org/partiql/lang/syntax/PartiQLParserSpyTest.kt

- None
- Adds SLL prediction mode to parser to reduce latency
- Ran benchmarks using the PartiQLParser (suffixed with New), the SqlParser (suffixed with Old), and the modified PartiQLParser (suffixed with Experimental). Here are the results:
```
Benchmark                                     Mode  Cnt     Score     Error  Units
ParserBenchmark.nestedSelectExperimental      avgt   20   124.236 ±   5.000  us/op
ParserBenchmark.nestedSelectNew               avgt   20  2525.692 ± 116.653  us/op
ParserBenchmark.nestedSelectOld               avgt   20   145.874 ±   9.847  us/op
ParserBenchmark.simpleSelectExperimental      avgt   20    10.384 ±   0.273  us/op
ParserBenchmark.simpleSelectNew               avgt   20    16.875 ±   1.262  us/op
ParserBenchmark.simpleSelectOld               avgt   20 …
```

Adds SLL prediction mode to parser to reduce latency

---

CHANGELOG.md
lang/antlr/PartiQL.g4
lang/src/org/partiql/lang/syntax/PartiQLVisitor.kt

- None
- Removes use of passed context to improve latency of parse
- While evaluating the effectiveness of SLL vs LL parsing, I noticed that almost all queries were seeing dramatically decreased latency. By examining the grammar, `PartiQL.g4`, I noted and tested several rules that would break the rules of SLL:
- there are no empty right hand sides
- each alternative of a non-terminal symbol begins with a unique terminal symbol
- the grammar is not left recursive
- Beyond this, I was looking for oddly formulated rule definitions.
- There was a single rule that takes advantage of ANTLR's context-passing feature. I tested the feature using the following query: `SELECT a FROM a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p`. See the results below:
| Name | Mode | Count | Score | +/- Error | …

Removes use of passed context to improve latency of parse

---

lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
lang/test/org/partiql/lang/eval/EvaluatorStaticTypeTests.kt

- [Closes] Issue #702 
- With this quick fix, we are able to run distinct on the same `sequence<ExprValue>` multiple times.
- A particular use case is running the query with type inferencer enabled. 
- 7 failed type inferencer test cases are passing now. 
- No, minor bug fix. 
- No.
- No.

fix distinct issue

---

CHANGELOG.md
lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLParser.kt
lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserSpyTest.kt
lang/src/test/kotlin/org/partiql/lang/thread/ThreadInterruptedTests.kt

- Related To #710, #895
- Resolves #747 
- Removes double-pass to increase parsing performance
- Adds interruption handling to both parse methods (LL and SLL)
- We discussed the importance of allowing our customers to fail quickly -- but that's out of the scope of a patch release.
- With these changes, we want to make our parser faster -- while also ensuring they can always interrupt the parse at any point if they desire. We also include interruption handling for creating the token stream.
- Adds more exception handling
-  With this, we'd like to make sure that our public APIs are always throwing the correct exceptions, so for `parseAstStatement`, we catch all to make sure our public API is never broken.
- With local benchmarking, the recent changes in the PartiQLParser have reduced the …

Removes double-pass to increase parsing performance, and adds interruption/exception handling

---

CHANGELOG.md
README.md
build.gradle
cli/src/org/partiql/shell/CompleterDefault.kt
cli/src/org/partiql/shell/Shell.kt
lang/antlr/PartiQL.g4
lang/build.gradle
lang/src/org/partiql/lang/syntax/PartiQLParser.kt
lang/src/org/partiql/lang/syntax/PartiQLVisitor.kt
lang/test/org/partiql/lang/syntax/PartiQLParserSpyTest.kt
lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt

- Prepares a patch release with parser improvements off of v0.8.1

Prepare v0.8.2 release

---

CHANGELOG.md
README.md
build.gradle
version-upgrade/v0.7-to-v0.8-upgrade/upgraded-examples/build.gradle

- Updates the README, CHANGELOG, gradle builds following v0.8.2 release
- Updated Unreleased Section in CHANGELOG: No. No code changes in released projects.

Update README, CHANGELOG, gradle builds following v0.8.2 release

---

CHANGELOG.md
lang/src/test/kotlin/org/partiql/lang/thread/ThreadInterruptedTests.kt

- Closes #911 
- The interrupted tests hide whatever exceptions may be thrown, and in the case of the internal method of ParseUsingSLL, it was occasionally throwing a StackOverflowError. This is handled by the public API, but the internal method doesn't handle it.
- Modified the thread interrupted test to throw the unhandled child thread exceptions to increase visibility if the tests ever fail.
- I also decreased the time for the parsing tests to 2 ms instead of 5 ms. Tested it several times locally -- no issue.

Fixes ThreadInterruptedTests and shows child-thrown exceptions

---

CHANGELOG.md
lang/src/main/kotlin/org/partiql/lang/ast/IsListParenthesizedMeta.kt
lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserMetaTests.kt

- Relevant to #925
- There is a customer use-case to differentiate between lists that are created using `[ , , , ]` and `( , , , )`.
- In our AST, we currently do not differentiate between the two.
- This adds a meta and adds it to our parsing.

Adds the IsListParenthesizedMeta to aid in differentiating list syntax's

---

docs/upgrades/v0.8-to-v0.9-upgrade.md

Adds 0.9 migration guide from CHANGELOG since 0.8.2

Adds 0.9 migration guide

---

CHANGELOG.md
buildSrc/build.gradle.kts
extensions/build.gradle.kts
lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalBexprToThunkConverter.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/optimizations/ConcatWindowFunction.kt
lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
lang/src/main/pig/partiql.ion
lang/src/test/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPartiQLPhysicalVisitorTransformTestsPass.kt
lang/src/test/kotlin/org/partiql/lang/planner/transforms/optimizations/ConcatWindowFunctionPassTest.kt
lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserMatchTest.kt

- Marks GPML and WINDOW AST nodes as Experimental
- Updates CHANGELOG
No
~Yes. Usage of the WINDOW and GPML nodes will now produce _warnings_ without explicit opt-in
No

Marks GPML and WINDOW AST nodes as Experimental

---

CHANGELOG.md
buildSrc/build.gradle.kts
extensions/build.gradle.kts
lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalBexprToThunkConverter.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/optimizations/ConcatWindowFunction.kt
lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
lang/src/main/pig/partiql.ion
lang/src/test/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPartiQLPhysicalVisitorTransformTestsPass.kt
lang/src/test/kotlin/org/partiql/lang/planner/transforms/optimizations/ConcatWindowFunctionPassTest.kt
lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserMatchTest.kt

This reverts commit f605f2b157c8148268e8935505089f2b27bc12d5.
- < A detailed description >
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Revert "Marks GPML and WINDOW AST nodes as Experimental (#923)"

---

CHANGELOG.md
README.md
examples/src/main/java/org/partiql/examples/S3JavaExample.java
gradle.properties
lang/src/main/kotlin/org/partiql/lang/eval/ExprValue.kt
lang/src/main/kotlin/org/partiql/lang/eval/ExprValueExtensions.kt
lang/src/main/kotlin/org/partiql/lang/eval/ExprValueFactory.kt
lang/src/main/kotlin/org/partiql/lang/eval/IonStructBindings.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerSelectStarTests.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/TestRunner.kt

Prepares 0.9.0 release

---

lang/src/test/kotlin/org/partiql/lang/eval/CastTestBase.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerCustomAnyOfTypeOperationTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerExceptionsTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerFromSourceByTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerLimitTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerUnknownValuesTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatorTestBase.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatorTestSuite.kt
lang/src/test/kotlin/org/partiql/lang/eval/LikePredicateTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/QuotedIdentifierTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/SimpleEvaluatingCompilerTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/CharLengthEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/CharacterLengthEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/ConcatEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/DateAddEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/DateDiffEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/ExtractEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/FilterDistinctEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/FromUnixTimeFunctionTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/LowerEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/SizeEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/SubstringEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/ToStringEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/ToTimestampEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/TrimEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/UpperEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/ExpectedResultFormat.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PipelineEvaluatorTestAdapter.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PipelineEvaluatorTestAdapterTests.kt

- [Closes/Related To] Issue #560 
- POC PR: https://github.com/partiql/partiql-lang-kotlin/pull/892 
- Removed `ION_WITHOUT_ANNOTATION` test format. Changed those test runners which used it to using `ION` test format. Later, we need to figure out what test cases need to get transformed from `ION` to `STRICT`. 
- The only adjustment to the affected test cases was adding `$BAG_ANNOTATION` and `$MISSING_ANNOTATION` to expected Ion results, since these annotations are no longer removed from the actual results by the test runners.
- Some test cases now have to specify `expectedPermissiveModeResult` argument of `runEvaluatorTestCase`, since the expected result in legacy mode (generally, `NULL`) differs from the expected result in permissive mode (generally, `MISSING`). This was a testing bug, …

Removed `ION_WITHOUT_ANNOTATION` test format

---

lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerDateTimeTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/MakeDateEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/MakeTimeEvaluationTest.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/ExpectedResultFormat.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PipelineEvaluatorTestAdapter.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PipelineEvaluatorTestAdapterTests.kt
test/partiql-randomized-tests/src/test/kotlin/org/partiql/lang/randomized/eval/EvaluatingCompilerDateTimeRandomizedTests.kt

- [Closes/Related To] Issue #560
- Remove `ExpectedTestFormat.STRING`. For those test cases which use this format, they are switched to use `ExpectedTestFormat.STRICT` . The `ExpectedTestFormat.STRING` compares actual & expected results in format of string, which is not really good in terms of maintaining tests. 
- No
- No

Remove STRING test format

---

docs/tutorials/Command Line Tutorial.md

None
Was trying to run the CLI with the latest version in `main` and noticed some of commands referenced the old `shell.sh` script rather than `partiql.sh`.
- No, not part of anything that's being released.
- No
- No

Fix mentions of shell.sh to partiql.sh

---

CHANGELOG.md
docs/tutorials/Command Line Tutorial.md
partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/pico/PartiQLCommand.kt
partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/pico/PipelineOptions.kt

- Closes #952 
- Adds support for shebang
- Fixes ability to use passed options for the pipeline.
- Adjusts how we determine whether STDIN is present by using `System.console()` -- this allows partiql to pipe its output to another partiql command.
- With the addition of standard input processing (from #946), we can seemingly add support for shebangs. Essentially, if a user specifies a shebang with the path to the `partiql` executable, this PR allows them to run PartiQL executable files.
- This can help some of our customers write queries in a fast-paced manner
- Users of this feature will need to have the gradle-produced executable (`partiql`) on their PATH.
- Here's an example:
- And here's an example of piping its output to itself:
- And another example with pretty printing:
- And …

Adds support for shebang and fixes pipeline options

---

partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/pico/PartiQLCommand.kt
partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/pico/PipelineOptions.kt

The `globalEnvironment` property of the `PipelineOption`s was initialized during object instantiation which means the `environmentFile` is always null — picocli has not bound input parameters/args to this object yet. By switching the `globalEnvironment` to a getter property, we check `environmentFile` on access.
```sql
> $ ./partiql-app/partiql-cli/build/install/partiql-cli/bin/partiql -e ./partiql-app/partiql-cli/archive/Tutorial/code/q1.env                                                                                               [±global_env ✓]
{ 
'hr': { 
'employees': <<
-- a tuple is denoted by { ... } in the PartiQL data model
{ 'id': 3, 'name': 'Bob Smith',   'title': null }, 
{ 'id': 4, 'name': 'Susan Smith', 'title': 'Dev Mgr' },
{ 'id': 6, 'name': 'Jane Smith',  'title': …
```

Fixes global_env in the shell

---

lang/src/main/kotlin/org/partiql/lang/ast/IsOrderedMeta.kt
lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
lang/src/main/kotlin/org/partiql/lang/eval/visitors/AggregationVisitorTransform.kt
lang/src/main/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
lang/src/test/kotlin/org/partiql/lang/compiler/memorydb/operators/GetByKeyProjectRelationalOperatorFactory.kt
lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerCollectionAggregationsTest.kt

#966 
#951 
Description is in 966 and agg finder fix describe in 951. Peeking the sequence caused it to be instantiated prematurely, so we'll use John's original (and simpler) method of adding a meta to determine which ExprValue to create. The other fixes (it stopped at least? can't say definitively because ... nondeterministic) some nondeterministic behavior we were seeing
No
No
No

Fixes list/bag ExprValue creation in plan evaluator

---

.github/workflows/conformance-report.yml

Adds workflow step to download previously created conformance report with backup condition to re-run if download fails.
---

Add workflow step to download previously created conformance report

---

test/partiql-tests-runner/src/main/kotlin/org/partiql/runner/ConformanceComparison.kt

Conformance comparison report comment had the wrong variable in the difference of passing tests. Should be `${numNewPassing - numOrigPassing}` rather than `${numNewPassing - numOrigFailing}`.
- Updated Unreleased Section in CHANGELOG: No
- No changes to released code

Fix conformance comparison report for passing row

---

.github/workflows/build.yml
CHANGELOG.md
buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt
lang/build.gradle.kts

Dokka generated docs weren't getting added to the Javadoc JAR since I moved publishing to plugin. Now each module that uses the publishing plugin will appropriately create sources and javadoc jars as before.
**Workflow Changes**
**Before - failing (cancelled, or fails after ~40mins)**
Before we had six workflows (three jobs, each run twice for java 11 and 17)
- Build and Test
- tasks: build, test
- Randomized Tests
- tasks: run randomized tests
- Report Generation
- tasks: build, test, generate report, upload report
**After - success ~12mins**
- Randomized Tests
- tasks: run randomized tests
- Report Generation
- tasks: build, test, generate report, upload report
I removed the double build + test between jobs 1 and 2. Now we have four workflows (2 jobs, 2 java versions)
I also used the …

Fixes javadoc jar

---

CHANGELOG.md
lang/build.gradle.kts

Putting the files back to the same jar locations where they used to be before 0.9.0: 
org/partiql/type-domains/partiql.ion and PartiQL.g4, PartiQLTokens.g4 on the top level. 
- Will follow-up shortly.

Put ANTLR and PIG sources back into the jar

---

test/partiql-tests-runner/README.md
test/partiql-tests-runner/build.gradle.kts

Enables overriding partiql-tests-data for conformance report

Enables overriding partiql-tests-data for conformance report

---

examples/src/main/java/org/partiql/examples/PartiQLCompilerPipelineJavaExample.java
examples/src/main/kotlin/org/partiql/examples/PartiQLCompilerPipelineExample.kt
lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerBuilder.kt
lang/src/test/kotlin/org/partiql/lang/compiler/PartiQLCompilerPipelineSmokeTests.kt
lang/src/test/kotlin/org/partiql/lang/compiler/memorydb/QueryEngine.kt
lang/src/test/kotlin/org/partiql/lang/compiler/operators/CustomOperatorFactoryTests.kt
lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt
partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/pipeline/AbstractPipeline.kt

Includes the @Deprecated ceremony where this was exposed through a user-visible method, but I'd be glad not to bother about that if people agree.
- Internal, except for the deprecation. 

Removed unused IonSystem from PartiQLCompilerBuilder (trivial)

---

CHANGELOG.md
partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/shell/Shell.kt

This started by dealing with the issue that the CLI would terminate when one would issue `!!` to see the AST, but the supplied query had a syntax error. 
Another thing was both ERROR! and OK! being printed out on a syntax error. 
(Use something silly like `select +` to reproduce.) 
Besides addressing the above, this also changes which failures are displayed how. 
* When it is an anticipated error from PartiQL (parsing, evaluation, etc), we ought to print the error, but not the stack trace, and continue the repl.  In practice, this means avoiding `catch (ex: Exception)`, instead catching `SqlException`, which is the umbrella for what we ourselves throw on user error.
* OTOH, when it is not an anticipated error, it is likely a bug. Philosophies vary on what to do in this case.  I suggest it …

A couple fixes to error processing in the CLI

---

CHANGELOG.md
lang/src/main/antlr/PartiQL.g4
lang/src/main/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
lang/src/main/pig/partiql.ion
lang/src/test/kotlin/org/partiql/lang/errors/ParserErrorsTest.kt
lang/src/test/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
lang/src/test/kotlin/org/partiql/lang/prettyprint/ASTPrettyPrinterTest.kt
lang/src/test/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinterTest.kt
lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt

An initial portion of experimental CREATE TABLE syntax, with basics of column declarations, with data types and NULL / NOT NULL constraints. 
- Except that the previous plug-the-hole CREATE TABLE syntax would no longer work.

CREATE TABLE initial experimental syntax

---

docs/wiki/tutorials/Command Line Tutorial.md
partiql-cli/partiql.sh

Make CLI runnable again in the build dir, after the recent directory movements. 
- A fix-up to earlier PR(s).

Make CLI runnable again

---

buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt

- N/A
- When running the publish plugin to publish to maven central or maven local, I have encountered a issue. 
See below:
In the debugger: 
I was able to pin down the issue to those two lines here: 
https://github.com/partiql/partiql-lang-kotlin/blob/1f102d6e57655234ac7e491c4d55174cb4f218c0/buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt#L90-L91
Based on the commit history, those two lines were added to make sure that source jar and javadoc jar are included. 
However, https://github.com/partiql/partiql-lang-kotlin/blob/1f102d6e57655234ac7e491c4d55174cb4f218c0/buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt#L63-L64 
should be sufficient, with additional fix in the [commit](https://github.com/partiql/partiql-lang-kotlin/commit/d632290 …

fix maven publish issue

---

docs/wiki/_Sidebar.md

Followup to https://github.com/partiql/partiql-lang-kotlin/pull/930. Adds the wiki sidebar link for the v0.8 -> v0.9 migration guide.

Add wiki sidebar link for 0.8 -> 0.9 migration guide

---

.github/workflows/conformance-report.yml

Noticed that the GH Actions workflow for conformance started failing. Example failed run: https://github.com/partiql/partiql-lang-kotlin/actions/runs/4506051931/jobs/7932435216#step:4:38. I think this is due to the GH Actions workflow running with Gradle 8.0. This PR fixes the conformance gradle version to what's in the `gradle-wrapper`, `7.5.1`.

Fix conformance GH Actions workflow by using a fixed gradle version

---

CHANGELOG.md
partiql-lang/src/main/kotlin/org/partiql/lang/CompilerPipeline.kt
partiql-lang/src/main/kotlin/org/partiql/lang/SqlException.kt
partiql-lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerBuilder.kt
partiql-lang/src/main/kotlin/org/partiql/lang/errors/ErrorAndErrorContexts.kt
partiql-lang/src/main/kotlin/org/partiql/lang/errors/ErrorCode.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/ErrorSignaler.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/builtins/DefinitionalBuiltins.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/SubqueryCoercionVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/VisitorTransforms.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/PartiQLPlannerDefault.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerCollectionAggregationsTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerGroupByTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerOrderByTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/DefinitionalBuiltinsTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/builtins/windowFunctions/WindowFunctionTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/visitors/SubqueryCoercionVisitorTransformTests.kt

- Closes Issue #826
Resolves #826, implementing to-singleton subquery coercion for SQL contexts of SQL-style SELECTs, following what is outlined in Ch 9 of the PartiQL specification.
Natural follow-ups would be #1011 and [#42](https://github.com/partiql/partiql-spec/issues/42). 
The implementation has two parts: 
- New built-in function COLL_TO_SCALAR (defined in the spec), which is used to wrap SELECTs eligible for the coercion. 
- New visitor SubqueryCoercionVisitorTransform that detects eligible SELECTs and applies COLL_TO_SCALAR to them. 
Behavior of COLL_TO_SCALAR (returning MISSING vs an error when the coercion cannot be performed) depends on compilation options, particularly on TypingMode. This dependency is new, compared to other built-ins. Unfortunately, the accommodation for …

To-singleton coercion of SQL-style SELECT subqueries

---

CHANGELOG.md
examples/src/main/java/org/partiql/examples/ParserJavaExample.java
examples/src/main/java/org/partiql/examples/PartiQLCompilerPipelineJavaExample.java
examples/src/main/kotlin/org/partiql/examples/ParserErrorExample.kt
examples/src/main/kotlin/org/partiql/examples/ParserExample.kt
examples/src/main/kotlin/org/partiql/examples/PartiQLCompilerPipelineExample.kt
examples/src/main/kotlin/org/partiql/examples/PreventJoinVistor.kt
partiql-cli/src/main/kotlin/org/partiql/cli/pipeline/AbstractPipeline.kt
partiql-lang/src/main/kotlin/org/partiql/lang/CompilerPipeline.kt
partiql-lang/src/main/kotlin/org/partiql/lang/ast/passes/StatementRedactor.kt
partiql-lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerBuilder.kt
partiql-lang/src/main/kotlin/org/partiql/lang/prettyprint/ASTPrettyPrinter.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLParser.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLParserBuilder.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
partiql-lang/src/main/kotlin/org/partiql/lang/util/AntlrUtilities.kt
partiql-lang/src/main/kotlin/org/partiql/lang/util/NumberExtensions.kt
partiql-lang/src/test/kotlin/org/partiql/lang/ast/IsIonLiteralMetaTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/PartiqlAstExtensionsTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/PartiQLCompilerPipelineFactory.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/evaluatortestframework/VisitorTransformBaseTestAdapter.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransformTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinterTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserCastTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTestBase.kt
partiql-lang/src/test/kotlin/org/partiql/lang/util/ConfigurableExprValueFormatterTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/util/testdsl/IonResultTestCase.kt

Follow up to https://github.com/partiql/partiql-lang-kotlin/pull/949
Removes IonSystem and deprecated parameters for the PartiQLParser
Yes
Yes. We've removed the IonSystem.
No

Removes IonSystem from PartiQLParser

---

partiql-lang/src/main/kotlin/org/partiql/lang/eval/PartiqlAstExtensions.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/FromSourceAliasVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/SelectListItemAliasVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/SelectStarVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/SubstitutionVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/VisitorTransforms.kt

Here are a few touch-ups in SQL-to-PartiQL desugaring that came up while I was working on understanding it, as likely needed for #826.  
The commits are self-contained and are as follows: 
* A few old todos that awaited for PIG copy() methods.
* A few comment touch-ups in desugaring.
* Revisit `FromSourceAliasVisitorTransform` implementation.
* The previous implementation relied on delicate ping-ponging of control between multiple instances of the host (`FromSourceAliasVisitorTransform`) and helper (`InnerFromSourceAliasVisitorTransform`) visitors.
* In the amended implementation, the host visitor drives the traversal and calls a fresh instance of the helper visitor in each spot where a transformation is needed.
* Both implementations create the same number of helper visitors (one per a …

Touch-ups in SQL desugaring

---

partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencer.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/PlanTyper.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/PlanUtils.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/RelConverter.kt
partiql-plan/src/main/resources/partiql_plan.ion

- Closes #1032 
- Renames the unreleased Rel.Common.Schema to Rel.Common.TypeEnv
- No, because Rel.Common.Schema is unreleased

Renames Rel.Common.Schema to Rel.Common.TypeEnv

---

partiql-lang/build.gradle.kts
partiql-spi/build.gradle.kts
partiql-types/build.gradle.kts

- None
- Publishes PartiQL Types
- Removes `libs` usage under `partiql-lang` and replaces with `api` as `:partiql-types` will be published
- These haven't been released

Publishes PartiQL Types

---

.github/workflows/build.yml
gradle.properties

- N/A
- [PR#1041](https://github.com/partiql/partiql-lang-kotlin/pull/1041) contains three changed files, two of which are markdown changes and the other one is to change the version attribute in `gradle.properties`. However, it caused github action to fail. See the error [here](https://github.com/partiql/partiql-lang-kotlin/actions/runs/4684254058/jobs/8300209279?pr=1041). 
```
* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
- The root cause for that issue is OOM. Github only providers workers with 7g of Ram. 
- Setting a value of org.gradle.jvmargs in `gradle.properties` overwrites these Gradle's default jvm args, and those values get fall back to JVM default. 
- In particular, the `MaxMetaspaceSize` value is set to …

debug github action

---

CHANGELOG.md
docs/wiki/upgrades/v0.8-to-v0.9-upgrade.md
partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprValue.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/ExprValueTest.kt

Previous versions of PartiQL supported converting an `IonDatagram` to an `ExprValue` (as a bag). This capability seemed to be unintentionally removed in https://github.com/partiql/partiql-lang-kotlin/pull/881, which was part of the v0.9.0 release.
Also updated the migration guide for 0.8.0 -> 0.9.0 to make note of this change.

Add back ability to convert `IonDatagram` to `ExprValue`

---

CHANGELOG.md
partiql-lang/src/main/antlr/PartiQL.g4
partiql-lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerDefault.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/QueryPlan.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPhysicalVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
partiql-lang/src/main/pig/partiql.ion
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPartiQLPhysicalVisitorTransformTestsPass.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransformTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt

- Closes #1038
- Closes #1043 
- Closes #1052 
- By adding support for the alias and condition in the physical plan, there is no longer a need to rewrite the DML statement into a projection operator -- as requested in 1052.
- Adds support for DML INSERT's WHERE/ALIAS in Parser, AST, and Plans
- Adds support for ALIAS syntax
- Adds a new property `as_alias` to the `insert` AST node.
- Adds `target_alias` property to the `dml_insert`, `dml_replace`, and `dml_update` nodes within the
Logical and Logical Resolved plans
- Adds new physical plan field representing the register allocated to the index.
- Adds support for CONDITION in `ON CONFLICT DO [REPLACE|UPDATE] EXCLUDED WHERE <condition>`
- Adds new property `condition` to the AST nodes of `do_replace` and `do_update`
- Adds `condition` …

Adds support for DML INSERT's WHERE/ALIAS in Parser, AST, and Plans

---

CHANGELOG.md
partiql-lang/src/main/antlr/PartiQL.g4
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/PartiQLVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt

- Closes #1063 
- Prior to this PR, our grammar expressed that users can parse INSERT statements with the *legacy* ON CONFLICT clause. Similarly, they were able to parse *legacy* INSERT statements with the *up-to-date* ON CONFLICT clause.
- This PR updates the ANTLR grammar to disallow this. It also updates the PartiQLVisitor accordingly.
- Tests have been added to assert that mixing-and-matching of the *legacy* and *up-to-date* grammar rules is not allowed.

Fixes parsing of INSERT and its legacy counterparts

---

CHANGELOG.md
README.md
gradle.properties

- PR #1066 
- Merges v0.10.0 branch
- Updates development version to be: v0.10.1-SNAPSHOT

Sets v0.10.1-SNAPSHOT Version

---

partiql-lang/src/main/pig/partiql.ion

I think this has gone unnoticed until now because PIG does not enforce the minimum arity of variadic elements is not enforced at during deserialization.
Related to #1069
See title.
- Updated Unreleased Section in CHANGELOG: No.
- This is a tiny change with very low impact.
- Any backward-incompatible changes? No.

Change minimum number of function call arguments from 1 to 0.

---

partiql-lang/src/main/pig/partiql.ion

To be honest, I do not know why I made this 1 initially, but it's actually totally legit to construct an empty struct.
See title.
- Updated Unreleased Section in CHANGELOG: No.
- This is a tiny change with very low impact.
- Any backward-incompatible changes? No.
- 

Change minimum arity of struct parts to 0 in logical & later plans.

---

CHANGELOG.md
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/mappers/IonSchemaMapper.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/PlannerSession.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/PlanTyper.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/ReferenceResolver.kt
partiql-lang/src/main/kotlin/org/partiql/lang/types/StaticTypeUtils.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/types/StaticTypeTests.kt
partiql-lang/src/test/resources/catalogs/b/b/d.json
partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt
plugins/partiql-mockdb/src/main/kotlin/org/partiql/plugins/mockdb/LocalConnectorObject.kt
plugins/partiql-mockdb/src/test/kotlin/org/partiql/plugins/mockdb/LocalConnectorMetadataTests.kt

- None
- Fixes JOIN predicate by adding the correct bindings to the input to the predicate for typing
- Modifies StructType attribute `fields` to be a List<Field>. This allows for ordering of the Struct as well as duplicate keys.
- Adds attribute, `isOrdered`, to StructType. As the PartiQL Spec allows for ordered tuples in the presence of schema, I opted to add it directly to StructType.
- For referencing attributes of an ORDERED StructType, the behavior is well-defined in grabbing the first attribute:
- > When the tuple t has multiple attributes a, the tuple path navigation t.a will return the first instance of a. Note that for tuples whose order is defined by schema, this is well-defined. For unordered tuples, it is implementation defined which attribute is returned in permissive mode …

Fixes JOIN Predicate and Allows Duplicates in StructType

---

buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt
lib/isl/build.gradle.kts
partiql-lang/build.gradle.kts
partiql-spi/src/main/kotlin/org/partiql/spi/BindingCase.kt
partiql-spi/src/main/kotlin/org/partiql/spi/BindingName.kt
partiql-spi/src/main/kotlin/org/partiql/spi/BindingPath.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/ConnectorObject.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/ConnectorObjectHandle.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/Constants.kt
partiql-types/build.gradle.kts
partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt

- Closes #1079
- Closes #1080
- Closes #1077
- Closes #1078 
- Adds Explicit API Mode to the Publishing Plugin (so that all projects intending to publish will have STRICT Explicit API Mode enabled)
- Allows `partiql-lang` and `isl` to be excluded.
- `lang` will eventually be deprecated/removed
- `isl` may eventually be deprecated/removed
- No. No changes facing the end user.

Adds Explicit API Mode to Publishing Plugin, Plan, and SPI

---

buildSrc/src/main/kotlin/partiql.versions.kt
lib/isl/src/main/kotlin/org/partiql/pig/runtime/workarounds.kt
lib/sprout/src/main/kotlin/org/partiql/sprout/generator/target/kotlin/poems/KotlinBuilderPoem.kt
partiql-lang/src/main/kotlin/org/partiql/lang/domains/util.kt

https://github.com/partiql/partiql-ir-generator/issues/41
The Kotlin target generates code that fails to compile with the error message:` Unresolved reference: asAnyElement`. The workaround is to add this to the consuming project:
```
package org.partiql.pig.runtime
fun kotlin.collections.List<com.amazon.ionelement.api.IonElement>.asAnyElement() = map { it.asAnyElement() }
```
This function has been added to the runtime library and released.
No
No
No

Updates PIG to 0.6.2; removes some workarounds

---

test/partiql-tests-runner/README.md
test/partiql-tests-runner/build.gradle.kts
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/TestRunner.kt

This checks out the git submodule for the most recent version of partiql-tests conformance suite.  
According to a manually-run comparison report, all new failures (and successes) are due to the the new tests that got added to the conformance suite since last refresh.
Also, some documentation tweaks -- see specific comments. 
In addition to the needed improvement with enabling/disabling the conformance suite runs, it would be helpful to get a mechanism for running smaller subsets of the suite (at least being able to limit to a directory), especially when running with IntelliJ UI.
A yet another issue is `DefaultConformanceTestRunner` that runs conformance tests during regular builds, w.r.t. a list of known failures.  After partiql-tests refresh this list became significantly out-of-date. …

Update partiql-tests to the newest; related doc tweaks.

---

partiql-lang/src/main/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
partiql-lang/src/test/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinterTest.kt

#1089 
We use the `IsListParenthesizedMeta` to indicate if a list was parenthesized rather than bracketed as our AST does not model these variants. This is a tiny fix to the QueryPrettyPrinter to ensure the list variant is preserved round-trip.
Nop
No
No

Preserves list variant in QueryPrettyPrinter

---

.gitmodules

In future fresh check-outs of partiql-lang-kotlin, this should help avoid hiccups with git credentials in the submodule. See https://stackoverflow.com/questions/6031494/git-submodules-and-ssh-access/6031607#6031607
- Updated Unreleased Section in CHANGELOG: NO

From HTTP to SSH URL for the test/partiql-tests git submodule.

---

partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprValue.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprValueExtensions.kt
partiql-lang/src/main/resources/org/partiql/schemas/graph.isl
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerGraphMatchTests.kt

Adjustments for running graph conformance tests in partiql-tests (as needed for loading external graphs into evaluation environments) and the tests themselves.
The tests come in two variations: unit tests and conformance tests in `partiql-tests` submodule. 
- Updated Unreleased Section in CHANGELOG: NO
- Not sure; tests are an internal matter?

Initial conformance tests for graph query

---

CHANGELOG.md
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/partiql.conventions.gradle.kts
buildSrc/src/main/kotlin/partiql.versions.kt
examples/build.gradle.kts
partiql-cli/build.gradle.kts

#1075
Updates language level from 1.5 to 1.6.
Yes
From a consumer standpoint, the language target remains 1.4
Yes, using kotlin stdlib 1.6 now

Updates to kotlin 1.6; compile target remains 1.4

---

CHANGELOG.md
buildSrc/src/main/kotlin/partiql.conventions.gradle.kts
buildSrc/src/main/kotlin/partiql.versions.kt

#1075 
Updates Kotlin target to 1.6
Yes
No
Kind of yes? Kotlin Std Libs are being changed from 1.5+ to 1.6.20

Updates Kotlin target to 1.6

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CODE_STYLE.md
CONTRIBUTING.md

- None
- Adds Code Style guidelines
- Adds a Contributors section for releases. See [v0.11.0](https://github.com/partiql/partiql-lang-kotlin/releases/tag/v0.11.0-alpha) to see what the contributors list rendering looks like.
- Updates GH PR template

Updates contributing/style guidelines

---

CHANGELOG.md
partiql-ast/src/main/pig/partiql.ion
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransformTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalResolvedToDefaultPartiQLPhysicalVisitorTransformTestsPass.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransformTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
partiql-parser/src/main/antlr/PartiQL.g4

- Closes #1111 
- Adds support for `EXCLUDED` by:
- Modifying `varRefExpr` in ANTLR to allow for non-reserved keywords. Marks `EXCLUDED` as non-reserved. It is still reserved immediately following `DO REPLACE` and `DO UPDATE`.
- Modifying PIG Logical/LogicalResolved `dml_operation.dml_update` and `dml_operation.dml_replace` to have an optional `row_alias` (string).
- I do this because `dml_update` is used for both `UPSERT` and `INSERT ... ON CONFLICT DO UPDATE ...`. `UPSERT` doesn't have the ability to use the `excluded` table.
- Same goes for `dml_replace` with `REPLACE` and `INSERT ... ON CONFLICT DO REPLACE ...`.
- So, the `row_alias` becomes a variable declaration and therefore gets a dedicated variable in the local registers.
- For identifier resolution, we allow the ON CONFLICT …

Adds syntactic and planning support for EXCLUDED

---

lib/isl/src/test/kotlin/org/partiql/ionschema/discovery/SchemaInferencerFromExampleTests.kt
lib/sprout/src/main/kotlin/org/partiql/sprout/model/Model.kt
lib/sprout/src/main/kotlin/org/partiql/sprout/parser/ion/IonTypeParser.kt
partiql-cli/src/main/kotlin/org/partiql/cli/format/Utilities.kt
partiql-cli/src/main/kotlin/org/partiql/cli/format/dot/Dot.kt
partiql-cli/src/main/kotlin/org/partiql/cli/functions/ReadFile.kt
partiql-cli/src/main/kotlin/org/partiql/cli/shell/Shell.kt
partiql-cli/src/main/kotlin/org/partiql/cli/shell/ShellHighlighter.kt
partiql-lang/src/main/kotlin/org/partiql/lang/CompilerPipeline.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/Bindings.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/EvaluatingCompiler.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprValueExtensions.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/IonStructBindings.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/binding/LocalsBinder.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/builtins/ScalarBuiltinsCollAgg.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/builtins/ScalarBuiltinsSql.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/builtins/internal/TimestampExtensions.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/physical/operators/Accumulator.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/OrderBySortSpecVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/AstToLogicalVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/LogicalToLogicalResolvedVisitorTransform.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/main/kotlin/org/partiql/lang/types/PartiqlPhysicalTypeExtensions.kt
partiql-lang/src/test/kotlin/org/partiql/lang/util/AstExtensions.kt
partiql-spi/src/main/kotlin/org/partiql/spi/BindingName.kt

#1075 
The string functions toUpperCase/toLowerCase are deprecated. Cleaning up the warnings.
No
No
No
Yes

Replaces toUpperCase/toLowerCase with uppercase/lowercase

---

lib/sprout/src/main/kotlin/org/partiql/sprout/generator/target/kotlin/KotlinCommand.kt
lib/sprout/src/main/kotlin/org/partiql/sprout/generator/target/kotlin/KotlinGenerator.kt
lib/sprout/src/main/kotlin/org/partiql/sprout/generator/target/kotlin/KotlinOptions.kt

n/a
Adds configurable `@file:OptIn(...)` annotations to Kotlin generated sourcse.
No, sprout is an internal build tool
No
No
Yes

[Sprout] Adds configurable OptIns to Kotlin target

---

partiql-types/src/main/kotlin/org/partiql/value/PartiQLValue.kt
partiql-types/src/main/kotlin/org/partiql/value/impl/PartiQLValueNullableImpl.kt
partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueTextWriter.kt
partiql-types/src/main/kotlin/org/partiql/value/util/PartiQLValueBaseVisitor.kt
partiql-types/src/test/kotlin/org/partiql/value/io/PartiQLValueTextWriterTest.kt

#1141 
This PR fixes instantiation of nullable collection values by using `isNull()` and `promote()` This is Yingtao's solution from https://github.com/partiql/partiql-lang-kotlin/pull/1131
No
No
No
Yes

Fixes Nullable PartiQLCollectionValue

---

partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-ast/src/main/resources/partiql_ast.ion
partiql-ast/src/test/kotlin/org/partiql/ast/helpers/ToLegacyAstTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt

n/a
Our grammar specifies that aliases are symbol primitives which are either quote or unquoted identifiers.
```antlr
asIdent
: AS symbolPrimitive;
symbolPrimitive
: ident=( IDENTIFIER | IDENTIFIER_QUOTED )
;
```
This PR updates the AST model to match the SQL grammar for symbol identifier as aliases.
No, these changes this is based upon has not been released
No, reason same as above
No
Yes
By …

Updates all aliases to identifier.symbol to match SQL grammar

---

CHANGELOG.md
partiql-cli/src/main/kotlin/org/partiql/cli/utils/ServiceLoaderUtil.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/PartiQLFunction.kt
partiql-types/src/main/kotlin/org/partiql/types/function/FunctionParameter.kt
partiql-types/src/main/kotlin/org/partiql/types/function/FunctionSignature.kt
plugins/partiql-mockdb/src/main/kotlin/org/partiql/plugins/mockdb/Pow.kt
plugins/partiql-mockdb/src/main/kotlin/org/partiql/plugins/mockdb/TrimLead.kt

- [Closes/Related To] Issue #1150 
- Move PartiQLFunction parameters and signatures to partiql-types.
- Updated Unreleased Section in CHANGELOG: 
YES
NO
NO
YES

Move function apis

---

docs/wiki/documentation/Functions.md

Adds the release version for each of the builtin functions. This can help clear up some confusion about why a builtin function is not working on a certain partiql-lang-kotlin version.
- Updated Unreleased Section in CHANGELOG: no -- no code changes.
- Any backward-incompatible changes? no
- Any new external dependencies? no
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? yes

Add builtin function release versions

---

partiql-lang/src/test/kotlin/org/partiql/lang/eval/TypedNullTests.kt

PartiQL spec issue related to Ion's typed nulls.
Adds some tests demonstrating the Kotlin implementation's current handling of typed nulls. This behavior is consistent across the partiql-lang-kotlin versions.
- Updated Unreleased Section in CHANGELOG: No -- no update to public API. Just some tests.

Add tests for Ion's typed nulls

---

CHANGELOG.md
partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValueExperimental.kt

- Add Timestamp StaticType. 
- The idea is to introduce minimal backward incompatible change. 
- Customer should not need to opt-in for timestamp class, or modify their existing codebase if they wish to continue use the ion timestamp. 
- However, if customer want to specify added feature such as precision, with/without timezone, then an explicit opt-in is required. 
- Yes. 
- Should not be. But would appreciate a second option on this. 
- No.  …

Timestamp staticType

---

CHANGELOG.md
README.md
gradle.properties

This reverts commit a2ce4d517207ad5a6ff04ca1f947e11529dcadf7.
- PR #1200  overlooked breaking changing. The next release version should be `0.13.0`. 
- Reverting to make commit history clean. 
- Yes. Reverting. 
-  No
- No. 
- No. 

Revert "Prepares v0.12.1 release (#1200)"

---

CHANGELOG.md
partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/optimizations/FilterScanToKeyLookup.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/optimizations/FilterScanToKeyLookupTests.kt

N/A.
`FilterScanToKeyLookupPass` will now properly ignore primary key equality expressions where both sides reference the candidate row are rewritten.  i.e.:
SELECT * FROM foo AS f WHERE f.id = f.bar
... was previously being rewritten to:
(bindings_to_values
(local_id 0)
(project
(impl <user-impl>)
(var_decl 0)
(path (local_id 0) (lit bar) (case_insensitive)))
)
)
Which is an invalid plan because when the dynamic argument to the project operator is evaluated the local variable 0 hasn't been initialized yet.
See the diff.
No.
No
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Fixes bug in FilterScanToKeyLookupPass

---

partiql-lang/src/test/kotlin/org/partiql/lang/eval/IonAnnotationTests.kt

- Related To Issue https://github.com/partiql/partiql-spec/issues/63 and https://github.com/partiql/partiql-spec/issues/61
This commits adds the tests for ensuring the correct behavior of eliding Ion annotations when evaluating Ion values in PartiQL. The intention for having such tests is to detect regression of the current behavior in future.
- No, this commit does not result in a new feature release.
- No, this commit adds new tests only,
- No. …

Add tests for Ion values with annotations

---

CHANGELOG.md
partiql-cli/src/main/kotlin/org/partiql/cli/pipeline/AbstractPipeline.kt
partiql-cli/src/main/kotlin/org/partiql/cli/shell/RunnablePipeline.kt
partiql-cli/src/main/kotlin/org/partiql/cli/shell/RunnableWriter.kt
partiql-cli/src/main/kotlin/org/partiql/cli/shell/Shell.kt
partiql-lang/src/jmh/kotlin/org/partiql/jmh/benchmarks/CompilerInterruptionBenchmark.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/CompileOptions.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/EvaluatingCompiler.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/Thunk.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerInterruptTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/impl/PartiQLPigParserThreadInterruptTests.kt

- None
- Adds support for thread interruption in compilation and execution
- Adds support for CLI users to use CTRL-C to cancel long-running compilation or execution of queries.
- Adds an `isInterruptible` flag to `CompileOptions` to allow users to opt-in.
- Measured the compilation and execution of long-running queries (7 cross joins, 10 cross joins with aggregations, 10 cross joins with aggregation functions and grouping). See the JMH changes in this PR. We saw an average speedup of:
- Compilation: -2.36%
- Compilation and Evaluation: -1.35%
- Compilation, Evaluation, and Materialization: -0.71%
- Total: -1.47%
- While the impact to speed is low, I still opted to added a flag (`isInterruptible`) to the `CompileOptions` to allow users to opt-in to the new changes.
- Updated Unreleased …

Adds support for thread interruption in compilation and execution

---

CHANGELOG.md
README.md
gradle.properties
partiql-lang/build.gradle.kts
partiql-plan/build.gradle.kts

Adds a Maven publishing step to `partiql-planner` and changes partiql-lang-kotlin's dependency on `partiql-planner` to be `api`.

Add partiql-planner Maven publishing plugin v0.10.1

---

CHANGELOG.md
README.md
gradle.properties
partiql-lang/build.gradle.kts
partiql-plan/build.gradle.kts

Adds a Maven publishing step to `partiql-planner` and changes partiql-lang-kotlin's dependency on `partiql-planner` to be `api`.

Add partiql-planner Maven publishing plugin v0.11.1

---

CHANGELOG.md
README.md
gradle.properties
partiql-lang/build.gradle.kts
partiql-parser/build.gradle.kts
partiql-plan/build.gradle.kts

Adds a Maven publishing step to `partiql-planner` and changes partiql-lang-kotlin's dependency on `partiql-planner` to be `api`.

Prepare v0.13.1 release and add partiql-planner Maven publishing plugin v0.13.1

---

CHANGELOG.md
lib/sprout/src/main/kotlin/org/partiql/sprout/generator/target/kotlin/KotlinGenerator.kt
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
test/sprout-tests/src/test/kotlin/org/partiql/sprout/tests/example/ToStringTests.kt

- None
- Adds toString() override to Sprout generation
- Ion format -- yet, we shouldn't rely on it. See the comments. It's more for readability. We don't format to Ion for:
- Maps
- Imported Types
- Escaped strings
- `toString` isn't a contract.

Adds toString() override to Sprout generation

---

CHANGELOG.md
buildSrc/src/main/kotlin/partiql.conventions.gradle.kts
buildSrc/src/main/kotlin/partiql.versions.kt
partiql-ast/src/main/resources/partiql_ast.ion
partiql-parser/src/main/antlr/PartiQL.g4
partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt
partiql-parser/src/test/kotlin/org/partiql/parser/impl/PartiQLParserSessionAttributeTests.kt

Needed for transpiler. Similar to https://github.com/partiql/partiql-lang-kotlin/pull/1049
Adds the CURRENT_DATE special form to the parser.
**SQL-99 6.19**
```ebnf
<current date value function> ::= CURRENT_DATE
```
YES
NO
NO
YES

Adds CURRENT_DATE special form to parser

---

CHANGELOG.md
README.md
gradle.properties

Prepare v0.13.2 release.
- Updated Unreleased Section in CHANGELOG: No -- release.

Prepare v0.13.2 release

---

CHANGELOG.md
gradle.properties

Prepare v0.13.3-SNAPSHOT. Fix some typos in the CHANGELOG
- Updated Unreleased Section in CHANGELOG: No
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? No

Prepare v0.13.3-SNAPSHOT; fix some typos in CHANGELOG

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt

https://github.com/partiql/partiql-lang-kotlin/issues/1238
When performing a LEFT (or RIGHT join), we must type the right-hand-side (or left-hand-side) as nullable because these joins pad the resultant tuple with NULLs if the condition fails to match.
This logic will type a non-struct value as nullable, but will type the fields of a struct value as nullable. This allows for SQL compatibility of the JOIN operators. Details in Issue #1238
No
This changes the behavior of PlanTyperV0
No …

Adds NULL typing to JOIN operators

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-plan/src/main/resources/partiql_plan_0_1.ion
partiql-planner/src/main/kotlin/org/partiql/planner/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/Errors.kt
partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/TypeUtils.kt

https://github.com/partiql/partiql-lang-kotlin/pull/1226
This is a port of Alan's work on EXCLUDE  (#1226) to the resolve logical plan. 
This passes all existing EXCLUDES tests.
No
No
Yes

Ports EXCLUDE to resolved plan

---

partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt

This printing was incorrect `x['y'] != x.y`
No
No
No
Yes

Remove x['y'] -> x.y printing

---

partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToBinder.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt

- None
- Small PR to update the default binders for CURRENT_USER and CURRENT_DATE.
- Now, `SELECT CURRENT_USER` previously normalized to `SELECT CURRENT_USER AS "_1"`, but now, it normalized to: `SELECT CURRENT_USER AS "CURRENT_USER"`
- No, not to main.
- No
- No

Adds session binders

---

partiql-plan/src/main/resources/partiql_plan_0_1.ion
partiql-planner/PlannerCheckList.adoc
partiql-planner/src/main/kotlin/org/partiql/planner/Header.kt
partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt

- During parsing, say the user enter `trim_leading(val)`, the function will be parsed; the AST would be `Call(id(trim_leading, case_sensitive), val)`
- Because in the header we generated a function signature `fun trim_leading(a)`, the function resolver will recognized the function. 
- But the trim leading function actually represent a special form of trim, `TRIM( LEADING FROM a)`. 
- In this PR, we stop this scenario by adding a Unicode private use char to the key in Function Map for those functions that should be hidden. 
- No. Change to unreleased feature. 
- No. Change to unreleased feature. 
- No. 
- Do …

Hidden functions

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/dogs.ion
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/os.ion

- None
- Fixes pathing of expressions by visiting root.
- Adds tests for pathing
- Previously, queries would fail because we would forget to type the root of paths (unless the rex was a variable). The following used to fail:
- `[0, 1, 2, 3][0]`
- `SELECT typical_allergies[0] AS main_allergy FROM dogs`
- and more
-  While this PR doesn't have anything to do with scalar functions, I was previously adding tests for scalar functions and am including them here. See `testScalarFunctions` in the schema inference tests.
and [Code …

Fixes pathing of expressions

---

partiql-lang/build.gradle.kts
partiql-planner/src/main/kotlin/org/partiql/planner/Header.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/FnResolver.kt
partiql-types/src/main/kotlin/org/partiql/types/function/FunctionSignature.kt

- N/A
- Control Flow functions such as `coalesce` and `nullIf` will be rewrited to a case when expression. 
- Support for ANY type in Function Header. 
- No, feature branch. 
-  No. 
-  No.
Yes. 

Support ANY type in Header functions And Planning of Control Flow Functions. 

---

partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt

- None
- <strike>Couldn't compile. The latest commit made use of `rexOpCase` which now has a default rex as an attribute. (See the 2nd latest commit).</strike>
- #1257 add a default rex as an attribute. 
- Do your changes …

Fixes rewrite of control flow. 

---

partiql-planner/src/main/kotlin/org/partiql/planner/Env.kt
partiql-planner/src/test/kotlin/org/partiql/planner/EnvTest.kt

- None
- This fixes references to globals
- Previously, when a user typed a query like `SELECT * FROM DoGs`, we would add a qualified identifier `"DoGs" (case-sensitive)` to the `globals` in the `TypeEnv`. This was wrong. The actual global should've been called `"dogs"` to match the filesystem. On top of that, we should've put the **entire** path as a global. AKA: `"default"."pql"."dogs"`. This PR fixes that.
By …

Fixes references to globals

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
partiql-planner/src/test/kotlin/org/partiql/planner/typer/PlanTyperTest.kt
partiql-planner/src/testFixtures/resources/catalogs/default/b/b/d.ion
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/T.ion
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/closed_duplicates_struct.ion
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/closed_ordered_duplicates_struct.ion
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/closed_union_duplicates_struct.ion
partiql-planner/src/testFixtures/resources/catalogs/default/pql/main/open_duplicates_struct.ion

- None
- Disambiguates references to struct attributes
- Before, when someone were to type `{ 'aBc': { 'DeF': 1 } }.abc.def` it would return a plan representing `{ 'aBc': { 'DeF': 1 } }.abc.def`. This PR disambiguates the plan by instead returning `{ 'aBc': { 'DeF': 1 } }."aBc"."DeF"`. This will help with transpilation.
- This PR handles union types, closed content structs, ordered structs, and open structs. Please see the tests for more information. The tests are lengthy, however, they are written to avoid any potential breaks in the future.
- Please see the kdoc for `PlanTyper.inferStructLookup` for information on how we handle the above.
- Do your …

Disambiguates references to struct attributes

---

.github/workflows/build.yml
partiql-lang/build.gradle.kts
partiql-lang/src/test/kotlin/org/partiql/lang/planner/SchemaLoader.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/impl/PartiQLParserSessionAttributeTests.kt
partiql-planner/build.gradle.kts
partiql-planner/src/testFixtures/kotlin/org/partiql/planner/test/PartiQLTestProvider.kt
plugins/partiql-memory/README.md
plugins/partiql-memory/build.gradle.kts
plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryCatalog.kt
plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryConnector.kt
plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryObject.kt
plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryPlugin.kt
plugins/partiql-memory/src/test/kotlin/org/partiql/plugins/memory/InMemoryPluginTest.kt
settings.gradle.kts

- Adds in memory connector for testing purpose. 
- Fixes the CI builds. 
Notes on CI builds: 
1. Github actions used packaged code (JAR) for build. 
- We can not turn folder/files in Jar to a Java File object easily, especially with the current set up in which the local plugin takes a path and we retrieve the path and turn it to `File` object later. 
- Solution:
-   During build process, we list out the path to each individual test resource, and store the path into a single file. 
-   We retrieve the content of resource using path, and load the content to a in-memory connector. 
2. Github checkout action is not running against the code in the RP. Instead, it runs against some merged version that is based on top of the target branch. 
Fix : …

In-memory Connector

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-plan/src/main/resources/partiql_plan_0_1.ion
partiql-planner/src/main/kotlin/org/partiql/planner/Header.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/typer/TypeUtils.kt
partiql-planner/src/test/kotlin/org/partiql/planner/typer/FunctionResolverTest.kt
partiql-types/src/main/kotlin/org/partiql/types/function/FunctionSignature.kt
plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/functions/Pow.kt
plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/functions/TrimLead.kt

- None
- Adds support for dynamic dispatch of functions.
- I've opted to model the possible "candidates" directly within the plan under a dynamic function call. We re-use the same logic of static calls (inserting the coercions where necessary) and maintaining the order of potential functions to dynamically invoke.
- By modeling it this way, we can remove all the `any -> any` functions from the PartiQL header.
- We also don't need to generate a massive `CASE WHEN` -- we can let the engine handle this specifically.
- We handle MISSING appropriately.
- In order to do this effectively, I compute the permutations of the potential types of the arguments. Consider the following invocation: `BINARY_PLUS(INT4|INT8, STRING|INT8|INT2)`. The permutations would result in the following "possible" …

Adds support for dynamic dispatch of functions

---

partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToBinder.kt
partiql-ast/src/main/kotlin/org/partiql/ast/normalize/NormalizeSelect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/normalize/NormalizeSelectTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-planner/src/testFixtures/resources/catalogs/default/aggregations/T.ion
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/aggregations.sql

We lost derived binding value in the `SELECT *` and didn't have tests on our normalization passes. This simply adds them back via slightly different mechanism. Rather than using the select item index, we increment a shared count. 
```
-- Example
SELECT a, bar(b), baz(c) FROM T
-- before used index (ie _2 and _3)
SELECT VALUE { 'a': a, '_2': bar(b), '_3': baz(c) FROM T
-- bug (always was _1)
SELECT VALUE { 'a': a,  '_1': bar(b), '_1': baz(c) } FROM T
-- bug fixed and counts up
SELECT VALUE { 'a': a, '_1': bar(b), '_2': baz(c) FROM T
```
No
No
No …

Fixes derived binder numbering

---

partiql-plan/src/main/resources/partiql_plan.ion
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Plan.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilders.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/util/PlanRewriter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/visitor/PlanBaseVisitor.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/visitor/PlanVisitor.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt

- #1267 
- I realize I left an unused plan node in my PR of dynamic dispatch of functions. In the PR above, there is both a scalar function call (of static, unresolved, and dynamic) and a scalar function definition (resolved, unresolved, dynamic). There need not be a "definition" of a dynamic function call -- as this wouldn't make much sense. Hence, it was unused.
- This PR removes the node. Since it was unused, no other code needs to be modified.
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/ …

Removes the dynamic function definition

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-plan/src/main/resources/partiql_plan.ion
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Plan.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilders.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/visitor/PlanBaseVisitor.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/visitor/PlanVisitor.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt

- None
- Modifies how we model paths in the plan
- As discussed offline, when dealing with the semantics of pathing, there are 3 core operations:
1. Indexing into an array. Ex: `a[0], a[1 + 1]`
2. Sensitive lookup in a tuple. Ex: `a."b", a['b'], a[CAST('a' || 'b' AS STRING)]`
3. Insensitive lookup in a tuple. Ex: `a.b`
- The above will be part of the PUBLIC API. However, in order to appropriately handle the subtle differences between `a.b`, `a."b"`, and `a['b']` when we haven't typed yet-- the internal APIs contain:
1. Indexing into an array. Ex: `a[0], a[1 + 1]`
2. Sensitive lookup on a tuple. Ex: `a['b'], a[CAST('a' || 'b' AS STRING)]`
3. Dot-notation lookup on a tuple/schema. Ex: `a.b` and `a."b"`. This has a subtle difference to the public API.
- We convert the dot-notation lookup to …

Modifies how we model paths in the plan

---

partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/predicate/OpBetweenTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/predicate/OpComparisonTest.kt
partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueIonReader.kt

1. Adds support for using datetime types in comparison function in the Function header.
2. Convert Ion Value to PartiQL value in Rex Converter.
3. Adds a convenient API in PartiQLValueIonReader for easier loading of ionElement to PartiQLValue.
Note that as of today we don't support implicit casting between date time types. i.e., Timestamp to Date, Timestamp to time etc. 
- No. 
-  No. 
-  No. 
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_S …

Support Datetime Types in comparison functions

---

CHANGELOG.md
partiql-lang/src/main/kotlin/org/partiql/lang/eval/EvaluatingCompiler.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprValue.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprValueExtensions.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/Named.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/StructExprValue.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerExcludeTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerSelectStarTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/exclude.sql

https://github.com/partiql/partiql-lang/issues/27 (still experimental until the RFC is merged).
Implementation of `EXCLUDE` operator (https://github.com/partiql/partiql-lang/issues/27) in the `EvaluatingCompiler`. A future PR will implement `EXCLUDE` in the `PhysicalPlanCompiler`, targeting the [partiql-eval branch](https://github.com/partiql/partiql-lang-kotlin/tree/partiql-eval).
- Updated Unreleased Section in CHANGELOG: **[Yes]**
By submitting this pull …

Implement EXCLUDE in `EvaluatingCompiler`

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt

- Previously the timestamp type would get parsed to a Time Type due to a bug in the parser. 
```
t1 is Timestamp
```
```
Expected:
(is_type
(id t1 (case_insensitive) (unqualified))
(timestamp_type
null))
Actual:
(is_type
(id t1 (case_insensitive) (unqualified))
(time_type
null))
```
- Yes. 
- Yes. Bug fix. 
-  No.
Yes.  …

Fix Timestamp Type Parsing Issue.

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt

- None
- Adds support for EXCLUDE in the default SqlDialect

Adds support for EXCLUDE in the default SqlDialect

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelFilter.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt

- Preceded by #1286 
- Adds Filter

Adds support for FILTER in Eval

---

partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLHeader.kt

N/A
Adds int32 and int64 operators to the date_add function. Before we only had the arbitrary-sized integer which we don't want as default.
No
No
No
Yes

Adds int32 and int64 variants of date_add

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt

- See #1292 
- I was adding DISTINCT to the evaluator, and I noticed it was missing in the plan.
- This PR adds support for DISTINCT in the Planner

Adds support for DISTINCT in the Planner

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/Record.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelJoin.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelJoinInner.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelJoinLeft.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathKey.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprStruct.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValue.kt

- None
- Adds INNER JOIN, LEFT JOIN, Path Step Key & Fixes ExprStruct
- Going to add the other JOINS after this. Wanted to get the ExprStruct and PathStepKey out.

Adds INNER JOIN, LEFT JOIN, Path Step Key & Fixes ExprStruct

---

CHANGELOG.md
docs/wiki/documentation/Functions.md
partiql-lang/src/main/kotlin/org/partiql/lang/eval/builtins/ScalarBuiltinsExt.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/builtins/functions/FilterDistinctEvaluationTest.kt

- Fixes https://github.com/partiql/partiql-lang-kotlin/issues/1277
The `PlanCompiler` was outputting a bag when `DISTINCT` and `ORDER BY` were present in a query. A list should have been outputted as `EvaluatingCompiler` outputs. `PlanCompiler` rewrites the `DISTINCT` to use the `ExprFunction` `filter_distinct` to preserve a collection's distinct elements. This PR changes that function to return a list when the input is a list.
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STY …

Fix `PlanCompiler` output type for `DISTINCT` + `ORDER BY`

---

partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/pivot.sql
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/sanity.sql

- Fixes typo which was using scan instead of scan_indexed
- Adds static typing of the PIVOT projection
No
No
No
Yes

Fixes scan_indexed and adds PIVOT

---

CHANGELOG.md
docs/wiki/documentation/Functions.md
partiql-eval/src/main/kotlin/org/partiql/lang/eval/internal/builtins/ScalarBuiltinsExt.kt
partiql-eval/src/test/kotlin/org/partiql/lang/eval/internal/builtins/functions/FilterDistinctEvaluationTest.kt
partiql-eval/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/builtins/ScalarBuiltinsExt.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/pivot.sql
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/sanity.sql

- Port fix from #1277 to `partiql-eval` branch
Add fix to PlanCompiler for `DISTINCT` + `ORDER BY` to `partiql-eval` branch.

Merge `main` to `partiql-eval` (incl #1298 fix)

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-ast/src/test/kotlin/org/partiql/ast/helpers/ToLegacyAstTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt

N/A couldn't find an issue for this.
Fixes the PIVOT "key" and "value". It's` <value> AT <key>` but we've had this flipped.
Yes
For semver no, but it's a bug fix.
No
Yes

Fixes parsing of PIVOT, replicates the bug in legacy conversion

---

CHANGELOG.md
partiql-cli/src/main/kotlin/org/partiql/cli/utils/ServiceLoaderUtil.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQL.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValue.kt
partiql-types/src/main/kotlin/org/partiql/value/helpers/ToIon.kt
partiql-types/src/main/kotlin/org/partiql/value/impl/BagValueImpl.kt
partiql-types/src/main/kotlin/org/partiql/value/impl/ListValueImpl.kt
partiql-types/src/main/kotlin/org/partiql/value/impl/SexpValueImpl.kt
partiql-types/src/main/kotlin/org/partiql/value/impl/StructValueImpl.kt
partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueIonReader.kt
partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueTextWriter.kt
partiql-types/src/main/kotlin/org/partiql/value/util/PartiQLValueBaseVisitor.kt
partiql-types/src/test/kotlin/org/partiql/value/io/PartiQLValueIonSerdeTest.kt
partiql-types/src/test/kotlin/org/partiql/value/io/PartiQLValueTextWriterTest.kt

N/A
A sequence gets exhausted after consumed once which does not make it a good option for the **default** backing field. This PR replaces the collection data structure with the Iterable interface. This allows requesting a new iterator which gives freedom in the implementation of the backing structure. You can use sequences or lazily-generated iterators, but importantly this is not the default.
Yes
No. PartiQLValue is considered experimental.
No …

Use Iterable for PartiQLValue collections rather than Sequence

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/main/resources/partiql_ast.ion
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt
partiql-plan/src/main/resources/partiql_plan.ion
partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Plan.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilders.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/util/PlanRewriter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/visitor/PlanBaseVisitor.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/visitor/PlanVisitor.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt

Refactors the modeling of `EXCLUDE` in the `partiql-ast` and `partiql-plan`. Changes include
- `EXCLUDE` root modeled as a variable reference rather than an identifier symbol
- `EXCLUDE` wildcard steps modeled using an enum to differentiate between the two types (tuple vs collection)
- Change `EXCLUDE` class names in `partiql-ast` to align w/ the `partiql-plan` modeling
By submitting this pull request, I …

Refactor modeling of `EXCLUDE` in `partiql-ast` and `partiql-plan`

---

partiql-lang/src/jmh/kotlin/org/partiql/jmh/benchmarks/PartiQLParserBenchmark.kt

JMH benchmark was using the old `PartiQLParserBuilder.standard().build()` to create the parser. Following #1309, JMH benchmark GH actions CI broke. Changed to use `PartiQLParser.default()`.
- No change to public api

Fix jmh benchmark after #1309

---

CHANGELOG.md
gradle.properties
partiql-lang/build.gradle.kts

- Prepares v0.14.1-SNAPSHOT
- Adds link for v0.13.2 to v0.14.0 commit comparison
- Removes some redundant dependencies in `partiql-lang`

Prepare v0.14.1-SNAPSHOT; remove duplicate dependencies

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt

N/A
Fixes typo when producing public API plan from the internal typed plan. Should be patched released asap.
No
No
No

Fix Rex.Op.Path typo

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprTupleUnion.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValue.kt

- None
- Adds evaluation of TUPLEUNION

Adds evaluation of TUPLEUNION

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCase.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt

- None
- Adds support for evaluation of CASE WHEN THEN
- See the `@Disabled` tests. Since we don't have EQUALS implemented yet, those tests are disabled.

Adds support for evaluation of CASE WHEN THEN

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlannerBuilder.kt

N/A
This commit adds the ability to pass a user-defined-function signature to the planner.
Yes
No
No
Yes

Adds UDF scalar signatures to planner

---

partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt

- None
- Adds literal STRUCT test just so we don't accidentally break anything in future.
- No, just adding a test.

Adds literal STRUCT test

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelScanIndexed.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathKey.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPivot.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt

Updates pivot on rebase and join tests
Yes

Updates pivot on rebase and join tests

---

partiql-eval/src/main/kotlin/org/partiql/eval/PartiQLEngine.kt
partiql-eval/src/main/kotlin/org/partiql/eval/PartiQLEngineBuilder.kt
partiql-eval/src/main/kotlin/org/partiql/eval/PartiQLEngineDefault.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprGlobal.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathIndex.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathSymbol.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/Connector.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/ConnectorBindings.kt
plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalConnector.kt
plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryBindings.kt
plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryConnector.kt
test/partiql-tests-runner/build.gradle.kts
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestEval.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestReport.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/LegacyExecutor.kt

This PR introduces a getBindings() method to PartiQL Plugins. A plugin will return a PartiQLBindings object which returns a PartiQLValue given a ConnectorObjectPath.
I have implemented this for the MemoryPlugin which is now used to load globals from the conformance test suite. This PR also includes an implementation of a TestExecutor for the ongoing evaluator work.
Yes

Initializes bindings in connectors and globals

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelDistinct.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt

- None
- Adds support for DISTINCT in Planner and Eval
- I also refactored the tests to make it easier to rebase and continue developing. Prior sanity tests were 17 passing and 2 disabled. There are now 18 passing and 2 disabled. The newly introduced one had to do with DISTINCT.

Adds support for DISTINCT in Eval

---

CHANGELOG.md
partiql-cli/src/main/kotlin/org/partiql/cli/Main.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlanner.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlannerBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlannerDefault.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/Header.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/FnResolver.kt
partiql-planner/src/test/kotlin/org/partiql/planner/HeaderTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/EnvTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/FunctionResolverTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PartiQLTyperTestBase.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/ConnectorMetadata.kt

N/A
This PR replaces https://github.com/partiql/partiql-lang-kotlin/pull/1309 as we need function information to come from the catalog (ConnectorMetadata).
Yes
Technically yes, but these are unreleased. This will be in a 0.14.1 patch to replace lost functionality of 0.14.0-alpha used by the transpiler.
- < In addition, please also mention any other …

Moves ConnectorMetadata to planner session for PartiQLPlanner re-use

---

partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PartiQLHeader.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/is_type.sql

N/A
Reduces redundancy of the IS TYPE operators as they do not need to be defined for each individual type.
No
No, internal typer concern for 0.14
No …

Remove redundancy by using ANY parameter for IS TYPE operators

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlannerBuilder.kt

- #1323 
- Re-adds removed builder APIs and adds deprecation notice
- I went through the JAPI compliance checker. Based on that, followed the guidance.
- This is a pre-req to v0.14.1 release.

Re-adds removed builder APIs and adds deprecation notice

---

.github/workflows/conformance-report.yml
test/partiql-tests-runner/README.md
test/partiql-tests-runner/build.gradle.kts
test/partiql-tests-runner/src/main/kotlin/org/partiql/runner/ConformanceComparison.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestBase.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestEval.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestLegacy.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/report/ReportGenerator.kt

Update: We can now access the full report from Github Action run. In both the step summary and the produced artifact. See [link](https://github.com/yliuuuu/partiql-lang-kotlin/actions/runs/7483462300?pr=15).  
- This PRs builds on #1289. The main goal is to have incorporate multiple backend in conformance tests GitHub action. 
- For every pull request, the GitHub CI now posts comments on 1) cross engine comparison base on the pull request commit; 2) cross commit comparison for every engine between pull request commit and head of target commit. 
For an example comment message, see: https://github.com/yliuuuu/partiql-lang-kotlin/pull/15#issuecomment-1886095877
Note: For the new eval engine: there is one test (`path expression with ambiguous table alias (lowercase), …

add conformance reporting

---

partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-parser/src/main/antlr/PartiQL.g4
partiql-parser/src/main/kotlin/org/partiql/parser/PartiQLParser.kt
partiql-parser/src/main/kotlin/org/partiql/parser/PartiQLParserBuilder.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/util/DateTimeUtils.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserFunctionCallTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserSessionAttributeTests.kt

This PR extends the PartiQL grammar to support qualified identifiers in routine invocation (FunctionCall). The AST already models this so this PR does not introduce an AST changes.
SQL-99 10.4 p.354 — Routine Invocation
```bnf
<routine invocation> ::= <routine name> <SQL argument list>
<routine name> ::= [ <schema name> <period> ] <qualified identifier>
```
**IMPORTANT**
We _may_ need to introduce larger changes to the grammar as this PR does not add qualified names to special forms.
No
No
No …

Adds qualifiers to function call expressions

---

partiql-plan/src/main/resources/partiql_plan.ion

This PR refactors catalog references to use an untyped pointer (ref) with typed entries for values and functions.
This is a prerequisite to part 2 of https://github.com/partiql/partiql-lang-kotlin/pull/1335
Yes
No
Yes
By submitting this pull request, I confirm that my contribution is made under the …

Adds generic catalog reference with typed catalog items

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeEnv.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/EnvTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/TypeEnvTest.kt

While working towards unifying our resolution logic for catalog identifiers, I began cleaning up the Env.kt. This cleans up local resolution (isolating all logic to TypeEnv for easy testing). It also appropriately prioritizes known schema matches over open schema matches (known vs not known).
This matches what is defined in our specification for locals resolution, but there's a possible extension to discuss. We may consider matching longest locals paths. If you read p38 carefully, it indicates we only match the path root for locals (that's what in this PR) — but I believe we should consider matching longest local variable paths as well.
No
No
- Any new external dependencies? …

Isolates local variable resolution logic

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeEnv.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/EnvTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/TypeEnvTest.kt

- Cherry Pick 89d38df7116fa3ae1eb1db91262a7a8ab87a763c
and …

Partiql plugin cherrypick

---

partiql-eval/build.gradle.kts
partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallDynamic.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallStatic.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-plan/src/main/resources/partiql_plan.ion
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Plan.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/builder/PlanBuilders.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/util/PlanRewriter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt

- None
- Adds support for dynamic dispatch in evaluation
- As all of the logic for matching function resides in the planner, I updated the plan representation of dynamic dispatch to hold the expected argument types for each candidate function. This should make our implementation faster, as the checks are minute.
- As the function pathing is still being worked on, I added a temporary deprecated API to help load in functions for execution. This will be removed once pathing is added.
- Any backward-incompatible changes? **YES**
- The modelling of dynamic dispatch has changed slightly in the plan representation. …

Adds support for dynamic dispatch in evaluation

---

CHANGELOG.md
README.md
buildSrc/src/main/kotlin/partiql.versions.kt
gradle.properties

- Upgrades IonJava dependency to latest, v1.11.1
- Prepares next release version, v0.14.2

Upgrade IonJava to v1.11.1; prepare v0.14.2 release

---

CHANGELOG.md
README.md
buildSrc/src/main/kotlin/partiql.versions.kt
gradle.properties

Backport of #1350. Targets base of v0.13.3 which is based off the v0.13.2 release version.
- Upgrades IonJava dependency to latest, v1.11.1
- Prepares next release version, v0.13.3

Upgrade IonJava to v1.11.1; prepare v0.13.3 release

---

CHANGELOG.md
README.md
buildSrc/src/main/kotlin/partiql.versions.kt
gradle.properties

Backport of #1350. Targets base of v0.12.2 which is based off the v0.12.1 release version.
- Upgrades IonJava dependency to latest, v1.11.1
- Prepares next release version, v0.12.2

Upgrade IonJava to v1.11.1; prepare v0.12.2 release

---

partiql-eval/src/main/kotlin/org/partiql/eval/PartiQLEngine.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelScanIndexedPermissive.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelScanPermissive.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallDynamic.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallStatic.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathIndex.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathKey.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathSymbol.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPermissive.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPivotPermissive.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprStruct.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValue.kt
partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueIonReader.kt
plugins/partiql-plugin/src/main/kotlin/org/partiql/plugin/internal/fn/scalar/FnLike.kt
plugins/partiql-plugin/src/main/kotlin/org/partiql/plugin/internal/fn/scalar/FnLikeEscape.kt
plugins/partiql-plugin/src/main/kotlin/org/partiql/plugin/internal/fn/scalar/FnLower.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt

- None
- Adds support for PERMISSIVE vs STRICT
- In short, this implementation attempts to reduce as much computation/checking as possible. In STRICT mode, we never attempt to recover from a TypeCheckException. In Permissive mode, given that MISSING represents a type-check exception and is largely propagated through operations, we attempt to catch TypeCheckExceptions as infrequently as possible (only when we need to). We specifically catch the errors (according to the specification) when:
- the value of an attribute in a struct results in a TypeCheckException.
- an element in an array results in a TypeCheckException
- creating the elements of a SELECT VALUE (AKA the constructor results in a TypeCheckException)
- when the inputs to a function (that takes in ANY/MISSING) results in a …

Adds support for PERMISSIVE vs STRICT

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt

- None
- Return type for `SqlDialect`'s `defaultReturn` function was `Nothing` rather than `SqlBlock`. This led the functions directly returning `defaultReturn` (e.g. `visitTypeCustom`) to have an output type of `Nothing` rather than `SqlBlock`.

Fix SqlDialect's `defaultReturn` return type to be `SqlBlock`

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt

Consider if we have `a : StaticType.UnionOf(INT4, NULL)`
The query `a + a` would be routed to a dynamic call, because the `buildArgumentPermutations` would attempts to match signatures with args `INT4, INT4`, `NULL, INT4`, `INT4, NULL`, `NULL, NULL`. 
See example Plan: 
```
⚬ PartiQLPlan[tag=Plan-36809b3]
├──Catalog[name=test, tag=Plan-c9b14412]
│  └──Symbol[type=union(null, int4), tag=Plan-fdf51022]
└──Query[tag=Plan-439af0a1]
└──Rex[type=union(int2, null, int4), tag=Plan-ecb47ef3]
└──Dynamic[tag=Plan-32394b25]
├──Rex[type=union(null, int4), tag=Plan-3b304cd]
│  └──Global[tag=Plan-b7513a12]
│     └──Ref[catalog=0, symbol=0, tag=Plan-eaf2e03d]
├──Rex[type=union(null, int4), tag=Plan-2be5e6ab]
│  └──Global[tag=Plan-7faea094]
│     └──Ref[catalog=0, …
```

resolve nullable type causes a dynamic call

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt

Typing of a `CASE WHEN` branch does not flatten the type in certain circumstances. Noticed this when I called `SELECT <table>.<struct>.* FROM <table>` and the an argument of the `TUPLEUNION` was an `AnyOfType` containing a single `STRUCT`.
- Updated Unreleased Section in CHANGELOG: **[Yes]**

Flatten case when branch result type in PlanTyper

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelLimit.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOffset.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt

- Remodel Limit / Offset
~~If limit is 0 or null, the query should behavior as the same as if there were no limit clause.~~
If offset is 0 or null, the query should behavior as the same as if there were no offset clause. 
If limit and offset clause both exist, the offset should get executed first. 
Update: 
When converting from AST to Plan, append the offset node first then the limit node. 
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base. …

Partiql eval limit offset

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeLattice.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt

- Changed Function Match logic.
-  Previously we assumed that if all the args require coercion to match the function signature, then the function match should failed, as there should be another function signature that requires no coercion. Such transitive coercion model is not correct. 
-  Change the matching logic to gather all possible candidate, then sort them first based on number of coercion and then the function Precedence. 
- Also, added the constrained decimal as a valid numeric type when generating function signature. 
- Yes. 
- No API changes. 
- < In addition, …

Func resolver

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelJoinNestedLoop.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/Symbols.kt

- Joins previously would hang if condition is false. 
- This is because we missed moving the pointer for the RHS record to the next one. 
- Also, small fix on the logic to insert ref into symbol. 
- < In addition, please also mention any other alternatives you've considered and the reason they've been …

Fix Join Hang

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt

Applies fix to SqlDialect output for unary ops from https://github.com/partiql/partiql-scribe/pull/22.

Fixes `SqlDialect` output for unary ops

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallDynamic.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValueComparatorInternal.kt
partiql-types/src/main/kotlin/org/partiql/value/util/NumberExtensions.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestBase.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt

- A collection of small fixes
1. Port the change from #1366
2. Dynamic function matches logic. 
3. Comparator support for Big Integer. 
4. Substring function name. 
- Do your changes comply …

Partiql eval continue

---

gradle.properties
partiql-cli/src/main/kotlin/org/partiql/cli/Main.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/DynamicTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/functions/NullIfTest.kt
partiql-planner/src/testFixtures/resources/catalogs/default/pql/t_item.ion
partiql-planner/src/testFixtures/resources/inputs/basics/case.sql

#1390 
This PR introduces the typing rules of a CASE-WHEN which types branches to the minimum common supertype. In the case of types from different sub-type families (STF) then we go up to the ANY type (known now as `dynamic`).
No
This is a behavioral change due to a bug.
No

Apply SQL 9.3 typing rules for CASE-WHEN

---

CHANGELOG.md
partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt

Change the `StaticType.AnyOfType`'s `.toString` method to not perform a `.flatten()` call. This can make things clearer when debugging `StaticType.AnyOfType` strings.
Previously,
`StaticType.unionOf(StaticType.STRING, StaticType.NULL)` and `StaticType.unionOf(unionOf(StaticType.STRING, StaticType.NULL))` would output the same string, which made debugging confusing.
By submitting this pull request, I confirm …

Change StaticType.AnyOfType's .toString to not perform .flatten()

---

partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerExcludeTests.kt

Adds a unit-test for excluding an attribute that is as a result of a new projection from a sub-query.
More details:
```
PartiQL> SELECT tbl2.* EXCLUDE tbl2.dervidedColumn FROM (SELECT tbl1.*, tbl1.a.b + 2 AS dervidedColumn FROM <<{'a': {'b': 2}, 'foo': 'bar', 'foo2': 'bar2'}>> AS tbl1) AS tbl2;
==='
<<
{
'a': {
'b': 2
},
'foo': 'bar',
'foo2': 'bar2'
}
>>
---
OK!
PartiQL> SELECT tbl2.* FROM (SELECT tbl1.*, tbl1.a.b + 2 AS dervidedColumn FROM <<{'a': {'b': 2}, 'foo': 'bar', 'foo2': 'bar2'}>> AS tbl1) AS tbl2;
==='
<<
{
'a': {
'b': 2
},
'foo': 'bar',
'foo2': 'bar2',
'dervidedColumn': 4
}
>>
---
OK!
```
- No, this is just a uni-test addition.
- No.
- Any …

Add EXCLUDE test for a new projection from subquery

---

CHANGELOG.md
partiql-ast/src/main/kotlin/org/partiql/ast/sql/Sql.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlBlock.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlLayout.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/internal/InternalSqlBlock.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/internal/InternalSqlDialect.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/internal/InternalSqlLayout.kt

#1402 
#1400 
This adds the improved pretty-printer behind the default public pretty-print function while keeping the existing Sql*.kt classes for backwards compatibility.
Yes
No
No
Yes

Adds more efficient internal pretty-printing

---

CHANGELOG.md
partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt

Fixes some previous buggy behavior when flattening an `AnyOfType` containing `AnyType`:
```
AnyOfType(setOf(StaticType.INT, StaticType.ANY))           // union(int, any)
AnyOfType(setOf(StaticType.INT, StaticType.ANY)).flatten() // union(int, any)
```
With this change, the above will now be:
```
AnyOfType(setOf(StaticType.INT, StaticType.ANY))           // union(int, any)
AnyOfType(setOf(StaticType.INT, StaticType.ANY)).flatten() // any
```
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/ …

Fix StaticType.flatten() on AnyOfType containing AnyType

---

CHANGELOG.md
partiql-plan/src/main/resources/partiql_plan.ion
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/DynamicTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/resources/partiql_plan_internal.ion
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/inputs/basics/case.sql
partiql-planner/src/testFixtures/resources/inputs/basics/coalesce.sql
partiql-planner/src/testFixtures/resources/inputs/basics/nullif.sql

Related to https://github.com/partiql/partiql-scribe/issues/26.
Previous rewrite according to SQL-99 spec was creating large logical plans with nested `COALESCE` and `NULLIF` expressions. This change makes dedicated `COALESCE` and `NULLIF` nodes within the logical plan.
Other than that,
- fixes a prior typing issue related to `COALESCE` (context in https://github.com/partiql/partiql-lang-kotlin/pull/1404#discussion_r1543461964)
- fixes a slight bug in dynamic typer w/ `StaticType.ANY`, where it was previously getting expanded to all of its types
Adding new nodes to the plan is technically a breaking change for the `PlanVisitor` interface. Tracking the sprout generation to add a warning on …

Add `COALESCE` and `NULLIF` to the logical plan

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/Errors.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeEnv.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/utils/PlanUtils.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/catalogs/default/aggregations/T1.ion
partiql-planner/src/testFixtures/resources/catalogs/default/aggregations/T2.ion
partiql-planner/src/testFixtures/resources/catalogs/default/aggregations/T3.ion
partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt

- None
- Fixes aggregations of attribute references to values of union types
- Before, in `TypeEnv`, we would assert, when looking up an attribute on a value, that the value were a `StructType` -- even though it could be a union of StructTypes. Or a union of other types. This PR handles this scenario.
- This PR does NOT handle heterogeneous data for aggregation functions. See the new, disabled test in PlanTyperTestsPorted.
- For the purposes of better error reporting, modified the definition of UndefinedVariable. See the CHANGELOG.
- What should `AVG` return? I've pasted a snippet from SQL:1999 which shows that we are conformant, however, I'm not sold.
- Any backward-incompatible changes? **YES**
- Yes, but not API incompatible changes. …

Fixes aggregations of attribute references to values of union types

---

CHANGELOG.md
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserDDLTest.kt
partiql-parser/src/main/antlr/PartiQL.g4
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserDDLTests.kt

- Add grammar rule for qualified name. 
- Support Parsing for using qualified name as table name in DDL command CREATE TABLE and DROP TABLE. 
- We can reuse the rule for qualified name for other SQL object in the future if needed. 
I don't think this PR is backward incompatible as the new AST carries the notion of qualified identifier, and uses the identifier as the output for CREATE TABLE and DROP TABLE node. 
The grammar rule changes affected the generated Antlr Parser but no user should directly invoke the Antlr generated parser anyway (i.e., The Antlr generated parser should not be sem-ver-ed in my opinion.)
The Pig AST remains unmodified.
- Yes.  …

qualified identifier

---

CHANGELOG.md
lib/sprout/src/main/kotlin/org/partiql/sprout/generator/target/kotlin/poems/KotlinVisitorPoem.kt

- Closes #1405.
- Copies over the kdoc warning from #1406.
Similar to #1406 but just adds the warning to not implement the sprout-generated visitor interfaces. This will currently be applied for the `AstVisitor` and `PlanVisitor`.
```Kotlin
// AstVisitor.kt
/**
* WARNING: This interface should not be implemented or extended by code outside of this library.
* Please extend [AstBaseVisitor].
*/
public interface AstVisitor<R, C> {
// rest of code
}
```
```Kotlin
// PlanVisitor.kt
/**
* WARNING: This interface should not be implemented or extended by code outside of this library.
* Please extend [PlanBaseVisitor].
*/
public interface PlanVisitor<R, C> {
// rest of code
}
```
- Any new external …

Add warning to not implement sprout-generated visitor interfaces

---

.github/workflows/build.yml

- None
- PRs targeting `v1` branch were not running the `build.yml` GH Action which runs the gradle build and tests
- Changes `build.yml` to run on every branch
- No public API changes.

Run build + tests on every branch

---

buildSrc/src/main/kotlin/partiql.conventions.gradle.kts
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelJoinNestedLoop.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOffset.kt
partiql-plan/src/main/resources/partiql_plan.ion
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlanner.kt
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlannerBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PartiQLPlannerDefault.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PlannerFlag.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PlanningProblemDetails.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ProblemGenerator.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/resources/partiql_plan_internal.ion
partiql-planner/src/test/kotlin/org/partiql/planner/PlanTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/PlannerErrorReportingTests.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PartiQLTyperTestBase.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/test/kotlin/org/partiql/planner/util/PlanNodeEquivalentVisitor.kt
partiql-planner/src/test/resources/outputs/basics/select.sql
partiql-types/src/main/kotlin/org/partiql/errors/Problem.kt

**Description**
Re-apply #1385
Yes

Apply "PartiQL Eval - Planner Mode (#1385)"

---

partiql-ast/src/main/kotlin/org/partiql/ast/normalize/NormalizeFromSource.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
test/partiql-tests-runner/build.gradle.kts

* Unpivot AT Alias Normalization
* equiv wildcard steps struct
* PERMISSIVE
* LEGACY
* equiv path expression with wildcard steps
* PERMISSIVE
* LEGACY
* unpivotMissing
* PERMISSIVE
* LEGACY
* unpivotEmptyStruct
* PERMISSIVE
* LEGACY
* unpivotStructWithMissingField
* selectFromScalarAndAtUnpivotWildCardOverScalar
* UNPIVOT Empty
* pathUnpivotEmptyStruct1
* pathUnpivotEmptyStruct2
* pathUnpivotEmptyStruct3
* Unable to resolve IS_STRUCT
* equiv attribute value pair unpivot missing
Yes
By submitting this pull request, I confirm that my contribution …

Fixes to UNPIVOT normalization and empty struct typing

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprMissing.kt

Possible replacement for https://github.com/partiql/partiql-lang-kotlin/pull/1416/
Makes a planner missing node into a compile-time error for strict mode.Locally went from 780 failing to 591 failing.
Yes

Makes a planner missing node into a compile-time error for strict mode

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallDynamic.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCast.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprSelect.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/operator/rex/ExprCallDynamicTest.kt

Handles null calls in dynamic dispatch
```
OVERLAY mismatched type, compileOption: LEGACY
null value on any of the 3 inputs returns false{likeExpr:" d.sid LIKE null ESCAPE null "}, compileOption: PERMISSIVE
null value on any of the 3 inputs returns false{likeExpr:" d.sid LIKE null ESCAPE null "}, compileOption: LEGACY
null value on any of the 3 inputs returns false{likeExpr:" d.sid LIKE null ESCAPE '[' "}, compileOption: PERMISSIVE
null value on any of the 3 inputs returns false{likeExpr:" d.sid LIKE null ESCAPE '[' "}, compileOption: LEGACY
null value on any of the 3 inputs returns false{likeExpr:" d.sid LIKE 'S1' ESCAPE null "}, compileOption: PERMISSIVE
null value on any of the 3 inputs returns false{likeExpr:" d.sid LIKE 'S1' ESCAPE null "}, compileOption: LEGACY
null value on any of …
```

Handles null calls in dynamic dispatch

---

partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-ast/src/main/resources/partiql_ast.ion
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserDDLTest.kt
partiql-parser/src/main/antlr/PartiQL.g4
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserDDLTests.kt

- Supports parsing of Attribute-Level Constraint (CHECK, NULL, NOT NULL, UNIQUE, PRIMARY KEY)
- Supports parsing of Table-Level Constraints (CHECK, UNIQUE, PRIMARY KEY)
- It contains breaking changes on the AST modeling. in particular remodeling of constraints to be unnested from table definition. 
- This is because the constraint can be reused in multiple parts of the DDL operation, (in this PR, attribute level constraint and table level constraints; in the future, we might needs to use constraint in ALTER Statement). 
- Supports parsing of Attribute-Level Constraint (CHECK, NULL, NOT NULL, UNIQUE, PRIMARY KEY)
- Supports parsing of Table-Level Constraints (CHECK, UNIQUE, PRIMARY KEY)
- Modeling of DDL node. 
- DDL node is modeled as a wrapper around …

Support parsing for attribute and tuple level constraint

---

partiql-ast/api/partiql-ast.api
partiql-parser/api/partiql-parser.api

- Running `./gradlew apiDump` to fix build. 
and [Code …

run apiDump

---

partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueIonReader.kt

N/A
There is a lot of unnecessary computation in `PartiQLValueIonReaderBuilder.build(ionElement: IonElement)` as it converts from `IonElement -> IonValue -> text Ion -> PartiQLValue`. This PR eliminates the hop to `IonValue`, resulting in `IonElement -> text Ion -> PartiQLValue`.
```
// Current implementation
val reader = IonReaderBuilder.standard().build(ionElement.toIonValue(IonSystemBuilder.standard().build()))
val writer = IonTextWriterBuilder.standard().build(out)
writer.writeValues(reader) 
```
The IonReader in the current implementation is completely unnecessary. We can eliminate the construction and overhead of passing data through an IonReader by writing the `IonValue`s directly to the writer.
```
val writer = IonTextWriterBuilder.standard().build(out) …
```

Remove unnecessary conversion steps in PartiQLValueIonReaderBuilder

---

partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/errors/ParserErrorsTest.kt
partiql-parser/src/main/antlr/PartiQL.g4
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt

- Adds non-reserved keywords from SQL-99 (https://ronsavage.github.io/SQL/sql-99.bnf.html#non-reserved%20word)
- Reworks the following ANTLR rules
- `functionName` -- gets rid of hard-coded reserved keywords as function names block
- `symbolPrimitive` -- adds `nonReserved` keywords to this rule
- No, v1 branch
- Any backward-incompatible changes? **[NO?]**
- Will have some behavioral changes related to some invalid queries not resulting in a parse error (will still be an evaluation error)
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blo …

Add to non-reserved keywords; rework `functionName` and `symbolPrimitive` parse rules

---

buildSrc/src/main/kotlin/partiql.versions.kt
partiql-lang/build.gradle.kts

#1439 had upgraded the gradle version to 8+, which is incompatible with the previous JMH plugin version, 0.5.3. This PR upgrades the JMH plugin version to the latest, 0.7.2, which is compatible w/ gradle 8+.
The older version caused a build failure for the GH actions JMH steps -- https://github.com/partiql/partiql-lang-kotlin/actions/runs/9086996607/job/24974662217.
- No public API changes.
- Any new external dependencies? **[YES]**
- Upgrade jmh plugin version from 0.5.3 to 0.7.2 (also involved using the updated plugin name). …

Upgrade JMH plugin dependency to 0.7.2

---

CHANGELOG.md
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/inputs/basics/case.sql

#1471 
Details are in the linked issue. Effectively this PR makes INT an alias for INT4. Today, the typing and handling of the 32-bit integer is covered by INT4, but we have (for historical reasons) had INT as the Ion unbounded integer. This has created a situation in which INT != INT4 and INT has no precision whereas BIGINT does; therefore BIGINT < INT.
The other systems we integrate with all have INT = INT4 because SQL dictates you must have a bound precision for the INTEGER type and pretty much every implementation uses 32-bit precision.
**Update**
```
SMALLINT    -> 16-bit
INT         -> 32-bit
BIGINT      -> 64-bit
```
Now, this PR is a somewhat sly half-measure by making INT an _alias_ to INT4 so that I don't have to change any planning/typing logic. John is working on updates to …

Changes INT/INTEGER to be an alias for INT4

---

docs/wiki/documentation/Functions.md

- Previous `Functions.md` placed some text builtin functions under the "math functions" header. Moved to the main header.
- Rendered -- https://github.com/partiql/partiql-lang-kotlin/blob/fix-function-page-heading/docs/wiki/documentation/Functions.md
- No code changes.

Fix Functions.md heading for text functions

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/PartiQLHeader.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeLattice.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt

#974 
Today the planner only has a `cast_decimal(v)` function which is used in coercions but does not support parameters. This PR adds `cast_decimal(v, p, s)` along with using the parameters in typing judgements.
```sql
CAST(v AS DECIMAL)      -- arbitrary precision/scale decimal
CAST(v AS DECIMAL(P))   -- decimal with precision = P and scale = 0
CAST(v AS DECIMAL(P,S)) -- decimal with precision = P and scale = S
```
```sql
-- | AST                        | Plan
--------------------------------|----------------------
CAST(v AS DECIMAL)           -- | cast_decimal(v)
CAST(v AS DECIMAL(P))        -- | cast_decimal(v, P, 0)
CAST(v AS DECIMAL(P,S))      -- | cast_decimal(v, P, S)
```
No …

Adds support for parameterized decimal cast

---

.github/workflows/conformance-report.yml

- None
- Applies fix from #1485 (cherry picked from commit 68e4849b152debc3bf5964c9dccd0082d80ed26e)
- No API changes

Update conformance GH action gradle version (#1485)

---

CHANGELOG.md
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-types/src/main/kotlin/org/partiql/value/io/PartiQLValueTextWriter.kt
partiql-types/src/test/kotlin/org/partiql/value/io/PartiQLValueTextWriterTest.kt

- Implements #1491
- Adds an implementation of datetime values for the `PartiQLValueTextWriter`
- With this change, `SqlDialect` will also be able to print datetime literals.

Add implementation of date, time, and timestamp values for `PartiQLValueTextWriter`

---

partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigParser.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTestBase.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt

- Fixes #1498 
- Previous behavior on `v1` allowed for inserting whitespace and comments between the angle brackets of a bag constructor. This PR corrects the behavior and gives an error for these scenarios.
- This PR follows what the Definitive ANTLR 4 Reference describes in Chapter 12 regarding double right angle brackets:
>  To address this, either we can add semantic predicates to the grammar or
we can check the parse tree afterward using a listener or visitor to ensure that
the > token column numbers are adjacent for shift operators. It’d be inefficient
to use predicates during the parse, so it’s better to check the right shift operators
after the parse. Most language applications need to walk the parse tree anyway.
I looked at some other alternatives such as
- pushing the typing to …

Fix bag constructor parsing

---

partiql-ast/build.gradle.kts
partiql-coverage/build.gradle.kts
partiql-plan/build.gradle.kts
partiql-planner/build.gradle.kts
partiql-spi/build.gradle.kts
partiql-types/build.gradle.kts

- None
- Fixes the publishing of jars for non-shadowed packages. Previously, all the packages that don't shadow any packages would fatjar all the dependencies (e.g. kotlin, ion-element). With this change, we now exclude those dependencies, so the jar contains what was there previously.
- Previous packages that shadowed certain dependencies (i.e. `partiql-parser` and `partiql-lang-kotlin`) did not have this issue
- Testing
- Ran `publishToMavenLocal` and compared the jars between 0.14.5 and this version
- Published jars for this version do not have the extra dependencies and retain the existing APIs
- Updated Unreleased Section in CHANGELOG: **[NO]** No api changes.
- Do your changes comply with the …

Fix published jars for non-shadowed packages

---

partiql-ast/build.gradle.kts
partiql-coverage/build.gradle.kts
partiql-eval/build.gradle.kts
partiql-plan/build.gradle.kts
partiql-planner/build.gradle.kts
partiql-spi/build.gradle.kts
partiql-types/build.gradle.kts

(cherry picked from commit 6b49fc19f0e18fc5a80d1b8c07e9c0fac9b2f492)
Targets `v1` branch and copies patch to `partiql-eval` branch.
Below description copied from #1504.
- None
- Fixes the publishing of jars for non-shadowed packages. Previously, all the packages that don't shadow any packages would fatjar all the dependencies (e.g. kotlin, ion-element). With this change, we now exclude those dependencies, so the jar contains what was there previously.
- Previous packages that shadowed certain dependencies (i.e. `partiql-parser` and `partiql-lang-kotlin`) did not have this issue
- Testing
- Ran `publishToMavenLocal` and compared the jars between 0.14.5 and this version
- Published jars for this version do not have the extra dependencies and retain the existing APIs
- Updated Unreleased …

Cherry picks #1504 (Fix published jars for non-shadowed packages)

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/internal/InternalSqlDialect.kt
partiql-ast/src/main/resources/partiql_ast.ion
partiql-ast/src/test/kotlin/org/partiql/ast/helpers/ToLegacyAstTest.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
partiql-parser/src/main/antlr/PartiQLParser.g4
partiql-parser/src/main/antlr/PartiQLTokens.g4
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserDDLTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserOperatorTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserSessionAttributeTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt

- Closes out https://github.com/partiql/partiql-lang-kotlin/issues/1478
- Adds an operator node to AST
- Adds additional parsing rules for special character sequences that can become operators
- `v1` branch
- Yes but on `v1` branch

Add operator node to AST and parser

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCast.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/FnResolver.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/Scope.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/Strategy.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeEnv.kt
partiql-planner/src/test/kotlin/org/partiql/planner/PlannerErrorReportingTests.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/ScopeTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/TypeEnvTest.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/sql/SqlBuiltins.kt
partiql-spi/src/main/kotlin/org/partiql/spi/connector/sql/builtins/FnNot.kt
partiql-types/src/main/kotlin/org/partiql/value/PartiQLValueComparatorInternal.kt

- This increases conformance by 184 tests (3.14%). See the [report](https://github.com/partiql/partiql-lang-kotlin/actions/runs/9898594883?pr=1508).
- This updates rules for variable resolution
- Adds support for casting from dynamic
- Updates tests to give greater visibility into errors

Updates rules for variable resolution

---

partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserLiteralTests.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/util/NumberUtils.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/util/NumberUtilsTest.kt

#1482 
Applies +/- signs to numeric literals.
No
No
No
Yes

Fixes parsing of signed numeric literals

---

partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Catalog.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Catalogs.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Identifier.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Name.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Namespace.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Path.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Session.kt
partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Table.kt

#1496 
Adds session, path, and identifiers to the catalog package with support for case-insensitive identifiers.

Updates catalog names for case-insensitive lookup

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt

- None
- The sonatype host that we publish to now requires a token to publish (more on [tokens](https://central.sonatype.org/publish/generate-token/#create-an-account))
- Our previous plugin for publishing, gradle maven publish [plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) would not work for this new auth requirement
- Migrated to use https://github.com/gradle-nexus/publish-plugin, which worked for publishing to our sonatype host.
- Testing -- ran `./gradlew publish` and the artifacts appeared in the sonatype server for release
- No, no changes to source code.
- No, no changes to source code.
- Any new external dependencies? **[YES]**
- Yes, for publishing, …

Update Maven publishing to use nexus publish plugin

---

partiql-eval/src/main/java/org/partiql/eval/value/Datum.java
partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallDynamic.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCallStatic.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprMissing.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt

- Fixes function invocation for missing arguments and fixes evaluation of `Rex.Op.Missing`.

Fixes function invocation for missing arguments

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ProblemGenerator.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/ir/Nodes.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/AstToPlan.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/Symbols.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/CompilerType.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/RexReplacer.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/utils/PlanUtils.kt
partiql-planner/src/main/resources/partiql_plan_internal.ion
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt

#1496 
This PR replaces the internal planner identifiers with the Identifiers and Names used by the Catalog for catalog object resolution. Notably there are no public API changes (no need for API dump) and there are no changes to any test cases. It is a fairly straightforward replacement, and soon the BindingName/BindingPath will be replaced by these to further reduce the redundancy.
- Updated Unreleased Section in CHANGELOG: **No**
- Any backward-incompatible changes? **No**
- Any new external dependencies? **No**
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **Yes**
By submitting this pull request, I …

Replaces internal IR ids and paths with the catalog identifiers and names

---

partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/catalogs/default/aws/ddb/pets.ion

```SQL
CREATE TABLE PETS (
id INT4,
breed STRING,
tag INT2
)
```
Tests:
```SQL
-- #1 should succeed
CAST(true AS INT2) --
-- #2  should fail
CAST((s : STRING) AS LIST)
-- #3 should succeed
CAST((i : INT2) AS INT4)
-- #4 should succeed
CAST((i : INT4) AS INT2)
```
As part of a specification work, we want to make the behavior for the #4 more visible:
From SQL-99 Section 6.22: <cast specification>:
```
If SD (source data type) is exact numeric or approximate numeric, then
Case:
i) If there is a representation of SV (source value) in the data type TD (target data type) that does not lose any leading si-gnificant digits after rounding or truncating if necessary, then TV is that representation.
The choice of whether to round or truncate is implementation-defined.
ii) Otherwise, an exception …
```

Add more cast tests

---

CHANGELOG.md
gradle.properties
partiql-cli/src/main/kotlin/org/partiql/cli/shell/ShellHighlighter.kt
partiql-lang/build.gradle.kts
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigParser.kt
partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
partiql-lang/src/main/kotlin/org/partiql/lang/util/AntlrUtilities.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/impl/PartiQLPigParserSpyTest.kt
partiql-lang/src/test/kotlin/org/partiql/lang/syntax/impl/PartiQLPigParserThreadInterruptTests.kt

- None
- Tries fixing the `partiql-lang` dependency on `partiql-parser`
- Since the ANTLR shading change (https://github.com/partiql/partiql-lang-kotlin/pull/1439), any call to the `PartiQLParserBuilder.standard()` from the Maven release of 0.14.6 would result in a `NoSuchMethodError` when attempting to parse. This was due to a `partiql-lang` using its own ANTLR dependency rather than `partiql-parser`'s shaded ANTLR dependency.
- It was not detected sooner in the normal gradle build because we would previously only generate the shaded ANTLR dependency when publishing the jars to Maven.
- We should have been using this [configuration](https://gradleup.com/shadow/multi-project/#depending-on-the-shadow-jar-from-another-project) provided by the shadow plugin for multi-project builds.
- Simple …

Fix antlr dep partiql-lang

---

partiql-plan/api/partiql-plan.api
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/Rel.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelAggregate.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelBuilder.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelExcept.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelIntersect.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelJoin.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelProject.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelScan.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelScanIndexed.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelSort.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelUnion.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rel/RelUnpivot.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/Rex.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexBuilder.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexCoalesce.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexCollection.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexGlobal.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexLit.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexSelect.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexSubquery.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/rex/RexVar.kt

This PR adds dataframe-like fluent builders to the logical plans. We have recurring customer asks of having calcite style algebra builders, and [we have had _some_ offering like this with the generated IRs](https://github.com/partiql/partiql-lang-kotlin/tree/main/partiql-ast), but these were more like convenience methods than actual dataflow builders.
For example, the builders were just POJO-style builders, and the DSL is just kotlin stuff for calling methods. Whereas these are consistent with a dataflow builder.
**Before**
```kotlin
// SELECT x FROM T
val query = rex(
type = ..,
op = RexOpSelect(
constructor = rex(
type = ...,
op = rexOpStruct(fields = listOf(rex(type=..., op=rexopVar)
input = rel(
type = ...,
op = relOpProject(
projections = ...
..
)
```
This is _really_ bad and not …

Initializes logical plan builders

---

test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/test/TestRunner.kt

- None
- Seems like the conformance test runner was not reporting back test failures that expected an `EvaluationFail` but did not error

[v1] Fix try-catch for conformance tests expecting an error

---

CHANGELOG.md
gradle.properties
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/DynamicTyper.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/catalogs/default/pql/t_item.ion
partiql-planner/src/testFixtures/resources/inputs/basics/case.sql
plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalSchema.kt

- Base #1549 on tip of v0.14.7. 
- Change version to v0.14.8-SNAPSHOT. (The target branch is not a release branch). 
1. Preserve constraint in dynamic typer
Previous, 
```
CASE  WHEN <condition> THEN <DECIMAL(10,5)>
ELSE null
END;
```
return Decimal Type with arbitrary precision and scale
Similarly: 
```
CASE  WHEN <condition> THEN <VARCHAR(10)>
ELSE null
END;
```
return String Type with arbitrary length constraint. 
With this PR: 
```
CASE  WHEN <condition> THEN <DECIMAL(10,5)>
ELSE null
END;
```
returns DECIMAL(10,5).
```
CASE  WHEN <condition> THEN <VARCHAR(10)>
ELSE null
END;
```
returns VARCHAR(10)
2. Type Constraint Promotion
If the common super type is of single type and require no coercion, the dynamic typer should perform promotion if applicable. …

[v0.14.8-SNAPSHOT] Preserve constraint for decimal, string in dynamic typer

---

CHANGELOG.md
README.md
gradle.properties
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/DynamicTyper.kt

- None
- Prepares v0.14.8 release

Prepare 0.14.8 release

---

test/partiql-tests-runner/src/main/kotlin/org/partiql/runner/ReportAnalyzer.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/ConformanceTestEval.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/report/ReportGenerator.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/test/TestRunner.kt

- Updates to latest conformance tests
- Adds 10 groups of temporarily ignored tests to later fix to align with project management tasks
- This will allow us to more easily develop the v1 branch while checking any diff in conformance. Then, tackling these 10 groups will be targeted.
- Fixes ignored tests not being shown in the conformance report
Note: The [report](https://github.com/partiql/partiql-lang-kotlin/actions/runs/10600100459?pr=1570) looks a bit weird due to the ignored tests now being shown. Before, they were incorrectly marked as passing, so now it looks like there's a decrease in the number of passing.

Updates to latest conformance tests

---

partiql-plan/api/partiql-plan.api
partiql-plan/src/main/kotlin/org/partiql/plan/v1/Schema.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/builder/PlanFactory.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/builder/RexBuilder.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rel/RelAggregateCall.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rel/RelExcludePath.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rel/RelExcludeStep.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rel/RelJoin.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rel/RelScan.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rex/RexBag.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rex/RexCallDynamic.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rex/RexCallStatic.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rex/RexNullIf.kt
partiql-plan/src/main/kotlin/org/partiql/plan/v1/operator/rex/RexVisitor.kt

#1548 
This PR applies the modifications to the v1.plan package which we needed to switch the intermediate representation used for execution.
It adds,
- dynamic calls
- exclude
- paths
- nullif
There are cleanup TODOs for several things we needed to pass existing tests with minimal changes, these include
- removal of nullif?
- fix subqueries in planner
- join schemas? …

Ports evaluation changes to v1 plans

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/partiql.versions.kt
partiql-ast/api/partiql-ast.api
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-eval/api/partiql-eval.api
partiql-lang/api/partiql-lang.api
partiql-lang/build.gradle.kts
partiql-lang/src/main/kotlin/org/partiql/lang/ast/passes/StatementRedactor.kt
partiql-lang/src/main/kotlin/org/partiql/lang/ast/passes/inference/StaticTypeExtensions.kt
partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/PartiqlAstSanityValidator.kt
partiql-lang/src/main/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerNAryTests.kt
partiql-plan/api/partiql-plan.api
partiql-planner/build.gradle.kts
partiql-spi/api/partiql-spi.api
partiql-types/api/partiql-types.api

- None. Kotlin 1.8+ will be helpful for the other task I'm working on to add simpler AST classes, specifically support for the `@Builder` Lombok annotation.
Upgrades v1 branch of PLK to Kotlin 1.9. Not sure yet which version of Kotlin we want to support for v1 since there are [Kotlin releases](https://kotlinlang.org/docs/releases.html#release-details) after 1.9.
Summary of changes required to get existing code working
- Upgrade related dependencies (Kotlinx coroutines, Dokka) to later version
- Upgrade PIG dependency to 0.6.3 -- 0.6.2 does not work in Kotlin 1.7 and later since `?.` operator on non-null types gives an error
- `partiql-planner` relied on Dokka's `relativeTo` -- changed to use Kotlin standard's `relativeTo`
- Re-run of `apiDump` since Kotlin 1.9 added additional functions …

[v1] Upgrade to Kotlin 1.9

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/Errors.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/ExcludeUtils.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/catalogs/default/b/b/b_open.ion
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/exclude.sql

- Related to https://github.com/partiql/partiql-lang/issues/91
Gives a plan-time **warning** when, in the presence of closed schema, and `EXCLUDE` path does not exclude a value.
---
Attribute not in struct
```
SELECT * EXCLUDE t.attr_does_not_exist FROM << { 'a': 1 } >> AS t;
```
^ will result in the error message 
```
Exclude path 't.attr_does_not_exist' does not exclude any values
```
---
Exclude collection wildcard step on a struct
```
SELECT * EXCLUDE t.a[*]
FROM <<{ 'a': { 'b': { 'c': 0, 'd': 'foo' } } } >> AS t;
```
^ will result in the error message
```
Exclude path 't.a[*]' does not exclude any values
```
---
- Do your changes comply with the …

[0.14.9-SNAPSHOT] Adds warnings for `EXCLUDE` paths that don't exclude any value

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/main/kotlin/org/partiql/ast/sql/internal/InternalSqlDialect.kt
partiql-ast/src/main/resources/partiql_ast.ion
partiql-ast/src/test/kotlin/org/partiql/ast/helpers/ToLegacyAstTest.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt

- https://github.com/orgs/partiql/discussions/92
- https://github.com/partiql/partiql-lang-kotlin/tree/v1-no-pv
- #1589 
This PR removes eager-parsing of Ion in the AST (ONLY) and introduces the parameterized VARIANT type. I am working on a subsequent[ PR to remove PartiQLValue from the planner ](https://github.com/partiql/partiql-lang-kotlin/tree/v1-no-pv)which will eliminate eager-parsing of Ion entirely.
This PR is limited to only the necessary AST changes and does not modify the grammar or other components.
and [Code …

Generalizes back-tick Ion to a variant pair in the AST

---

partiql-cli/src/main/kotlin/org/partiql/cli/Main.kt
partiql-cli/src/main/kotlin/org/partiql/cli/shell/Shell.kt
partiql-eval/api/partiql-eval.api
partiql-eval/src/main/kotlin/org/partiql/eval/PartiQLResult.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/CastTable.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/statement/QueryStatement.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEngineDefaultTest.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/casts/CastTable.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-spi/api/partiql-spi.api
partiql-spi/src/main/java/org/partiql/spi/value/Datum.java
partiql-spi/src/main/kotlin/org/partiql/spi/value/ion/IonDatum.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt

- Fixes small evaluation bugs related to casts, types, etc
- This is in relation to the removal of v0.x APIs from the v1 branch
- Updated PartiQLResult to return Datum, not PartiQLValue

Fixes small evaluation bugs related to casts, types, etc

---

CHANGELOG.md
README.md
gradle.properties
partiql-parser/build.gradle.kts
partiql-spi/build.gradle.kts
partiql-types/build.gradle.kts

This PR prepares the 1.0.0-rc.1 release which targets the v1-rc1 branch. Two things need to be done before this is merged.

Prepares 1.0.0-rc.1 release

---

CHANGELOG.md
README.md
gradle.properties
partiql-parser/build.gradle.kts
partiql-spi/build.gradle.kts
partiql-types/build.gradle.kts

This PR cherry-picks the rc.1 release and includes the rc.2-SNAPSHOT version for development.

Prepares rc.2-SNAPSHOT

---

.github/workflows/conformance-report.yml

- Noticed this issue in https://github.com/partiql/partiql-lang-kotlin/pull/1579#issuecomment-2397848467 and https://github.com/partiql/partiql-lang-kotlin/pull/1616
- Since the update to the conformance comparison report, the GH Actions step to find the previous command was searching for the wrong string. This led to a GH Actions comment for every commit.
- No, v1 branch + no public API or behavioral change
By …

[v1] Fix conformance report comment finding

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/v1/Ast.java
partiql-ast/src/main/java/org/partiql/ast/v1/AstVisitor.java
partiql-ast/src/main/java/org/partiql/ast/v1/QueryBody.java
partiql-ast/src/main/java/org/partiql/ast/v1/SelectItem.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphLabel.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphQuantifier.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphSelector.java

- Adds factory methods for every hand-written AST class
- Fixes some AST classes/functions
- Add constructors for some classes
- Fix naming of `visitSelectItemAll` -> `visitSelectItemStar`
- Change `@NotNull Long` -> `long`
- No, targeting v1 branch
- Yes but on v1 branch
By submitting this pull request, I confirm that my contribution is made under …

[v1] Add AST factory methods; some fixes to AST classes

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/v1/AstEnum.java
partiql-ast/src/main/java/org/partiql/ast/v1/DataType.java
partiql-ast/src/main/java/org/partiql/ast/v1/DatetimeField.java
partiql-ast/src/main/java/org/partiql/ast/v1/Enum.java
partiql-ast/src/main/java/org/partiql/ast/v1/FromType.java
partiql-ast/src/main/java/org/partiql/ast/v1/GroupByStrategy.java
partiql-ast/src/main/java/org/partiql/ast/v1/JoinType.java
partiql-ast/src/main/java/org/partiql/ast/v1/Nulls.java
partiql-ast/src/main/java/org/partiql/ast/v1/Order.java
partiql-ast/src/main/java/org/partiql/ast/v1/SetOpType.java
partiql-ast/src/main/java/org/partiql/ast/v1/SetQuantifier.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/Scope.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/SessionAttribute.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/TrimSpec.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/WindowFunction.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphDirection.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphRestrictor.java

- The previous sprout-generated code used Kotlin enum classes which provided some helper methods when working with enum constants -- https://kotlinlang.org/docs/enum-classes.html#working-with-enum-constants. I found I needed these in the partiql-parser migration, particularly `.valueOf(<string>)` and `.values`. This PR adds those two functions to the interface and implements them for existing enum impls.
- No, on v1.
- Adds to the enum interface but on v1
and …

[v1] Add .valueOf and .values methods for enums

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/v1/AstEnum.java
partiql-ast/src/main/java/org/partiql/ast/v1/DataType.java
partiql-ast/src/main/java/org/partiql/ast/v1/DatetimeField.java
partiql-ast/src/main/java/org/partiql/ast/v1/FromType.java
partiql-ast/src/main/java/org/partiql/ast/v1/GroupByStrategy.java
partiql-ast/src/main/java/org/partiql/ast/v1/JoinType.java
partiql-ast/src/main/java/org/partiql/ast/v1/Nulls.java
partiql-ast/src/main/java/org/partiql/ast/v1/Order.java
partiql-ast/src/main/java/org/partiql/ast/v1/SetOpType.java
partiql-ast/src/main/java/org/partiql/ast/v1/SetQuantifier.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/Scope.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/SessionAttribute.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/TrimSpec.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/WindowFunction.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphDirection.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphRestrictor.java

- Adds a `.name` method to every `AstEnum`. This is part of normal enum classes but was missing from our `AstEnum` abstract class definition.
- Some other minor `AstEnum` implementation fixes
- No, on  v1
- Any backward-incompatible changes? **[No]**

[v1] Add name method to AstEnum

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/v1/Ast.kt
partiql-ast/src/main/java/org/partiql/ast/v1/FromJoin.java
partiql-ast/src/main/java/org/partiql/ast/v1/JoinType.java
partiql-eval/src/main/java/org/partiql/eval/compiler/PartiQLCompiler.java
partiql-parser/api/partiql-parser.api
partiql-parser/src/main/antlr/PartiQLParser.g4
partiql-parser/src/main/kotlin/org/partiql/parser/V1PartiQLParser.kt
partiql-parser/src/main/kotlin/org/partiql/parser/V1PartiQLParserBuilder.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/V1PartiQLParserDefault.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserBagOpTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserDDLTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserFunctionCallTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserOperatorTests.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserSessionAttributeTests.kt

- Migrates the partiql-parser to use the new AST
- On v1 branch
- Some changes but on v1 and hasn't been release yet

[v1] Migrate parser to new AST

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/v1/Ast.kt
partiql-ast/src/main/java/org/partiql/ast/v1/AstRewriter.kt
partiql-ast/src/main/java/org/partiql/ast/v1/AstVisitor.java
partiql-ast/src/main/java/org/partiql/ast/v1/ExcludeStep.java
partiql-ast/src/main/java/org/partiql/ast/v1/FromTableRef.java
partiql-ast/src/main/java/org/partiql/ast/v1/Select.java
partiql-ast/src/main/java/org/partiql/ast/v1/SelectItem.java
partiql-ast/src/main/java/org/partiql/ast/v1/Statement.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/Expr.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphLabel.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphPart.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphPattern.java
partiql-ast/src/main/java/org/partiql/ast/v1/graph/GraphSelector.java
partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToBinder.kt
partiql-ast/src/main/kotlin/org/partiql/ast/normalize/Normalize.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/helpers/ToBinder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/normalize/AstPass.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/normalize/Normalize.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/normalize/NormalizeFromSource.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/normalize/NormalizeGroupBy.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/V1NormalizeSelect.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/transforms/NormalizeSelectTest.kt

- Makes `AstVisitor` an abstract class with defaults
- Adds an `AstRewriter`
- Port the partiql-ast normalization passes to partiql-planner package and makes them `internal`
- Other partiql-planner `AstVisitor` impls are to be added in a subsequent PR
- No, on v1 branch. …

[v1] Adds AstVisitor and AstRewriter; port partiql-ast normalization passes to partiql-planner

---

partiql-ast/src/main/java/org/partiql/ast/v1/DataType.java
partiql-ast/src/main/java/org/partiql/ast/v1/expr/ExprIsType.java
partiql-cli/src/main/kotlin/org/partiql/cli/pipeline/Pipeline.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEvaluatorTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/V1PartiQLParserDefault.kt
partiql-planner/api/partiql-planner.api
partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlanner.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/SqlPlanner.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/V1AstToPlan.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/V1RelConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/V1RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/V1SubstitutionVisitor.kt
partiql-planner/src/test/kotlin/org/partiql/planner/PlanTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/PlannerPErrorReportingTests.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/exclude/SubsumptionTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PartiQLTyperTestBase.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/test/resources/outputs/basics/select.sql
test/partiql-randomized-tests/src/test/kotlin/org/partiql/lang/randomized/eval/Utils.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt

- Adds v1 AST -> plan conversion and hooks up w/ existing planner and eval code
- No, on v1
- Yes, but on v1

[v1] Add v1 ast -> plan conversion; hook up w/ existing code

---

CHANGELOG.md
README.md
gradle.properties
partiql-ast/build.gradle.kts
partiql-eval/build.gradle.kts

- Prepares v1.0.0-rc.2 release
- The draft release notes can be found [here](https://github.com/partiql/partiql-lang-kotlin/releases/tag/untagged-bc42b3ea53c8f1e74302). If you don't have access, I can add the content here (if desired).

Prepares v1.0.0-rc.2 release

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/AstNode.java
partiql-ast/src/main/java/org/partiql/ast/GroupBy.java
partiql-ast/src/main/java/org/partiql/ast/Let.java

- None
- Make `AstNode`'s `equals` and `hashCode` functions abstract such that the extending classes need to implement. This ensures an `AstNode` does NOT rely on the implicit equals function of `AstNode` which includes the tag
- See a similar pattern in Trino's AST -- https://github.com/prestodb/presto/blob/cd9f2dd43470b5298a9f9fb0572be7d2aa9bf74c/presto-parser/src/main/java/com/facebook/presto/sql/tree/Node.java#L45-L50
- Making the two functions abstract uncovered a couple classes that were missing `equals` and `hashcode` implementations
- No, on `v1` branch.
- Yes but not yet released. …

[v1] Make `AstNode` equals and hashcode abstract; add missing impls

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/AstVisitor.java
partiql-ast/src/main/java/org/partiql/ast/DataType.java
partiql-ast/src/main/java/org/partiql/ast/expr/ExprBoolTest.java
partiql-ast/src/main/java/org/partiql/ast/expr/ExprIsType.java
partiql-ast/src/main/java/org/partiql/ast/expr/ExprMissingPredicate.java
partiql-ast/src/main/java/org/partiql/ast/expr/ExprNullPredicate.java
partiql-ast/src/main/java/org/partiql/ast/expr/TruthValue.java
partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/main/kotlin/org/partiql/ast/Ast.kt
partiql-ast/src/main/kotlin/org/partiql/ast/AstRewriter.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEvaluatorTest.kt
partiql-parser/src/main/antlr/PartiQLParser.g4
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/Builtins.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnIsFalse.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnIsTrue.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnIsUnknown.kt

- Related PR -- https://github.com/partiql/partiql-lang-kotlin/pull/1520
- partiql-lang discussion on MISSING propagation and predicates -- https://github.com/orgs/partiql/discussions/93
- Adds AST, parser, evaluation support for SQL99's `IS [NOT] TRUE|FALSE|UNKNOWN` boolean test predicate
- AST: refactors `NULL` and `MISSING` out of `DataType` and creates dedicated null and missing predicate nodes
- No `v1` yet to be released.
- Removal of some `DataType` AST values and functions (for `NULL` and `MISSING`); `v1` not yet released so not an issue. …

[v1] Add IS [NOT] TRUE|FALSE|UNKNOWN; make IS NULL and IS MISSING separate AST nodes

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/DataType.java
partiql-ast/src/main/java/org/partiql/ast/DatetimeField.java
partiql-ast/src/main/java/org/partiql/ast/FromType.java
partiql-ast/src/main/java/org/partiql/ast/GroupByStrategy.java
partiql-ast/src/main/java/org/partiql/ast/JoinType.java
partiql-ast/src/main/java/org/partiql/ast/Literal.java
partiql-ast/src/main/java/org/partiql/ast/Nulls.java
partiql-ast/src/main/java/org/partiql/ast/Order.java
partiql-ast/src/main/java/org/partiql/ast/SetOpType.java
partiql-ast/src/main/java/org/partiql/ast/SetQuantifier.java
partiql-ast/src/main/java/org/partiql/ast/expr/Scope.java
partiql-ast/src/main/java/org/partiql/ast/expr/SessionAttribute.java
partiql-ast/src/main/java/org/partiql/ast/expr/TrimSpec.java
partiql-ast/src/main/java/org/partiql/ast/expr/TruthValue.java
partiql-ast/src/main/java/org/partiql/ast/expr/WindowFunction.java
partiql-ast/src/main/java/org/partiql/ast/graph/GraphDirection.java
partiql-ast/src/main/java/org/partiql/ast/graph/GraphRestrictor.java
partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt

- Removes the `UNKNOWN` AST enum variant
- Renumbers enums to start from 0. We can always add back `UNKNOWN` or some "OTHER" variant in the future.
- Renames `TruthValue.UNK` to `TruthValue.UNKOWN`

[v1] Remove UNKNOWN AST enum variant

---

partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/AstVisitor.java
partiql-ast/src/main/java/org/partiql/ast/ddl/CreateTable.java
partiql-ast/src/main/java/org/partiql/ast/ddl/Ddl.java
partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/main/kotlin/org/partiql/ast/AstRewriter.kt

- None
- In the AST, changes the DDL statements to directly extend `Statement`
- Removes the top-level DDL AST node that had extended `Statement`
- No, on unreleased v1.
- Yes, but v1 has not yet been released.

[v1] Remove top-level DDL node in AST

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PErrors.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/ExcludeUtils.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/TypeUtils.kt
partiql-planner/src/test/kotlin/org/partiql/planner/PlannerPErrorReportingTests.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/testFixtures/resources/catalogs/default/b/b/b_open.ion
partiql-planner/src/testFixtures/resources/inputs/schema_inferencer/exclude.sql
partiql-spi/api/partiql-spi.api
partiql-spi/src/main/java/org/partiql/spi/errors/PError.java
partiql-spi/src/test/kotlin/org/partiql/spi/errors/PErrorCodeTests.kt

- #1586
- Closes #1673
- Cherry-picks #1586 to `main` from `v0.14.9`, converts the use of StaticType to PType, and rebases.
- Since the table lookup and error handling have differed, there are 4 tests that have been updated. 2 in PlanTyperTestsPorted and PlannerPErrorReportingTests.

Ports v0.14.9 changes

---

partiql-eval/api/partiql-eval.api
partiql-eval/src/main/java/org/partiql/eval/Environment.java
partiql-eval/src/main/java/org/partiql/eval/Row.java
partiql-eval/src/main/java/org/partiql/eval/compiler/Match.java
partiql-eval/src/main/java/org/partiql/eval/compiler/PartiQLCompiler.java
partiql-eval/src/main/java/org/partiql/eval/compiler/Pattern.java
partiql-eval/src/main/kotlin/org/partiql/eval/internal/helpers/DatumArrayComparator.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/helpers/RecordUtility.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpAggregate.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpDistinct.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpExceptAll.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpExceptDistinct.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpExclude.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpIntersectAll.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpIntersectDistinct.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpUnionAll.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rel/RelOpUnionDistinct.kt

- Audits eval package
- Removes the public `getValues()` on `Row`.

Audits eval package

---

partiql-eval/src/test/kotlin/org/partiql/eval/internal/DataExceptionTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEvaluatorTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PlusTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/TestCases.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnDivide.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnMinus.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnModulo.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnPlus.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnTimes.kt
partiql-spi/src/main/kotlin/org/partiql/spi/internal/NumberExtensions.kt

- Closes https://github.com/partiql/partiql-lang-kotlin/issues/1697
- Changes integer types to error on overflow
- Changes integer types division and modulo by 0 to give an explicit data exception

[v1] Change integer types to error on overflow; give explicit data exception on div/mod by 0

---

partiql-plan/api/partiql-plan.api
partiql-plan/src/main/java/org/partiql/plan/rex/Rex.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexArray.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexBag.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexBase.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexCall.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexCase.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexCast.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexCoalesce.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexDispatch.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexError.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexLit.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexNullIf.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexPathIndex.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexPathKey.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexPathSymbol.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexPivot.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexSelect.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexSpread.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexStruct.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexSubquery.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexSubqueryComp.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexSubqueryIn.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexSubqueryTest.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexTable.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexType.java
partiql-plan/src/main/java/org/partiql/plan/rex/RexVar.java

- Audits the org.partiql.plan.rex package

Audits the org.partiql.plan.rex package

---

partiql-eval/src/test/kotlin/org/partiql/eval/internal/DataExceptionTest.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserOperatorTests.kt
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnNeg.kt
test/partiql-randomized-tests/src/test/kotlin/org/partiql/lang/randomized/eval/IntOverflowRandomizedTest.kt

- None, but similar to recent PRs
- https://github.com/partiql/partiql-lang-kotlin/pull/1715
- https://github.com/partiql/partiql-lang-kotlin/pull/1696
- https://github.com/partiql/partiql-lang-kotlin/pull/1716
- Similar to this old PR https://github.com/partiql/partiql-lang-kotlin/pull/1484
- Fixes unary minus w/ numeric literal parsing -- now will parse as a signed int literal rather than unary minus + unsigned int literal
- Previously, it would be impossible to parse `-2147483648` as an INT4
- Add data exception for unary negation overflow

[v1] Fix unary minus with numeric literal parsing; add data exception for unary neg overflow

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PartiQLTyperTestBase.kt
partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Catalog.kt
partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Path.kt
partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Session.kt

- As I was writing the "Implementing a Catalog" usage guide, I realized that the default implementations weren't what I wanted.
- This is a simple PR to change the default, and update the fnResolver to loop through the SQL Path when resolving a function.

Updates default impls of Catalog#getFunctions and Catalog#getAggregations

---

.github/workflows/conformance-report.yml

Adds back default name for conformance report upload.

[v1] Test conformance report upload

---

partiql-eval/src/main/kotlin/org/partiql/eval/internal/helpers/ValueUtility.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/CastTable.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathKey.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprPathSymbol.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprSpread.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprSubquery.kt
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprSubqueryRow.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEvaluatorTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/internal/TestCases.kt
partiql-spi/api/partiql-spi.api
partiql-spi/src/main/java/org/partiql/spi/value/Datum.java
partiql-spi/src/main/java/org/partiql/spi/value/DatumRow.java

Adds the ability to create rows.
Note: we already implicitly did this under the hood, but now we're making it apparent and more user-friendly. When writing the usage guide on how to create implementations of `Table`, I realized we couldn't outright create a ROW, even though we specified the type to be a ROW. So, adding this so that I can call the right API in the usage guide.

Adds `Datum#row()`

---

partiql-eval/src/test/kotlin/org/partiql/eval/internal/PartiQLEvaluatorTest.kt
partiql-plan/api/partiql-plan.api
partiql-plan/src/main/java/org/partiql/plan/rel/RelType.java
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/CompilerType.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/util/TypeUtils.kt
partiql-planner/src/test/kotlin/org/partiql/planner/PlannerPErrorReportingTests.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTest.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/ScopeTest.kt
partiql-spi/api/partiql-spi.api
partiql-spi/src/main/java/org/partiql/spi/types/PType.java
partiql-spi/src/main/java/org/partiql/spi/types/PTypeField.java
partiql-spi/src/main/java/org/partiql/spi/types/PTypeRow.java
partiql-spi/src/main/java/org/partiql/spi/value/Datum.java
partiql-spi/src/main/java/org/partiql/spi/value/DatumRow.java
partiql-spi/src/main/kotlin/org/partiql/spi/internal/SqlTypes.kt
partiql-spi/src/testFixtures/kotlin/org/partiql/types/FromStaticType.kt

- None
- Rename SPI's type Field to PTypeField

[v1] Rename SPI's type Field to PTypeField

---

CHANGELOG.md
examples/README.md
gradle.properties

- None
- Adds back `-SNAPSHOT` and upgrades patch version
- Adds unreleased section to changelog

Adds -SNAPSHOT; upgrade to v1.0.1

---

CHANGELOG.md
partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Session.kt

- N/A
- Return the properties that were set on the `Session` `Builder`.
- Updated Unreleased Section in CHANGELOG: YES
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? YES

Fix: Properly return properties from Session

---

partiql-eval/src/test/kotlin/org/partiql/eval/internal/LetTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt

- None
- In this pr, I added the implementation of LET clause. After merging this PR into the main branch, we suppose to support this kind of queries which have LET clause inside.
```
SELECT t.x, t.y, t.z * 2 AS double_z
FROM (
SELECT A AS x, B AS y, new_val AS z
FROM <<{ 'A': 1, 'B': 2, 'C': 3}>> 
LET B + C AS new_val
) AS t;
```
- The output wil be:
```
<<
'x':1,
'y':2,
'new_val':10
>>
```
- Updated Unreleased Section in CHANGELOG: 
- YES
- Any backward-incompatible changes? 
- NO
- Any new external dependencies? 
- NO
By submitting this pull …

Add implementation of LET clause and LetTests

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
gradle.properties

- Releases v1.2.0
- There are no breaking changes.
- Updates pull request template
- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md) and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **YES**

Releases v1.2.0

---

.github/workflows/build.yml

- https://github.com/actions/runner-images/issues/11101
- GH Actions recently removed the unbuntu runner we were previously using
- Updated Unreleased Section in CHANGELOG: **[NO]**: no public api changes
- Any backward-incompatible changes? **[NO]**: 
- Any new external dependencies? **[NO]**: no

ci: update GH Actions ubuntu runner

---

.github/workflows/gradle-wrapper-validation.yml
gradle.properties

- None
- Prep next snapshot version following the [v1.2.1 release](https://github.com/partiql/partiql-lang-kotlin/releases/tag/v1.2.1)
- Upgrade gradle wrapper validation to new GH action name and latest version. Previous version started failing more consistently.
- Updated Unreleased Section in CHANGELOG: **[NO]**: <Explain if NO> no changes
[csg]: …

chore: prep v1.2.2-SNAPSHOT + upgrade gradle wrapper validation action

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/InternalToPublicPlanTest.kt

- None
- Some more Rex nodes in the plan were getting mistyped as the outer context's type. See this comment from prior PR for the same issue https://github.com/partiql/partiql-lang-kotlin/pull/1749#discussion_r2074294215

fix: typing of Rex nodes in the plan

---

CHANGELOG.md
partiql-eval/src/test/kotlin/org/partiql/eval/CatalogTest.kt
partiql-eval/src/test/kotlin/org/partiql/eval/PErrorCollector.kt
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RelConverter.kt
partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Session.kt

- N/A
Previously, the list of aggregation functions known to planning was hard-coded. This PR looks up aggregation functions in the catalog, allowing planning to find both built-ins and catalog-defined functions.
- Updated Unreleased Section in CHANGELOG: YES
- Do your changes comply with the [contributing][cg] and [code style][csg] guidelines? YES

Enable definition of aggregation functions in the Catalog

---

CHANGELOG.md
partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt

- None
- Fixes the printing of AST literal string single quotes. Previously, `SqlDialect` would not properly escape single quotes.

fix: SqlDialect printing of AST literal string single quotes

---

CHANGELOG.md
partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt

- None
- Updates the `partiql-tests` git submodule
- LIMIT, OFFSET, and ORDER BY applied to the set op failed to parse. This PR fixes this parsing issue

fix: parsing of LIMIT, OFFSET, ORDER BY applied to a set op

---

CHANGELOG.md
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/CompilerType.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PTypeMetaInPlan.kt
partiql-spi/api/partiql-spi.api
partiql-spi/src/main/java/org/partiql/spi/types/PType.java
partiql-spi/src/test/kotlin/org/partiql/types/PTypeMetaTest.kt

- None
- Adds metas to `PType` denoting whether a default parameter was specified or not
- Adds a couple additional `PType` static factory functions to create a decimal and numeric with a precision and default scale
- Any backward-incompatible changes? **[YES]**: <Explain if YES>

feat: add metas to PType denoting a default parameter

---

CHANGELOG.md
partiql-cli/src/test/kotlin/org/partiql/cli/io/DatumWriterTextPrettyTests.kt
partiql-spi/src/main/java/org/partiql/spi/value/Datum.java

- fix Issue #1771 
- Fix the interval code for `INTERVAL` datum with `MINUTE_SECOND` case to display the interval correctly.

fix: correct qualifier for INTERVAL datum with MINUTE_SECOND (#1771)

---

CHANGELOG.md
partiql-ast/api/partiql-ast.api
partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
partiql-eval/src/main/java/org/partiql/eval/Environment.java
partiql-eval/src/main/kotlin/org/partiql/eval/internal/compiler/StandardCompiler.kt
partiql-plan/api/partiql-plan.api
partiql-plan/src/main/java/org/partiql/plan/OperatorVisitor.java
partiql-plan/src/main/java/org/partiql/plan/WithListElement.java
partiql-plan/src/main/java/org/partiql/plan/rel/RelWith.java
partiql-plan/src/main/kotlin/org/partiql/plan/Operators.kt
partiql-planner/api/partiql-planner.api
partiql-planner/src/main/kotlin/org/partiql/planner/builder/PartiQLPlannerBuilder.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/PlannerFlag.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/SqlPlanner.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTest.kt

- None
- Adds an experimental, limited `With` representation in the partiql-plan
- This is currently marked as experimental since we may choose a different modeling of CTEs in the future.
- Adds an experimental `With` configuration to the planner that controls whether `With` variable references are rewritten to their query representation.
- This PR preserves the original behavior to rewrite `With` variable references while also providing the option to not rewrite the var refs.
- Adds some missing implementations of `With` and `WithListElement` in `SqlDialect` and `AstVisitor`
- Do your changes …

feat: experimental WITH representation in the plan

---

CHANGELOG.md
partiql-eval/src/test/kotlin/org/partiql/eval/internal/IntervalParseSignedTests.kt
partiql-planner/src/main/kotlin/org/partiql/planner/internal/util/IntervalUtils.kt

-  Issue #1770 
- Refactor the parsing logic to support signed `INTERVAL` literals (with optional leading '+'/'-')
- Add test cases to verify it works

feat: signed `INTERVAL` literals support (#1770)

---

partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt

- None
- Followup to previous PR (https://github.com/partiql/partiql-lang-kotlin/pull/1774). Needed to also add the specified precision metas when converting `DataType`s in the AST -> Plan conversion
- Updated Unreleased Section in CHANGELOG: **[NO]**: <Explain if NO> already covered in previous CHANGELOG update
[csg]: https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_ST …

feat: add additional meta for unspecified INTERVAL precision and frac precision

---

CHANGELOG.md
partiql-cli/src/main/kotlin/org/partiql/cli/io/DatumWriterTextPretty.kt
partiql-cli/src/test/kotlin/org/partiql/cli/io/DatumWriterTextPrettyTests.kt

- [Closes/Related To] Issue #1788 
Previously, VARIANT types were displayed as byte array object references instead of their actual content. 
The fix converts the packed byte array to a UTF-8 string for display, allowing users to see the actual `Ion` content.
``` partiql
partiql ▶ select t.*, t.pdx.region from `{ pdx: { region: 'foo', segmentCount: 42 }, iad: { region: 'bar', segmentCount: 43 }}` as t;
=== RESULT ===
<<
{
'pdx': `[B@1000d54d`,
'region': `[B@3f4f5330`,
'iad': `[B@14b7786`
}
>>
OK!
```
``` partiql
partiql ▶ select t.*, t.pdx.region from `{ pdx: { region: 'foo', segmentCount: 42 }, iad: { region: 'bar', segmentCount: 43 }}` as t;
=== RESULT ===
<<
{
'pdx': `{region:foo,segmentCount:42}`,
'region': `foo`,
'iad': `{region:bar,segmentCount:43}`
}
>>
OK!
```
- Updated Unreleased …

fix: display of `Ion` in PartiQL CLI output

---

CHANGELOG.md
partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCall.kt

- [Closes/Related To] Issue #1800 
- Fix the bug mentioned in the above issue
```
partiql ▶ null OVERLAPS missing;
w: [semantic] Expression always returns missing
=== RESULT ===
missing
OK!
partiql ▶ missing OVERLAPS null;
w: [semantic] Expression always returns missing
=== RESULT ===
missing
OK!
```
[csg]: …

fix: missing propagation behavior in functions args

---

docs/upgrades/v0.14-to-v1-upgrade/examples/src/test/kotlin/examples/ParserChanges.kt
docs/upgrades/v0.14-to-v1-upgrade/upgraded-examples/src/test/kotlin/examples/ParserChanges.kt

- add migration example for partiQL parser
- Updated Unreleased Section in CHANGELOG: No, No feature released/change
- Do your changes comply with the [contributing][cg] and [code style][csg] guidelines? YES

add migration example for partiQL parser

---

CHANGELOG.md
partiql-cli/src/main/kotlin/org/partiql/cli/pipeline/ErrorMessageFormatter.kt

- [Closes/Related To] Issue #1733 
- < Explain >
- Do your changes comply with the [contributing][cg] and [code style][csg] guidelines? Yes

Remove unicode non-character in the CLI error report

---

partiql-spi/src/test/kotlin/org/partiql/value/TimestampTest.kt

- [Closes] Issue #1812
- Migrate tests in `TimestampTest.kt` from using `PartiQLValue` to `Datum`
- Verify that Datum timestamp factory methods correctly preserve fractional seconds without rounding, handle different timezone representations and compare timestamps properly using the comparator.
- Update the rounding related tests since `Datum.timestamp()` will preserve fractional nanos, preserve all the other tests using `PartiQLValue` previously
- Updated Unreleased Section in CHANGELOG: **[NO]**: No change in public interface
By submitting this pull request, I confirm that my contribution is made under …

migrate: timestamp tests from `PartiQLValue` to `Datum`

---

CHANGELOG.md
partiql-spi/src/main/java/org/partiql/spi/value/DatumComparator.java
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/io/DatumIonReader.kt
test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/util/DatumUtil.kt

- Closes Issue #1783 
- Define `Ion` representation for `INTERVAL` in conformance tests
- Add support for `INTERVAL` in `partiql-tests-runner`

add: `Ion` representation for `INTERVAL` in conformance tests & support `INTERVAL` in partiql-tests-runner

---

partiql-ast/src/main/java/org/partiql/ast/IntervalQualifier.java

- Closes #1820 
- Set the maximum precision as 9 for PartiQL `INTERVAL` in the AST
```
partiql ▶ INTERVAL '999999999-11' YEAR(9) to MONTH;
=== RESULT ===
INTERVAL '999999999-11' YEAR (9) TO MONTH
OK!
partiql ▶ INTERVAL '99:59.123456789' MINUTE(2) TO SECOND(9);
=== RESULT ===
INTERVAL '99:59.123456789' MINUTE (2) TO SECOND (9)
OK!
```
[csg]: …

Fix `INTERVAL` precision containing a range of fields

---

docs/upgrades/v0.14-to-v1-upgrade/examples/src/test/kotlin/examples/ErrorHandlingChanges.kt
docs/upgrades/v0.14-to-v1-upgrade/upgraded-examples/src/test/kotlin/examples/ErrorHandlingChanges.kt

- Add exception handling migration guide from v0.14.9 to v1
Updated Unreleased Section in CHANGELOG: No, No feature released/change
Any backward-incompatible changes? NO
Any new external dependencies? NO
Do your changes comply with the [contributing](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md) and [code style](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md) guidelines? YES

Add exception handling migration guide from v0.14.9 to v1

---

CHANGELOG.md
partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnLower.kt

- None
- Fix returned datum for calling `LOWER` on a clob. Previously was returning a string datum when it should have been a clob.
- Behavior now follows what we do for `UPPER`.

fix: LOWER(clob) datum return type
