partiql/partiql-lang-kotlin

- docs/user/COOKBOOK.md
https://github.com/partiql/partiql-lang-kotlin/issues/99
Update sample code to not use `EvaluatingCompiler` directly.
> (Docs) Update cookbook examples to use CompilerPipeline (#99)

- lang/src/org/partiql/lang/errors/ErrorCode.kt
- lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
- lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
- lang/test/org/partiql/lang/eval/builtins/ConcatEvaluationTest.kt
- lang/test/org/partiql/lang/eval/builtins/SizeExprFunctionTest.kt
- testscript/pts/test-scripts/operators/concat.sqlts
Continues the work from https://github.com/partiql/partiql-lang-kotlin/pull/113 addressing PR comments 
> assign error code when concat fails

- lang/build.gradle
> Move to new sonatype URL

- README.md
> (Docs) Adds badges on README for Travid & Codecov

- build.gradle
Prepare version 0.1.1 release for PartiQL.
> (Release) Prepare v0.1.1 for release

- build.gradle
- cli/build.gradle
- pts/build.gradle
(Build) removes version assignments in subproject
> (Build) removes version assignments in subproject

- README.md
> Update package version in readme

- cli/README.md
> Fixes #155

- build.gradle
> Set version to 0.1.3-SNAPSHOT in build.gradle

- docs/user/CLI.md
- examples/src/java/org/partiql/examples/CSVJavaExample.java
- examples/src/java/org/partiql/examples/S3Example.java
- testscript/Readme.md
- testscript/src/org/partiql/testscript/compiler/Compiler.kt
N/A
Fixed a few spellings ('bellow' to 'below') and grammar in the READMEs.
> Fix a few spelling and grammar issues.

- docs/user/CLI.md
Include additional detail, commands and input files to make it easier for new users to follow along.
*Testing*
Tested updated instructions using REPL on local environment.
> Include additional detail, commands and input files to make it easier for new users to follow along.

- lang/src/org/partiql/lang/util/ExprValueFormatter.kt
- lang/src/org/partiql/lang/util/IonValueExtensions.kt
- lang/src/org/partiql/lang/util/NumberExtensions.kt
- lang/test/org/partiql/lang/util/ConfigurableExprValueFormatterTest.kt
> Preserve negative zero from both decimal and ion literals

- lang/src/org/partiql/lang/errors/ErrorCode.kt
- lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
- lang/test/org/partiql/lang/eval/EvaluatingCompilerExceptionsTest.kt
> Error code for / and % by zero

- lang/src/org/partiql/lang/eval/NaturalExprValueComparators.kt
- lang/src/org/partiql/lang/util/NumberExtensions.kt
- lang/test/org/partiql/lang/eval/NaturalExprValueComparatorsTest.kt
Add equality tests for equivalent values and null values
Resolves #165 
> fix float negative zero equality

- README.md
- build.gradle
- lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
- lang/test/org/partiql/lang/eval/EvaluatingCompilerTests.kt
- lang/test/org/partiql/lang/eval/EvaluatorTestBase.kt
* Cherry picks https://github.com/partiql/partiql-lang-kotlin/commit/c1ed67e6ab919799978d0dfb297b6cc034b87e3d 
* Adds missing helper functions in EvaluatorTestBase
* Update version numbers in README and build.gradle
> Prepare release v0.2.1

- docs/dev/CODE-STYLE.md
- docs/dev/intellij_code_style.xml
These files were a little out of date.  Updating with what we're doing today.
> Update IntelliJ code style and CODE-STYLE.md

- cli/src/org/partiql/cli/Repl.kt
- cli/test/org/partiql/cli/ReplTest.kt
- docs/user/CLI.md
- docs/user/GettingStarted.md
… performance measure
Issue #, ION-1184
> Removed the time taken in (ms) from REPL

- cli/src/org/partiql/cli/Repl.kt
> Remove unused variable

- lang/src/org/partiql/lang/eval/CompileOptions.kt
- lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt
- lang/src/org/partiql/lang/eval/Thunk.kt
- lang/test/org/partiql/lang/eval/io/CustomExceptionHandlerTest.kt
Added ThunkOptions to configure exception handler which can be used instead of default handler which throws EvaluationException.
Added a class ThunkFactory which takes ThunkOptions as an argument. All the Thunk functions are moved to this class.
Added ThunkOptions property to CompileOptions.
Added a unit test to test the custom exception handler.
> Configurable exception handling

- lang/src/org/partiql/lang/syntax/LexerConstants.kt
- lang/src/org/partiql/lang/syntax/SqlParser.kt
- lang/test/org/partiql/lang/syntax/SqlParserTest.kt
Issue #224 
Changed the precedence value for SELECT(6) and set it to be higher than UNION(5).
> Fixed UNION precedence in Parser

- lang/resources/org/partiql/type-domains/partiql.ion
Initial changes to PIG-domain to add LET (#179)
> LET PIG-domain changes (from_let)

- docs/dev/CODE-STYLE.md
> Update CODE-STYLE.md with guidance regarding !! operator

- README.md
- build.gradle
> Minor version bump to `0.2.3-SNAPSHOT` and update README.md version.

- docs/dev/CODE-STYLE.md
I'm seeing this come up very often in when I do code reviews.  It needs to be adopted into our official code style.
> Add guidance about mutable data structures

- README.md
- build.gradle
> New release v0.2.3

- build.gradle
> prepare 0.2.4-SNAPSHOT

- README.md
- build.gradle
> New release v0.2.5

- build.gradle
Prepares the PartiQL v0.2.6-SNAPSHOT
> Prepare 0.2.6-SNAPSHOT

- README.md
- build.gradle
> New release v0.2.6

- build.gradle
> Prepare 0.2.7-SNAPSHOT

- lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt
Just like the title says: cherry-picks #405, with minor modifications needed for the older deserializer class.
When this is merged, we can release the `v0.1.6` hot fix branch.
> Cherry-picks #405 to v0.1.6 branch

- README.md
- build.gradle
> Change version number to v0.1.6

- README.md
- build.gradle
> Bump major version, update preferred version in README.md

- build.gradle
Sets version to `v0.3.1-SNAPSHOT`
> Minor version bump, restore -SNAPSHOT after release

- README.md
- build.gradle
> New release v0.3.1

- build.gradle
> Prepare 0.3.2-SNAPSHOT

- lang/src/org/partiql/lang/eval/ExprValueExtensions.kt
- lang/src/org/partiql/lang/eval/time/TimeExtensions.kt
- lang/src/org/partiql/lang/syntax/SqlParser.kt
- lang/test/org/partiql/lang/eval/EvaluatingCompilerCastTest.kt
- lang/test/org/partiql/lang/eval/EvaluatingCompilerDateTimeTests.kt
- lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt
> Changes default value of the default timezone offset to UTC.

- README.md
- build.gradle
Removes `-SNAPSHOT` and updates version in `README.md`
> New release v0.3.2

- build.gradle
> Prepare v0.3.3 release

- README.md
- build.gradle
Also update `README.md` to have current maven release.
> Minor version bump to v0.3.4-SNAPSHOT

- README.md
- build.gradle
> New release v0.3.4

- README.md
- build.gradle
Update `build.gradle` and `README.md` with v0.2.7
> New release v0.2.7

- README.md
- build.gradle
Update `build.gradle` and `README.md` with v0.1.7
> New release v0.1.7

- cli/src/org/partiql/cli/functions/ReadFile.kt
- cli/test/org/partiql/cli/functions/ReadFileTest.kt
- docs/user/CLI.md
*Issue #491*
Added more test cases to read different CSV formats.
> More test cases to read CSV formats

- build.gradle
Prepare v0.5.0 release of PartiQL.
> [release] Prepare v0.5.0 release

- lang/src/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
- lang/test/org/partiql/lang/prettyprint/QueryPrettyPrinterTest.kt
Implemented PartiQL query formatter. For now, only the following scenarios for nested queries are supported
* SFW/CASE in SFW
* SFW/CASE in DML
The following scenarios for nested queries are not supported:
* SFW/CASE in CASE
* SFW/CASE in function call
* SFW/CASE in container type
* SFW/CASE in operators
Thus, in these cases, nested SFW/CASE queries are just printed as one line string, as the test cases below TODO comment in the test file shown.
> Implemented a basic PartiQL query formmater

- build.gradle
Prepare v0.6.0 release of PartiQL.
> [release] Prepare v0.6.0 release

- build.gradle
> Prepare v0.6.1-SNAPSHOT

- cli/src/org/partiql/cli/Repl.kt
- cli/test/org/partiql/cli/ReplTest.kt
- docs/user/CLI.md
- lang/src/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
Integrate pretty printer tools with REPL. See the changes in `CLI.md` on how to use AST and query pretty printer.  
Note that due to https://github.com/partiql/partiql-lang-kotlin/issues/266, test cases are not added or modified in REPL test file.
> Integrate pretty printer

- lang/test/org/partiql/lang/eval/EvaluatorStaticTypeTests.kt
- lang/test/org/partiql/lang/eval/EvaluatorTestSuite.kt
- lang/test/org/partiql/lang/eval/EvaluatorTests.kt
- lang/test/org/partiql/lang/eval/evaluatortestframework/EvaluatorErrorTestCase.kt
*Issue #, if available:* https://github.com/partiql/partiql-lang-kotlin/issues/169
In checking some old bugs, I found that the desired behavior is implemented. This PR fixes the relevant test cases.
> Fixes tests related to Issue #169

- cli/src/org/partiql/shell/ShellHighlighter.kt
> Fixes syntax highlighting for !add_to_global_env

- cli/src/org/partiql/cli/main.kt
- cli/test/org/partiql/cli/CliTest.kt
- Closes #566
- Closes #544
- Adds 3 useful CLI flags to the CLI options
> Adds other compile options to the CLI

- build.gradle
*Issue #, if available:* #648 
Set the next version for development.
> Set next dev version

- docs/user/numericTypeAndArithmeticOperation.md
N/A
Add document on Number type and arithmetic operation
No.
No.
```
For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in 
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base.
```
*Does your PR introduce a new external dependency? (y/n), if yes, please explain the reason. In addition, please
also …
> doc on number type and arithmetic

- lang/src/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
Refactored some code in `StaticTypeInferenceVisitorTransform.kt` file:
1. Formatted the file 
2. Changed variable name from `nary` to `processedNode`
3. Changed `if` statement to `when` statement. 
This PR does not have any changes behavior of type inferencer.
> Refactor STIVT Code Style

- lib/partiql-isl/build.gradle
This PR aims to update to and release partiql ISL 0.2.1
> Release ISL 0.2.1

- CHANGELOG.md
- cli/src/org/partiql/shell/CompleterDefault.kt
- cli/src/org/partiql/shell/Shell.kt
- lang/src/org/partiql/lang/syntax/PartiQLParser.kt
- None.
- Adds simple auto-completion to the CLI
- Simply hit TAB
- Needs to be merged after #854 as this branch is a branch off of those changes.
https://user-images.githubusercontent.com/40360967/198119656-06a86301-3b0b-464f-a6f8-5f96f3a3a805.mov
> Adds simple auto-completion to the CLI

- build.gradle
- lib/partiql-isl/build.gradle
> Bump versions up towards next release.

- lang/src/org/partiql/lang/planner/PartiQLPlanner.kt
Continued from https://github.com/partiql/partiql-lang-kotlin/pull/783, I guess I missed to change the default option in `PartiQLParser`.
> Changed default `TypedOpBehvaior` in `PartiQLParser` 

- docs/_Sidebar.md
- docs/documentation/Window Functions.md
- N/A
- Add a documentation explaining how `Lag` and `Lead` works
- No
- No
- No.
> add window function doc

- cli/src/main/kotlin/org/partiql/shell/Shell.kt
- Closes #913 
- Re-adds the !!
> Re-adds the CLI AST pretty-printer for the EvaluatingCompiler

- buildSrc/src/main/kotlin/partiql.versions.kt
N/A
Upgrades PIG to 0.6.1
NO
NO
> Updates PIG to 0.6.1

- buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt
> Updates maven contact email to partiql-dev@amazon.com

- CHANGELOG.md
- examples/src/main/java/org/partiql/examples/S3JavaExample.java
- lang/src/main/kotlin/org/partiql/lang/eval/ExprValue.kt
- lang/src/main/kotlin/org/partiql/lang/eval/ExprValueExtensions.kt
- lang/src/main/kotlin/org/partiql/lang/eval/ExprValueFactory.kt
- lang/src/main/kotlin/org/partiql/lang/eval/IonStructBindings.kt
- lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerSelectStarTests.kt
- test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/TestRunner.kt
- Migrate `ExprValue.toIonValue()` from `ExprValue.kt` to `ExprValueExtension.kt` 
- Change `IonValue.toExprValue()` to `ExprValue.of(value: IonValue)`
> Change `IonValue` & `ExprValue` conversion API

- gradle.properties
> Prepares 0.9.1-SNAPSHOT

- partiql-lang/src/jmh/kotlin/org/partiql/jmh/benchmarks/MultipleLikeBenchmark.kt
- partiql-lang/src/jmh/kotlin/org/partiql/jmh/benchmarks/ParserBenchmark.kt
> Removes ionSystem from parser in JMH benchmarks

- CHANGELOG.md
- README.md
- gradle.properties
- N/A
- prepare release v0.9.3
- Yes.
- No
-  No. 
> prepare release v0.9.3

- gradle.properties
- Set v0.10.0-SNAPSHOT as the next dev. version
- N/A.
- No
- No
> Set v0.10.0-SNAPSHOT as the next dev. version

- CHANGELOG.md
- README.md
- gradle.properties
- None
- Prepares v0.10.0 release
- Copied and pasted the CHANGELOG for v0.9.3 and updated v0.9.4 as well.
- Created #1067 to track migration guide release
- This is a release
> Prepares v0.10.0 release

- CHANGELOG.md
- gradle.properties
- None
- Updates development version
- Updates CHANGELOG
> Initializes 1.0 Development Branch

- CHANGELOG.md
- README.md
- gradle.properties
- None
- Releases v0.11.0
- Any backward-incompatible changes? **YES**
- No code changes, but releasing breaking changes.
> Releases v0.11.0

- gradle.properties
- None
- Sets development version to v0.11.1-SNAPSHOT
> Sets development version to v0.11.1-SNAPSHOT

- CHANGELOG.md
- README.md
- buildSrc/src/main/kotlin/org/partiql/gradle/plugin/publish/PublishPlugin.kt
- lib/isl/build.gradle.kts
- partiql-lang/build.gradle.kts
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/mappers/IonSchemaMapper.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/PlannerSession.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/PlanTyper.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/ReferenceResolver.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/types/StaticTypeUtils.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/types/StaticTypeTests.kt
- partiql-lang/src/test/resources/catalogs/b/b/d.json
- partiql-spi/src/main/kotlin/org/partiql/spi/BindingCase.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/BindingName.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/BindingPath.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/connector/ConnectorObject.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/connector/ConnectorObjectHandle.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/connector/Constants.kt
- partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt
- plugins/partiql-mockdb/src/main/kotlin/org/partiql/plugins/mockdb/LocalConnectorObject.kt
- plugins/partiql-mockdb/src/test/kotlin/org/partiql/plugins/mockdb/LocalConnectorMetadataTests.kt
- None
- Merges main into V1-DEV. See commits. I wanted to do this so we can have Explicit API Mode in V1-DEV.
- The only conflict was the dev version
> Merges main to V1-DEV

- CHANGELOG.md
- README.md
- gradle.properties
Setting up for post-0.12.0 contributions
> Setting up for post-0.12.0 contributions

- CHANGELOG.md
- buildSrc/src/main/kotlin/partiql.versions.kt
> Upgrades ion-java to 1.10.2

- CHANGELOG.md
- partiql-lang/src/main/kotlin/org/partiql/lang/CompilerPipeline.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/ast/passes/inference/StaticTypeInferencer.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerBuilder.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/compiler/PartiQLCompilerDefault.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/EvaluatingCompiler.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/ExprFunction.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransform.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencer.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/planner/transforms/plan/PlanTyper.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/types/FunctionSignature.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/eval/visitors/StaticTypeInferenceVisitorTransformTest.kt
- [Closes/Related To] Issue @1149
Adds @Deprecated notices and give a replacement API to use in place of the deprecated methods.
- Updated Unreleased Section in CHANGELOG: [YES/NO]
YES
NO
NO
YES
> Add @deprecate

- partiql-types/src/main/kotlin/org/partiql/value/datetime/DateTime.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/DateTimeComparator.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/DateTimePrecisionChanger.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/DateTimeValue.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/LocalTimeHighPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/LocalTimeLowPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/LocalTimestampHighPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/LocalTimestampLowPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/OffsetTimeHighPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/OffsetTimeLowPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/OffsetTimestampHighPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/OffsetTimestampLowPrecision.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/SqlDate.kt
- partiql-types/src/main/kotlin/org/partiql/value/datetime/impl/Utils.kt
- Adding Kdocs to timestamp.
- Minor changes to timestamp data model. 
- No. Minor changes on unreleased feature. 
-  No
- No. 
- Yes. 
> Kdoc and minor changes to timestamp data model. 

- CHANGELOG.md
- README.md
- gradle.properties
- Release of v0.12.1
- Yes. 
-  No.
-  No. 
- Yes. 
> Prepares v0.12.1 release

- CHANGELOG.md
- README.md
- gradle.properties
- Merged after PR #1201.
- Prepares for release v0.13.0
- Yes. 
-  Yes. See changelog. 
-  No. 
- Yes. 
> Prepares v0.13.0 release

- gradle.properties
- [Closes/Related To] Issue N/A
- Setting up for post-0.13.0 contributions
- No
-  No
- No
- Yes. 
> Setting up for post-0.13.0 contributions

- CHANGELOG.md
- gradle.properties
Prepare v0.13.2-SNAPSHOT following v0.13.1 release.
- Updated Unreleased Section in CHANGELOG: No, simple update to version after v0.13.1 release.
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? No
> Prepare v0.13.2-SNAPSHOT

- lib/partiql-byob/src/main/kotlin/org/partiql/transpiler/cli/Shell.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/sql/RelToSql.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/sql/RexToSql.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/targets/redshift/RedshiftTarget.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/targets/trino/TrinoTarget.kt
- lib/partiql-transpiler/src/test/resources/cases/tests_00.ion
- lib/partiql-transpiler/src/test/resources/targets/partiql/partiql_results_00.ion
- lib/partiql-transpiler/src/test/resources/targets/redshift/redshift_results_00.ion
- lib/partiql-transpiler/src/test/resources/targets/trino/trino_results_00.ion
- partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt
- partiql-plan/src/main/resources/partiql_plan_0_1.ion
- partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RelConverter.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
- partiql-planner/src/testFixtures/kotlin/org/partiql/planner/test/Parsing.kt
- partiql-planner/src/testFixtures/resources/catalogs/default/pql/item.ion
- partiql-planner/src/testFixtures/resources/tests/suite_00.ion
- partiql-types/src/main/kotlin/org/partiql/types/StaticType.kt
- None
- Adds preliminary support for JOINs.
- We need to add support for `SELECT *` so that we can perform more comprehensive checks. Will add to follow-up PR.
- Not `main`.
- All changes to `plan_0_1` haven't been released yet.
> Adds preliminary support for JOINs.

- CHANGELOG.md
- partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToLegacyAst.kt
- partiql-ast/src/main/pig/partiql.ion
- partiql-ast/src/main/resources/partiql_ast.ion
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/EvaluatingCompiler.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/eval/visitors/SubqueryCoercionVisitorTransform.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/prettyprint/ASTPrettyPrinter.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinter.kt
- partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/eval/EvaluatingCompilerIntTest.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/prettyprint/ASTPrettyPrinterTest.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/prettyprint/QueryPrettyPrinterTest.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserPrecedenceTest.kt
- partiql-lang/src/test/kotlin/org/partiql/lang/syntax/PartiQLParserTest.kt
- partiql-parser/src/main/antlr/PartiQL.g4
- partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt
- [Closes/Related To] Issue #1221 
- Parsing and evaluation of Bitwise and operator. 
- Yes. 
- No. New feature. 
-  No. 
- Yes. 
> bitwise and parse/eval

- buildSrc/src/main/kotlin/partiql.versions.kt
- lib/partiql-byob/src/main/kotlin/org/partiql/transpiler/cli/Shell.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/sql/SqlCalls.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/targets/redshift/RedshiftCalls.kt
- lib/partiql-transpiler/src/main/kotlin/org/partiql/transpiler/targets/redshift/RedshiftTarget.kt
- lib/partiql-transpiler/src/test/resources/cases/tests_00.ion
- lib/partiql-transpiler/src/test/resources/targets/partiql/partiql_results_00.ion
- lib/partiql-transpiler/src/test/resources/targets/redshift/redshift_results_00.ion
- lib/partiql-transpiler/src/test/resources/targets/trino/trino_results_00.ion
- partiql-ast/src/main/kotlin/org/partiql/ast/helpers/ToBinder.kt
- partiql-ast/src/main/resources/partiql_ast.ion
- partiql-parser/src/main/antlr/PartiQL.g4
- partiql-parser/src/main/kotlin/org/partiql/parser/impl/PartiQLParserDefault.kt
- partiql-parser/src/test/kotlin/org/partiql/parser/impl/PartiQLParserSessionAttributeTests.kt
- partiql-plan/src/main/resources/partiql_plan_0_1.ion
- partiql-planner/src/main/kotlin/org/partiql/planner/Header.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
Adds session attributes to the transpiler rules.
> Adds CURRENT_USER and CURRENT_DATE to transpiler

- partiql-lang/src/test/kotlin/org/partiql/lang/planner/transforms/PartiQLSchemaInferencerTests.kt
- partiql-plan/src/main/resources/partiql_plan_0_1.ion
- partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/typer/PlanTyper.kt
- None
- Adds `default` attribute.
- This simplifies things slightly during typing as well as transpilation.
- Adds tests
> Modifies definition of CASE_WHEN in Plan

- partiql-planner/src/main/kotlin/org/partiql/planner/transforms/RexConverter.kt
> fix type mismatch

- partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
- partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
This adds quoting of subqueries via the pretty-printer. It also exposes a place to control expression quoting behavior.
Yes
> Adds quoting of subqueries to pretty-printer

- partiql-ast/src/main/kotlin/org/partiql/ast/sql/SqlDialect.kt
- N/A
- Remove unnecessary !! because smart casts work with JvmField
- Fixes aggregation printing bug
No
No
No
Yes
> Clean up SqlDialect

- CHANGELOG.md
- README.md
- gradle.properties
- Prepare v0.14.0 release
- Yes. 
- Release commit. This release contains backward-incompatible change. See changelog.  
- No. 
Yes. 
> Prepare v0.14.0 release

- partiql-planner/src/main/kotlin/org/partiql/planner/internal/Env.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
- partiql-planner/src/test/kotlin/org/partiql/planner/PlanTest.kt
- partiql-planner/src/test/kotlin/org/partiql/planner/util/PlanNodeEquivalentVisitor.kt
- partiql-planner/src/test/resources/outputs/basics/select.sql
- Fixed Variable Resolution. 
- Add a text based plan testing method to prevent unintentional break of the plan. 
- Yes. 
-  No. 
-  No
- Yes. 
> Fixes variable resolution

- partiql-planner/src/main/kotlin/org/partiql/planner/PartiQLPlannerBuilder.kt
https://github.com/partiql/partiql-lang-kotlin/pull/1327/files#diff-99c98827ce0e59b6783a1dccc5a19ee9f539ac14e4bb5aea954516b7ec2f454bR51
Updated to 1.0 rather than 15.0.0
No
No
No
Yes
> Updates planner builder deprecation message

- CHANGELOG.md
- README.md
- gradle.properties
- None
- **IMPORTANT**: Please review both commits. I will tag the first commit with `v0.14.1`.
> Releases v0.14.1 and prepares development

- partiql-spi/src/main/kotlin/org/partiql/spi/BindingPath.kt
- plugins/partiql-local/build.gradle.kts
- plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalCatalog.kt
- plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalConnector.kt
- plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalObject.kt
- plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalPlugin.kt
- plugins/partiql-local/src/main/kotlin/org/partiql/plugins/local/LocalSchema.kt
- plugins/partiql-local/src/test/kotlin/org/partiql/plugins/local/LocalConnectorMetadataTests.kt
- plugins/partiql-memory/build.gradle.kts
- plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryCatalog.kt
- plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryCatalogBuilder.kt
- plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryConnector.kt
- plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryObject.kt
- plugins/partiql-memory/src/main/kotlin/org/partiql/plugins/memory/MemoryPlugin.kt
- plugins/partiql-memory/src/test/kotlin/org/partiql/plugins/memory/MemoryCatalogTest.kt
Updates our internal plugins to the latest SPI interfaces. Note that these are not functional yet because function resolution is not complete. This will also need to include the latest changes from partiql-eval to included bindings in the memory plugin.
No
No
No
Yes
> Updates plugins to latest SPI interfaces

- CHANGELOG.md
- gradle.properties
- Prepares v0.14.3-SNAPSHOT following recent v0.14.2 release
> Prepares v0.14.3-SNAPSHOT

- CHANGELOG.md
- README.md
- gradle.properties
- None
- Releases v0.14.3 and prepares development
- NOTE: See diff for both commits. I'll cut the release using the first commit.
> Releases v0.14.3 and prepares development

- CHANGELOG.md
- gradle.properties
- None
- Releases `1.0.0-perf.1` (tag `v1.0.0-perf.1`) and sets up next development version.
- **SEE BOTH COMMITS**. The first will be used to release the pre-release.
- We follow SemVer to denote a pre-release:
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, …
> Releases v1.0.0-perf.1

- gradle.properties
Prepares v0.14.5-SNAPSHOT version following v0.14.4 release.
- No changes needed.
> Prepare v0.14.5-SNAPSHOT

- CHANGELOG.md
Updates the CHANGELOG for 
- https://github.com/partiql/partiql-lang-kotlin/issues/1390
- https://github.com/partiql/partiql-lang-kotlin/pull/1391
> Updates CHANGELOG for CASE-WHEN

- CHANGELOG.md
- README.md
- gradle.properties
Prepares 0.14.5 patch release.
Yes
No, patch release.
No
Yes
> Prepares 0.14.5 release

- CHANGELOG.md
- gradle.properties
Adds -SNAPSHOT to gradle.properties and updates CHANGELOG with unreleased section.
Yes
No
No
Yes
> Prepares v0.14.6 snapshot

- partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
- partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCoalesce.kt
- partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprNullIf.kt
- None
- Adds support for NULLIF and COALESCE
- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md) and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **YES**
> Adds support for NULLIF and COALESCE

- partiql-eval/src/main/kotlin/org/partiql/eval/internal/Compiler.kt
- None
- Adds support for catching type check exceptions in FILTER when permissive
> Adds support for catching type check exceptions in FILTER when permissive

- partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/PlanTyperTestsPorted.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/connector/sql/builtins/AggAvg.kt
- None
- Updates AVG to return DECIMAL. Increases conformance by 4 tests.
- Any backward-incompatible changes? **YES** -- updates AVG to return DECIMAL
> Updates AVG to return DECIMAL

- test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/executor/EvalExecutor.kt
- test/partiql-tests-runner/src/test/kotlin/org/partiql/runner/test/TestRunner.kt
- Updates conformance tests to latest commit.
- Enables easier conformance debugging by maintaining the stack trace and giving better error messages
> Updates conformance tests and enables easier conformance debugging

- partiql-lang/src/main/kotlin/org/partiql/lang/syntax/impl/PartiQLPigVisitor.kt
- partiql-parser/build.gradle.kts
- partiql-parser/src/main/antlr/PartiQLParser.g4
- partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
#1472 
Details in 1472
No
No
No
Yes
> Fixes ANTLR parser grammar and renames parser g4 file

- .github/workflows/conformance-report.yml
- [Closes/Related To] Issue None
- Check to see if updating conformance GH action gradle version fixes the conformance test runner failures
- No changes to API
> Update conformance GH action gradle version

- partiql-types/src/test/kotlin/org/partiql/value/io/PartiQLValueTextWriterTest.kt
- None
- Forgot to commit a few tests from #1492.
- Just some more tests
> Add some tests missing from #1492

- partiql-eval/src/main/java/org/partiql/eval/value/DatumTimestamp.java
- Fixes timestamp bug by using the correct PType.
> Fixes timestamp bug

- partiql-planner/api/partiql-planner.api
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Catalog.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Catalogs.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Function.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Identifier.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Name.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Namespace.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Path.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Session.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/catalog/Table.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/internal/SqlTypes.kt
#1497 
#1496 
This PR merges the catalog interfaces into the v1 branch.
- Updated Unreleased Section in CHANGELOG: **No**
- Any backward-incompatible changes? **No**
- Any new external dependencies? **No**
and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **Yes**
> Merges v1-catalog into v1

- partiql-eval/src/main/kotlin/org/partiql/eval/internal/helpers/ValueUtility.kt
- partiql-eval/src/main/kotlin/org/partiql/eval/internal/operator/rex/ExprCase.kt
- Small bug fixes that didn't make it into the original missing value as function arguments PR
> Fixes small bugs

- CHANGELOG.md
- README.md
- gradle.properties
- Updates version for v0.14.9 release
> Releases v0.14.9

- partiql-lang/build.gradle.kts
- settings.gradle.kts
Adds a convenience single import package `partiql-lang`.
> Adds the partiql-lang import-only package

- partiql-spi/api/partiql-spi.api
- partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Catalogs.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/catalog/Session.kt
- plugins/partiql-memory/src/test/kotlin/org/partiql/plugins/memory/MemoryConnectorTest.kt
> Adds an empty catalog implementation

- gradle.properties
- partiql-ast/api/partiql-ast.api
- partiql-ast/src/main/java/org/partiql/ast/AstNode.java
- partiql-ast/src/main/java/org/partiql/ast/AstVisitor.java
- partiql-ast/src/main/java/org/partiql/ast/DataType.java
- partiql-ast/src/main/java/org/partiql/ast/Identifier.java
- partiql-ast/src/main/java/org/partiql/ast/ddl/AttributeConstraint.java
- partiql-ast/src/main/java/org/partiql/ast/ddl/TableConstraint.java
- partiql-ast/src/main/java/org/partiql/ast/ddl/package-info.java
- partiql-ast/src/main/java/org/partiql/ast/dml/ConflictAction.java
- partiql-ast/src/main/java/org/partiql/ast/dml/package-info.java
- partiql-ast/src/main/java/org/partiql/ast/expr/ExprIsType.java
- partiql-ast/src/main/java/org/partiql/ast/expr/ExprOperator.java
- partiql-ast/src/main/java/org/partiql/ast/expr/ExprParameter.java
- partiql-ast/src/main/java/org/partiql/ast/expr/ExprRowValue.java
- partiql-ast/src/main/java/org/partiql/ast/expr/package-info.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphDirection.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphLabel.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphMatch.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphPart.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphPattern.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphQuantifier.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphRestrictor.java
- partiql-ast/src/main/java/org/partiql/ast/graph/GraphSelector.java
- partiql-ast/src/main/java/org/partiql/ast/graph/package-info.java
- partiql-ast/src/main/java/org/partiql/ast/package-info.java
- partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
- partiql-ast/src/main/kotlin/org/partiql/ast/Ast.kt
- partiql-ast/src/main/kotlin/org/partiql/ast/AstRewriter.kt
- None
- Add missing javadoc
- Add missing package-info.java
- Mark graph AST nodes as experimental
- Cleanup of AST visitor naming
- Followup on Identifier naming comment https://github.com/partiql/partiql-lang-kotlin/pull/1700#discussion_r1908001777
> [v1] AST docs and public API cleanup

- partiql-parser/build.gradle.kts
- partiql-parser/src/main/java/org/partiql/parser/PartiQLParser.java
- partiql-parser/src/main/java/org/partiql/parser/package-info.java
- partiql-parser/src/main/kotlin/org/partiql/parser/Exceptions.kt
- partiql-parser/src/main/kotlin/org/partiql/parser/internal/PErrors.kt
- partiql-parser/src/main/kotlin/org/partiql/parser/internal/PartiQLParserDefault.kt
- partiql-parser/src/test/kotlin/org/partiql/parser/internal/ArgumentsProviderBase.kt
- partiql-parser/src/test/kotlin/org/partiql/parser/internal/PTestDef.kt
- partiql-parser/src/test/kotlin/org/partiql/parser/internal/PartiQLParserDDLTests.kt
- None
- Parser package audit
- Added missing javadoc for public APIs
- Cleaned up warnings within code + build scripts
> [v1] Parser docs and cleanup

- CHANGELOG.md
- gradle.properties
> Release v1.0.0

- CHANGELOG.md
- gradle.properties
- partiql-eval/src/test/kotlin/org/partiql/eval/internal/CteTests.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
```shell
% git diff 97741fa2ff9c811c2803fb194582b04d26a66e5f..HEAD --name-only | grep api
partiql-ast/api/partiql-ast.api
partiql-spi/api/partiql-spi.api
% git diff 97741fa2ff9c811c2803fb194582b04d26a66e5f..HEAD -- partiql-ast/api/partiql-ast.api
% git diff 97741fa2ff9c811c2803fb194582b04d26a66e5f..HEAD -- partiql-spi/api/partiql-spi.api
```
> Releases v1.1.0

- CHANGELOG.md
- partiql-ast/api/partiql-ast.api
- partiql-ast/src/main/java/org/partiql/ast/sql/SqlDialect.kt
- partiql-ast/src/test/kotlin/org/partiql/ast/sql/SqlDialectTest.kt
- partiql-plan/src/main/java/org/partiql/plan/rex/RexPathIndex.java
- partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/PlanTransform.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/internal/transforms/RexConverter.kt
- partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt
- partiql-planner/src/test/kotlin/org/partiql/planner/PlannerPErrorReportingTests.kt
- None
- Fixing some miscellaneous issues encountered while working to upgrade Scribe to use PLK-1.x. See the CHANGELOG or the self-review for more details.
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**: Yes
- Any backward-incompatible changes? **[YES/NO]**: No
- Any new external dependencies? **[YES/NO]**: No
- Do your changes comply with the [contributing][cg] and [code style][csg] guidelines? **[YES/NO]** Yes
> fix: misc issues when working with PLK-1.x

- CHANGELOG.md
- gradle.properties
- None
- Prepares v1.2.1 release
> release: v1.2.1

- CHANGELOG.md
- build.gradle.kts
- gradle.properties
- None
- Prep new patch release
> release: v1.2.2

- CHANGELOG.md
- gradle.properties
- None
- Prep next snapshot version
> chore: prep v1.2.3-SNAPSHOT

- CHANGELOG.md
- partiql-eval/src/test/kotlin/org/partiql/eval/internal/IntervalDivideTests.kt
- partiql-eval/src/test/kotlin/org/partiql/eval/internal/IntervalTimesTests.kt
- partiql-planner/src/test/kotlin/org/partiql/planner/internal/typer/operator/OpArithmeticTest.kt
- partiql-spi/src/main/java/org/partiql/spi/types/PType.java
- partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/DiadicOperator.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnDivide.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/function/builtins/FnTimes.kt
- partiql-spi/src/main/kotlin/org/partiql/spi/utils/IntervalUtils.kt
- Closes Issue #1779
- Add support `INTERVAL` times or divide with numerics 
- Any backward-incompatible changes? **NO**:
- Any new external dependencies? **NO**:
- Do your changes comply with the [contributing][cg] and [code style][csg] guidelines? **YES**
> Add support INTERVAL times or divide with numerics #1779

- CHANGELOG.md
- gradle.properties
- None
- Prep new patch release
> release: v1.2.3
